### ISSUE TITLE
yaml download failed

### ISSUE THREAD

**Issue by qiyongxiao** [MacDownApp/macdown#1003]
Hi,I'm pre-build macdown. I meet an error with
```bundle exec pod install```
```
Installing LibYAML (0.1.4)

[!] Error installing LibYAML
[!] /usr/bin/curl -f -L -o /var/folders/3d/qhs4xyk15jsbwqpkrc3pkf940000gn/T/d20180731-42535-1muwk10/file.tgz http://pyyaml.org/download/libyaml/yaml-0.1.4.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to pyyaml.org port 80: Connection refused
```
I found this site has been become https, How do i change the download's url?

I update my macdown to '0.7.2', it's failure.

**Comment by franklinyu** [comment]
To debug, are you able to download from <http://pyyaml.org/download/libyaml/yaml-0.1.4.tar.gz> directly?

**Comment by uranusjr** [comment]
Their HTTP endpoint is broken. I think this needs to be filed to Cocoapods.

**Comment by uranusjr** [comment]
I’ve added a forked spec in MacDownApp/cocoapods-specs. This should work now. Please [report this problem to CocoaPods](https://github.com/CocoaPods/CocoaPods) so they can fix it.
