### ISSUE TITLE
missing or disorder editor pane sometimes

### ISSUE THREAD

**Issue by xiangp126** [MacDownApp/macdown#1006]
- version 0.71(870)
- OS: High Sierra 10.13.4

open a file using macdown through the command-line utility, sometimes the editor pane was missing

```bash
# launch iterm2
macdown /tmp/sshfs.md
```

![screen shot 2018-07-31 at 11 27 11](https://user-images.githubusercontent.com/8759365/43436844-c4f7e3b4-94b8-11e8-863c-5484e858ef16.png)

**Comment by franklinyu** [comment]
Note that in #908 you mentioned that this issue depends on specific files. For those affected files, does it happen every time (reliably reproducible), or it happens sometimes?

**Comment by xiangp126** [comment]
For those affected files, nearly but not exactly every time it happens like this.

and among my 6 md files, only 1 or 2 files ever happens like this, it's very strange.

**Comment by franklinyu** [comment]
So in order to reproduce the issue, could you please upload some sample?

**Comment by xiangp126** [comment]
@franklinyu how can I upload the file?

**Comment by franklinyu** [comment]
There is an “upload attachment” button. Alternatively you can [drag and drop](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by xiangp126** [comment]
upload file did not support .md suffix, so I change it to .txt
[sshfs.txt](https://github.com/MacDownApp/macdown/files/2252257/sshfs.txt)

**Comment by xiangp126** [comment]
it occurs very frequently, I think it has nothing to do with the file content and format itself.

Because I use vim , so command-line tool is very helpful for me.
