### ISSUE TITLE
The software itself does not support strikethrough

### ISSUE THREAD

**Issue by OCDpunk** [MacDownApp/macdown#1010]
The software itself does not support strikethrough
Does the next version consider adding the strikethrough?
```
~~test~~
```
~~test~~

**Comment by franklinyu** [comment]
Please enable it in preferences.

**Comment by alanhg** [comment]
![image](https://user-images.githubusercontent.com/9245110/68205164-8afe1d00-0004-11ea-81ac-14a30696a16f.png)
