### ISSUE TITLE
How to display the number of words？

### ISSUE THREAD

**Issue by ripperhe** [MacDownApp/macdown#1011]

**Comment by shuchenliu** [comment]
#### Usually checking Preferences would answer questions like this.

<img width="383" alt="screen shot 2018-08-22 at 10 36 30 am" src="https://user-images.githubusercontent.com/5944967/44480143-62ecee80-a5f7-11e8-9751-e45c3b148337.png">

**Comment by ripperhe** [comment]
But when I turned this on, I only saw this change, I didn't see the number of words
![jietu20180823-090207](https://user-images.githubusercontent.com/13943595/44498828-7eb5ca80-a6b3-11e8-930c-b176dd62d995.png)
![jietu20180823-090123](https://user-images.githubusercontent.com/13943595/44498830-82e1e800-a6b3-11e8-9643-78a44828474e.png)

**Comment by ripperhe** [comment]
@shuchenliu 
@franklinyu

**Comment by franklinyu** [comment]
That is known issue #812. Will be available in next release.

**Comment by ripperhe** [comment]
OK, thank you!
