### ISSUE TITLE
Looks like complete rip off MacDown

### ISSUE THREAD

**Issue by stonevil** [MacDownApp/macdown#1013]
This product looks like complete rip off MacDown

http://markeditor.incasedo.cn
https://itunes.apple.com/us/app/markeditor/id1398414250?mt=12

**Comment by uranusjr** [comment]
Hi, thanks for the heads up! MacDown is released under the MIT license, meaning that it *does not* prohibit derived works, as long as they provide the original license, so rip-offs are technically allowed. The app, however, does not seem to contain a copy of the license, which is a problem. I have personally [submitted a claim](https://www.apple.com/legal/internet-services/itunes/appstorenotices/#?lang=en) to Apple to resolve the issue.

**Comment by stonevil** [comment]
This is exactly what I'm noticed. Zero information about original product and license.

Anyway. Thanks for MacDown. Still best markdown editor for macOS for tech documentation. Vim everything. MacDown for markdown.
