### ISSUE TITLE
display character bug

### ISSUE THREAD

**Issue by qiyongxiao** [MacDownApp/macdown#1017]
if I write sometimes words on it:
```
export LDFLAGS="-L/usr/local/opt/libffi/lib
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
password = jdiuo^DKA432
``` 
will show error:
![image](https://user-images.githubusercontent.com/7349963/45795645-4b288900-bccf-11e8-8660-98b59a558d2f.png)

could this will be fix by next version ?

**Comment by franklinyu** [comment]
This is an extension of Markdown. Turn off underline in preference panel.
