### ISSUE TITLE
next release & macOS Mojave support

### ISSUE THREAD

**Issue by alexkaessner** [MacDownApp/macdown#1018]
Hello MacDown'ers,

I have to ask it! When will the next version of MacDown be released? The latest version (0.7.1) was released over one year ago. Since then there was done a lot to improve MacDown. Would be sad if this work will never be released for all users out there.

As [mentioned on Twitter](https://twitter.com/MacDownApp/status/982213584531763203) the v1.0 is just around the corner. What's holding up the release? Is there anything we can test to validate the release?

----
![Dark Mode Screenshot](https://pbs.twimg.com/media/Dfjw0UlX0AAZEGG.jpg:large)
My second part of the question is if the next version will already support the macOS Mojave dark mode? As [I posted on Twitter](https://twitter.com/alexkaessner/status/1006819334168236032) this will look just awesome! Shouldn't be much work, as we basically just have to build this with Xcode 10.

**Comment by franklinyu** [comment]
Did you try building MacDown in Xcode 10? Currently MacDown is not working with the new building system introduced in Xcode 10, at least on my machine.

**Comment by rschiang** [comment]
@FranklinYu As it is a build system regression, I eventually just switched to the [old build system](https://stackoverflow.com/questions/50709330/cycle-inside-building-could-produce-unreliable-results-xcode-10-error) on Xcode 10. Hope this helps.

**Comment by alexkaessner** [comment]
Honestly I'm always just running the default "build and run" command of Xcode (with missing version number and so on). Though the app itself was working I guess that doesn't really help shipping the "real" version …

**Comment by inevity** [comment]
Bulit  master on 10.14.2 (18C54) macos.  OK. But no graphviz or mermaid preferences.

**Comment by alexkaessner** [comment]
@FranklinYu @uranusjr If Xcode 10 isn't working yet, you could still release it with the old build system. I mean the dark mode isn't that important (though it would be cool). **It's more about all these improvements that were made over the last 1.5 years, that the users are still waiting for and never received.**

**Comment by briantully** [comment]
A new release would be very much appreciated!

**Comment by jeaes87** [comment]
I agree with @alexkaessner and @briantully. A new release would be very much appreciated. You've done great work on the toolbar and I really really miss it (from previous versions). I'd like to see that come to life!

**Comment by briantully** [comment]
Can anyone who has successfully build MacDown in XCode 10 please share how they did it? OR share a link to your build?

I've spent the past couple of hours trying to build MacDown with no luck, using the Xcode "new build system" as well as the "legacy build system" to no avail.
I keep getting linker errors related to GBCli library not being found (even though it does get installed with `bundle exec pod install`).

**Comment by briantully** [comment]
Anyone? Bueller?

**Comment by dpinol** [comment]
The toolbar has disappeared on 0.7.1 right?

**Comment by FranklinYu** [comment]
@dpinol It’s only available in testing channel so far.

**Comment by legoming** [comment]
what's the plan of next release?

**Comment by alexkaessner** [comment]
I just thought I test building it with the Xcode 11 beta 3. I've updated the cocoapods _(handlebars-objc to 1.4.6 & Sparkle to 1.21.3)_ and used the "new build system". And it worked!

I'm not that deep into the development with all the libraries and different building systems, but where is the problem with the building then?

**Comment by dpinol** [comment]
any news? missing the toolbar

**Comment by FranklinYu** [comment]
Hi guys. 0.7.2 is the first release that I made (with great help from @uranusjr). It is almost the same as [0.7.2d137](https://macdown.uranusjr.com/history/testing/#version_1007); I hope you guys like it. I would soon (?) release a new version in testing channel as well, but there’s no commitment.

**Comment by alexkaessner** [comment]
@FranklinYu @uranusjr Awesome guys!! Thanks for the release! I bet the community still wants MacDown alive, so let's help you to keep it that way. Seems like you found a way to fix the building system problems?

PS: I will close this issue as the main point was to continue updating MacDown and that just happened.

**Comment by briantully** [comment]
FWIW, on 0.7.2 I am seeing bad flickering in the preview window on every keystroke. I had to revert to the previous 0.7.2d137 release. I've also recently discovered both "Mark Text" and "Typora" apps, and must say they are very impressive and very polished/stable.
