### ISSUE TITLE
$\hat X$ display error

### ISSUE THREAD

**Issue by JohnYang-2718** [MacDownApp/macdown#1022]
The hat symbol skews to the right.
<img width="855" alt="screen shot 2018-10-17 at 15 48 19" src="https://user-images.githubusercontent.com/15006150/47070569-1c48f880-d224-11e8-913a-71bda77da3ef.png">

**Comment by andrey-popov** [comment]
\tilde is also affected in the same way.

**Comment by franklinyu** [comment]
This is issue of either MathJax or Safari. Minimal HTML document to reproduce:

```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
</head>

<body>
  <p>\(\hat\sigma\)</p>
  <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    'showProcessingMessages': false,
    'messageStyle': 'none'
  });

  if (typeof MathJaxListener !== 'undefined') {
    MathJax.Hub.Register.StartupHook('End', function () {
      MathJaxListener.invokeCallbackForKey_('End');
    });
  }
  </script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
</body>

</html>
```

This works fine in Chrome, but not in Safari. MacDown uses WebView which is essentially Safari.

**Comment by GitHub27182818** [comment]
I tried right click the formula, Math Settings/Math Renderer/SVG, and the math rendering appears to be normal. The display error only occurs when I choose Math Renderer/HTML-CSS.

**Comment by franklinyu** [comment]
@GitHub27182818 Try https://macdown.uranusjr.com/history/testing/ ?
