### ISSUE TITLE
Jump within a document doesn't work

### ISSUE THREAD

**Issue by NatashaLi-ESPRESSIF** [MacDownApp/macdown#1030]
It seems I cannot jump to different sections within a .md document using Mac.

I am sure the I am using the right grammar because:
1. I've tried the Help document, which doesn't jump properly 
2. I've tried the exact document with another Mac computer, which does jump as expected.

<img width="1372" alt="6eaa40b2-5c9d-4544-b44e-43a5a9ec4f85" src="https://user-images.githubusercontent.com/29246225/48556772-cd27dd80-e91f-11e8-8bff-db66f14b94c4.png">

I am using a Macbook pro and I've tried to reinstall the software.

I am not sure why is that? could you pls help?

**Comment by FranklinYu** [comment]
OS version please? Also please refer to #924.

**Comment by NatashaLi-ESPRESSIF** [comment]
OS: macOS High Sierra 10.13.3
Macdown version: 0.7.1 (870)

**Comment by FranklinYu** [comment]
As mentioned in #924, please upgrade to latest High Sierra.
