### ISSUE TITLE
Syntax highlight of link is invalid with space symbol

### ISSUE THREAD

**Issue by bearzyj** [MacDownApp/macdown#1036]
**1 Environment**
MacDown version : 0.7.1 (870)
macOS Mojave Version : 10.14.1

**2 Issue description**
```markdown
[Test 1](#Test 1)
[Test 2](#Test_2)

<a name="Test 1"></a>
#Test 1

<a name="Test_2"></a>
#Test 2
```
As above, for "Test 2" link MacDown could show the green syntax highlight while "Test 1" cannot, while both of the two links are workable.

**3 Expected behavior**
In above case, "Test 1" should have the same green syntax highlight as "Test 2" does inside MacDown App.

**Comment by uranusjr** [comment]
Hash can’t contain spaces. The highlighter gets confused because the syntax is invalid, leading to undefined behaviours.
