### ISSUE TITLE
Customize css of mermaid

### ISSUE THREAD

**Issue by legoming** [MacDownApp/macdown#1043]
How can I customize mermaid css in MacDown and make it effect? Any guideline?

**Comment by FranklinYu** [comment]
IIUC you can do it in “Style” just like other part of Markdown.

**Comment by legoming** [comment]
Yes, I know how to customize css for preview. But how can I customize mermaid? Same way?

**Comment by FranklinYu** [comment]
Yes, the CSS should apply to the entire page.

**Comment by legoming** [comment]
OK, I try it. Thanks for your kindly answer.
