### ISSUE TITLE
failed to render latex math equation

### ISSUE THREAD

**Issue by liuzqt** [MacDownApp/macdown#1046]
I've just installed mactex, and try to view some latex document, it render correctly, so I believe the latex engine is installed correctly in my machine.

But when I use macdown to type some math equation, it won't render.

a small example

```
$$
    \frac{dR}{dt}=k_{in}f(R)-k_{out}g(R)
$$

```

I'm using macOS 10.14. 

I don't know how markdown engine parse those math equation, I guess the markdown application call the latex engine and the latex engine will render them? Any idea to debug with this problem?

**Comment by FranklinYu** [comment]
It’s disabled by default. You need to enable it in preferences. In addition, it’s rendered with MathJax (though we are considering KaTeX), not with your local LaTeX environment.
