### ISSUE TITLE
Find a way to change italic markup

### ISSUE THREAD

**Issue by gregoirenoyelle** [MacDownApp/macdown#1047]
Hi,

I write a lot of documentation in markdown with function name like my_function(). In **MacDown** that will make italic text. Of course, I can use in my name my\_function() but it's add a lot of work. 
Is there a way in Macdown set up for using "*" instead for italic.
Thanks.

Cheers,
Grégoire

**Comment by uranusjr** [comment]
Use inline code (backticks), or turn off intra-word emphasis.
