### ISSUE TITLE
Arrow symbols not aligned

### ISSUE THREAD

**Issue by ggnam** [MacDownApp/macdown#1053]
![Sample Image](https://i.imgur.com/zJ3Xnot.png)

As you see the picture as above, the arrow symbol (→) is neither centered nor aligned on the result page.

I don't know why this happens. I tested this on GitHub markdown editor, not showing error.

**Comment by FranklinYu** [comment]
Why would you expect arrow symbol to be centered or aligned?

**Comment by ggnam** [comment]
Sorry if get notified! I'm closing the issue since it's too outdated 😅
