### ISSUE TITLE
Add screenshot of the app to README.md

### ISSUE THREAD

**Issue by whyboris** [MacDownApp/macdown#1059]
I really appreciate when I know what I'm about to download. More-often-than-not I just don't download the app.

Perhaps just include the screenshot of the app as the first thing visitors see when they come to GitHub?

![image](https://user-images.githubusercontent.com/17264277/54693475-1752e280-4afd-11e9-83b2-573f9196e1e4.png)

ps - I'm aware that there is a screenshot on the website: https://macdown.uranusjr.com/

**Comment by uranusjr** [comment]
Pull request welcomed :)
