### ISSUE TITLE
Build instructions out of date?

### ISSUE THREAD

**Issue by JetForMe** [MacDownApp/macdown#1061]
Are the build instructions out of date? I had issues using `bundle exec pod install`, but `pod install` worked after I updated cocoapods.

**Comment by FranklinYu** [comment]
The build instruction is up-to-date, and I just tried again. What’s the issue using `bundle exec pod install`?

**Comment by JetForMe** [comment]
The main error is "ArgumentError - Malformed version number string". I'm not really sure how `bundle exec` is different from `pod install`, but maybe it's running a different `pod` executable?

Here's the full transcript:

```
 repo/ (lz/dateTools) 17:33$ bundle exec pod install
Analyzing dependencies
Downloading dependencies
Using GBCli (1.1)
Using JJPluralForm (2.1)
Installing LibYAML (0.1.4)
Using M13OrderedDictionary (1.1.0)
Using MASPreferences (1.3)
Using PAPreferences (0.5)
Using Sparkle (1.18.1)
Using handlebars-objc (1.4.5)
Using hoedown (3.0.7)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/lib/ruby/gems/2.5.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.3_1/lib
Repositories : macdownapp - https://github.com/MacDownApp/cocoapods-specs.git @ 8db889cd3472ec88521227a7eff5d50fd066fcc8
               master - https://github.com/CocoaPods/Specs.git @ 263a353540cdd3f23ee6d03c73771b5d0b3d946d
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :osx, "10.8"

source 'https://github.com/MacDownApp/cocoapods-specs.git'  # Patched libraries.
source 'https://github.com/CocoaPods/Specs.git'

project 'MacDown.xcodeproj'

inhibit_all_warnings!

target "MacDown" do
  pod 'handlebars-objc', '~> 1.4'
  pod 'hoedown', '~> 3.0.7', :inhibit_warnings => false
  pod 'JJPluralForm', '~> 2.1'
  pod 'LibYAML', '~> 0.1'
  pod 'M13OrderedDictionary', '~> 1.1'
  pod 'MASPreferences', '~> 1.3'
  pod 'Sparkle', '~> 1.18', :inhibit_warnings => false

  # Locked on 0.4.x until we drop 10.8.
  pod 'PAPreferences', '~> 0.4'
end

target "MacDownTests" do
  pod 'PAPreferences', '~> 0.4'
end

target "macdown-cmd" do
  pod 'GBCli', '~> 1.1'
end
```

### Error

```
ArgumentError - Malformed version number string 
/usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/version.rb:209:in `initialize'
/usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/version.rb:200:in `new'
/usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/version.rb:200:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:119:in `embedded_content_settings'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:64:in `generate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:109:in `update_changed_file'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `create_xcconfig_file'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:173:in `block (2 levels) in install_libraries'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:171:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:171:in `block in install_libraries'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:165:in `install_libraries'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:183:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.5.0/bin/pod:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - - ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.
   https://github.com/CocoaPods/CocoaPods/issues/8240 [closed] [16 comments]
   4 days ago

 - pod cache list
   https://github.com/CocoaPods/CocoaPods/issues/8460 [closed] [2 comments]
   28 Jan 2019

 - Malformed version number string
   https://github.com/CocoaPods/CocoaPods/issues/7765 [closed] [46 comments]
   03 Nov 2018

and 38 more at:
https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20&type=Issues&utf8=✓

[!] Found multiple specifications for `LibYAML (0.1.4)`:
- /Users/rmann/.cocoapods/repos/macdownapp/LibYAML/0.1.4/LibYAML.podspec.json
- /Users/rmann/.cocoapods/repos/master/Specs/5/b/9/LibYAML/0.1.4/LibYAML.podspec.json
```

**Comment by FranklinYu** [comment]
> I'm not really sure how `bundle exec` is different from `pod install`, but maybe it's running a different `pod` executable?

It’s using the CocoaPods version specified in `Gemfile.lock`. See https://bundler.io

**Comment by FranklinYu** [comment]
This looks like CocoaPods issue. Please file issue against them.

There seems to be some related information and links in error message; I suggest read it before filing issues.

**Comment by iFredOS** [comment]
On my side, I can't build the project with the latest commit. I attached the log.

[Build target peg-markdown-highlight_2019-04-18T04-44-01.txt](https://github.com/MacDownApp/macdown/files/3093492/Build.target.peg-markdown-highlight_2019-04-18T04-44-01.txt)

**Comment by FranklinYu** [comment]
@iFredOS There is some fundamental issue in your build environment if it cannot find `stdio.h`. The entire operating system relies on it.

**Comment by iFredOS** [comment]
@FranklinYu I followed those [instructions](https://github.com/MacDownApp/macdown/blob/master/README.md#development), what can I do more?

**Comment by FranklinYu** [comment]
@iFredOS Typically Xcode should find the system headers without any configuration. Your case is very weird; missing `stdio.h` sounds like “my macOS don’t have Finder.app”. I’m trying to help you debugging your Xcode setup, but I can’t guarantee anything.

Please try compiling a simple C application in command line to see whether Clang can find the headers. Something like

```c
#include <stdio.h>

int main(void) {
    printf("hello!\n");
    return 0;
}
```

**Comment by iFredOS** [comment]
I understand your analogy. It works without issues. I will erase the project and redo everything. Sorry for bothering you. Thanks for the help.

**Comment by iFredOS** [comment]
@FranklinYu Still the same issue after I redownloaded everything and redone the commands. Maybe I don't build your project correctly. I just do command+B and it fail.

**Comment by iFredOS** [comment]
@FranklinYu I did a `make` in `macdown/Dependency/peg-markdown-highlight/greg` and now I can build MacDown. Does it make any senses I needed to do that?

**Comment by FranklinYu** [comment]
You shouldn’t need to do that. That works because your CLI environment can find the headers, while Xcode cannot. When you are compiling in CLI, which compiler are you using? Typically it would be in `/usr/bin/`.

**Comment by iFredOS** [comment]
I'm new to this world of development. I only know Java. I already compiled some project by following instruction but I cannot answer your question for C compiler.

**Comment by FranklinYu** [comment]
@iFredOS That’s fine. Welcome to C programming! In C we use something like `gcc`, `clang`, or `cc` to compile. How did you compiled the example C program that I provide earlier? Something like `gcc main.c` or `make main`?

**Comment by FranklinYu** [comment]
@iFredOS Please add your findings to #1072. I’m closing this issue since it was originally a different one.

**Comment by iFredOS** [comment]
> @iFredOS That’s fine. Welcome to C programming! In C we use something like `gcc`, `clang`, or `cc` to compile. How did you compiled the example C program that I provide earlier? Something like `gcc main.c` or `make main`?

I used `make`.
