### ISSUE TITLE
Front matter rendering broken in master?

### ISSUE THREAD

**Issue by JetForMe** [MacDownApp/macdown#1062]
The released version 0.7.1 seems to render front matter correctly, but master does not. Is this a known problem?

![0 7 1](https://user-images.githubusercontent.com/401600/55446490-bb647100-5574-11e9-94ba-2fcb1a89e64d.png)

![master](https://user-images.githubusercontent.com/401600/55446518-d6cf7c00-5574-11e9-9229-4df3667c9bcc.png)

**Comment by uranusjr** [comment]
When in doubt, quote your strings.

**Comment by JetForMe** [comment]
Hmm, I tried that, no luck. I tried reducing the front matter to just

```
---
layout: post
---
```

And it still renders incorrectly.

**Comment by JetForMe** [comment]
Ahahahahaaa my bad. Sorry. I hadn't turned on the Pref for front matter. I'm an idiot. It was on in the release app but the one I built from Xcode seems to have a different bundle ID or something, and has separate prefs. Maybe Sandboxing? I don't know. My bad.

**Comment by uranusjr** [comment]
It is indeed weird why Xcode would use a different bundle ID, but that wouldn’t be the first time Xcode being weird. Glad you worked it out!
