### ISSUE TITLE
[mermaid][sequenceDiagram] How can I change the self-self loop line from curved to linear style?

### ISSUE THREAD

**Issue by legoming** [MacDownApp/macdown#1068]
_When writing sequenceDiagram like this_

```mermaid
sequenceDiagram
participant Alice
participant Bob
Alice->>John: Hello John, how are you?
loop Healthcheck
John->>John: Fight against hypochondria
end
Note right of John: Rational thoughts <br/>prevail...
John-->>Alice: Great!
John->>Bob: How about you?
Bob-->>John: Jolly good!
```

_we get output like this_

![](https://live.staticflickr.com/7840/47568921691_86e707edfe_z_d.jpg)

<font color=dark>**I just want to change the loop line for "John->>John: Fight against hypochondria" from curved line to liner line, how can I customize it?**</font>

**Comment by FranklinYu** [comment]
This is mermaid specific issue, and you will get much better response if you ask the mermaid community. You can also play with their [live editor](https://mermaidjs.github.io/mermaid-live-editor/) to see how you can achieve the desired effect.

**Comment by legoming** [comment]
@fcanas OK, got it. Thanks.

**Comment by FranklinYu** [comment]
Of course, if you find something working in mermaid, but not working in MacDown mermaid, feel free to re-open this issue.
