### ISSUE TITLE
How can I remove the prefix dot and line-space between parent header and child header from TOC?

### ISSUE THREAD

**Issue by legoming** [MacDownApp/macdown#1069]
In a word, just wanna a compact and simple list of header title with indent fo sub-header, how can I customize it?

**Comment by FranklinYu** [comment]
Please provide a screenshot or explain more about which part you want to remove.

**Comment by legoming** [comment]
Current toc style is like this:
![](https://live.staticflickr.com/7818/46687188835_08a10b1932_z_d.jpg)

But as I used MD to write some documents with tens of pages who has long toc, in that case, I just want a simple list with indent like this:

![](https://live.staticflickr.com/7846/46687188995_2d4882a39f_o_d.png)

**Comment by FranklinYu** [comment]
Yes this is possible. Do you know some CSS?

**Comment by legoming** [comment]
Yes. I reused github2 theme and customized a little- font, color, even some new tag.
But don’t know how to customize toc.

**Comment by FranklinYu** [comment]
If you look at the generated HTML, the generated TOC is actually `<ul>`, so you can change the margin between them. As for bullet, see [this question](https://stackoverflow.com/questions/1027354/need-an-unordered-list-without-any-bullets).

**Comment by legoming** [comment]
Thanks @FranklinYu 

I can remove bullets now by setting `<ul>` like this

```html
ul {
  list-style-type: none;
}

ul.toc {
  font-family: Roboto, "Noto Serif SC";
  color: #134e8e;
  //margin-left: -28px;
}

ul.toc:before {
  content: "Table of Content\00000A\00000A";
  white-space: pre;
  font-weight: bold;
}

ul li {
  /*margin-top: -20px;*/
  padding-left: -10px;
  line-height: 25px;
}

ul li:first-child {
  margin-top: -20px;
}

ul li:last-child {
  margin-bottom: -20px;
}
```


![](https://live.staticflickr.com/7917/47558017632_6f89c9c0f9_z_d.jpg)

**Comment by legoming** [comment]
previous customize has side effect on unordered list, adjust like this

```
ul.toc {
  list-style-type: none;
  font-family: Roboto, "Noto Serif SC";
  color: #134e8e;
  //margin-left: -28px;
}

ul.toc:before {
  content: "Table of Content\00000A\00000A";
  white-space: pre;
  font-weight: bold;
}

ul.toc li {
  list-style-type: none;
  /*margin-top: -20px;*/
  padding-left: -10px;
  line-height: 25px;
}

ul.toc li:first-child {
  margin-top: -20px;
}

ul.toc li:last-child {
  margin-bottom: -20px;
}
```
