### ISSUE TITLE
Remove mou campaign reference from homepage

### ISSUE THREAD

**Issue by daten-kieker** [MacDownApp/macdown#1073]
On the [homepage](https://macdown.uranusjr.com/) the [Indiegogo campaign](https://www.indiegogo.com/projects/mou-1-0-markdown-editor-on-os-x-for-you#/) for mou is still linked. Given that delivery promised for 2015-08-31 has not yet appeared and that [the author](https://twitter.com/chenluois) seems to be inactive sind 2015-07-27 this is only a distraction.

I think it's great to give credit to the origins of MacDown but these links on the MacDown homepage were a waste of time to me.

**Comment by FranklinYu** [comment]
Please create an issue at https://github.com/MacDownApp/macdown-site thanks!
