### ISSUE TITLE
Code blocks inside unordered lists require leading newline

### ISSUE THREAD

**Issue by oalders** [MacDownApp/macdown#1078]
I noticed today that fenced code inside an unordered list seems to require a leading newline in order to display correctly.   This is Version 0.7.1 (870)

> * first list
> * my list item
> ```
> my code
> more code
> ```
> * my third list item
> 
> * second list
> * other list item
> 
> ```
> my code
> more code
> ```
> * my third list item

<img width="730" alt="Screen Shot 2019-05-30 at 13 59 10" src="https://user-images.githubusercontent.com/96205/58653178-287d5400-82e3-11e9-98a0-946d4416ddbf.png">

**Comment by FranklinYu** [comment]
If you want code blocks to be *inside* items, then correct markup would be

````markdown
*   Variables

    ```c
    int a = 1;
    ```

*   Functions

    ```c
    int add(int x, int y) {
        return x + y;
    }
    ```
````

Preview:

> *   Variables
>
>     ```c
>     int a = 1;
>     ```
>
> *   Functions
>
>     ```c
>     int add(int x, int y) {
>         return x + y;
>     }
>     ```

So this is pretty much the expected behavior. I'm closing this, but you can still leave comments if this confuses you.

**Comment by oalders** [comment]
Great.  Thanks for this!
