### ISSUE TITLE
Plugins not loading?

### ISSUE THREAD

**Issue by JetForMe** [MacDownApp/macdown#1091]
Hi. I finally got around to making a plugin for Macdown, and I can't get it to load. I tried the example plugin at https://github.com/MacDownApp/macdown-gistit, and it doesn't show up in the menu, either.

**Comment by FranklinYu** [comment]
I can load “Gist it!” without issue. Where did you put it?

**Comment by JetForMe** [comment]
Hmm, I couldn't find the built plug-in at all, not sure where I had installed it, but the Readme was pretty clear, so I'm sure I put it there. It seems to load now, anyway.
