### ISSUE TITLE
Website outdated link to Github "fenced code blocks"

### ISSUE THREAD

**Issue by msikma** [MacDownApp/macdown#1097]
The top of the [features page](https://macdown.uranusjr.com/features/) links to "[https://help.github.com/articles/github-flavored-markdown#fenced-code-blocks](https://help.github.com/articles/github-flavored-markdown#fenced-code-blocks)" when mentioning fenced code blocks, but the link should be changed to "[https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks)".

**Comment by FranklinYu** [comment]
Please copy this issue to https://github.com/MacDownApp/macdown-site. Thanks!
