### ISSUE TITLE
Connecting to googletagmanager.com on startup?

### ISSUE THREAD

**Issue by stevelord** [MacDownApp/macdown#1102]
Hi,

The Lulu firewall reports that Macdown wants to connect to googletagmanager.com on startup. Has any google analytics tracking been embedded into the app?

I'm running Mojave and Macdown 0.7.1 (870).

Cheers,
Steve

**Comment by uranusjr** [comment]
I don’t recall embedding any kind of tracking code. The closest I can think of is maybe WebKit is being too smart and trying to prefetch something prematurely.

**Comment by uranusjr** [comment]
Please do tell me if you ever find out what is causing the request though, I’ll definitely remove it if possible.

**Comment by stevelord** [comment]
My first thoughts were either webkit or some other component. I'll drop the rule and see if it pops back up. If it does I'll look into it when I get time. I'd suggest closing this issue for now and I can create a new one if I find anything.

Thanks for the great software!
