### ISSUE TITLE
Preferences trouble

### ISSUE THREAD

**Issue by dyp2000** [MacDownApp/macdown#1103]
Mac OS 10.15.1 Catalina 
MacDown Version 0.7.2 (1008)

![ScreenShot 2019-11-18 в 12 16 58](https://user-images.githubusercontent.com/79825/69032148-a18d7680-09fd-11ea-9267-96d565b64010.png)

**Comment by alexkaessner** [comment]
Same here with Version 0.7.2 (1008) on macOS Catalina

**Comment by luckman212** [comment]
I can't even get 0.7.2 to launch on Catalina 10.15.1:
![image](https://user-images.githubusercontent.com/1992842/69056693-80695d80-09de-11ea-86ab-6501658ac43a.png)
Tried downloading several times. Something's not right.

**Comment by jzaehrin** [comment]
I have the same issue, i try by zip or brew.

**Comment by FranklinYu** [comment]
I'll try it when I get back home tonight. If the Zip file is somehow damaged I'll upload a new one here (in this issue as an attachment) so that you guys can test it before I push it to the world.

**Comment by FranklinYu** [comment]
The preference panel issue seems to be independent of the binary corruption issue. The binary issue would be tracked in #1106. I’m still working on this issue.

**Comment by machale** [comment]
When I tried 0.7.2 on macOS 10.14.6 I saw the same mostly-empty panel in Preferences > Markdown as @dyp2000 so I don't think this is Catalina-specific.

**Comment by hernanBeiza** [comment]
Hi! I updated to 0.7.2 today and I have the same issue. I am using macOS Sierra (10.12.6)
![Screen Shot 2019-11-20 at 8 18 15 AM](https://user-images.githubusercontent.com/1325005/69234615-5ba3f000-0b6e-11ea-92b5-1fe07a95ff39.png)

**Comment by FranklinYu** [comment]
@hernanBeiza This issue belongs to #1106.

**Comment by Morane** [comment]
Hi,

What about the **bug in Preferences/Macdown** ? Do you plan to fix it ?

Best regards

![69032148-a18d7680-09fd-11ea-9267-96d565b64010](https://user-images.githubusercontent.com/15726635/70430640-83a2b700-1a7b-11ea-8e72-7d2d497fe97b.png)

**Comment by Morane** [comment]
What to do for the layman ? 🤔

**Comment by dyp2000** [comment]
> What to do for the layman ? 🤔

Wait for release

**Comment by FranklinYu** [comment]
> What about the **bug in Preferences/Macdown** ? Do you plan to fix it ?

My next priority would be a bugfix release, but no guarantee about time though. Sorry.

**Comment by FranklinYu** [comment]
The fix in PR will be included in 0.7.3; I’m still researching about reason of #1104 and I want to fix it before I make a new release.

**Comment by FranklinYu** [comment]
Heads-up: v0.7.3 fixes this issue without fixing #1104.
