### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by killobatt** [MacDownApp/macdown#1108]
Could you, please, add the Ukrainian language to the list of supported languages? I'd like to volunteer and help to make Ukrainian translation on [Transifex](https://www.transifex.com/macdown/macdown/).

**Comment by FranklinYu** [comment]
Please join https://www.transifex.com/macdown/macdown/language/uk_UA/

Thanks!

**Comment by killobatt** [comment]
Thanks!

**Comment by FranklinYu** [comment]
Hi, just to make sure: is this you?

https://www.transifex.com/user/profile/killobatt/

**Comment by killobatt** [comment]
Yes

**Comment by FranklinYu** [comment]
Sorry for the wait; I haven’t been able to find time for it. I approved it minutes ago. Thanks! Look forward to your contribution.
