### ISSUE TITLE
0.7.2 app "damanged" cannot run

### ISSUE THREAD

**Issue by ot-tony-archer** [MacDownApp/macdown#1115]
When I download from the site or when I install from homebrew I get the following popup after running the app:

`"MacDown" is damaged and can't be ipened. You should move it to the Trash.`

How to I fix this?  I love MacDown and need it badly :)

**Comment by ot-tony-archer** [comment]
Follow up:  Running this resolved it:

`xattr -cr /Applications/MacDown.app`

> -c clears attributes and -r does so recursively

**Comment by FranklinYu** [comment]
Duplicate of #1106
