### ISSUE TITLE
mermaid can't user axisFormat

### ISSUE THREAD

**Issue by Gowa2017** [MacDownApp/macdown#1126]
Code like this:

```mermaid
gantt
    dateFormat YYYY-MM-DD
    title 用户体系改造工作计划
       axisFormat %m-%d
    section 后台
    数据结构  :active,a1,2019-12-12,2019-12-16
    接口相关改造  :active,a2, after a1, 3d 
    
    section APP改造
    APP改版及登录  :active,b1, 2019-12-16, 5d
    APP端相关封装 :b2, after b1, 3d
    学习培训    :b3, after b2, 7d
    二七路     :b4, after b2, 7d
    校园食安    :b5, after b2, 7d
    企业管理    :b6, after b2, 7d
    营业执照-微企 :b7, after b2, 7d
    食品许可    :b8, after b2, 7d
    APP改造完成        :crit,s,2019-12-31, 1d
    
    section 集中测试
    集中测试 :c1, after s, 9d
    
    section 上线
    预上线 :d1, 2020-01-10,7d

```

In typora is Ok.
![image](https://user-images.githubusercontent.com/33367355/70876551-ebfe1500-1ff4-11ea-875d-ea8b362927ef.png)

**Comment by FranklinYu** [comment]
In MacDown we use v3.5.4. Is this feature available in this version?

**Comment by Gowa2017** [comment]
> In MacDown we use v3.5.4. Is this feature available in this version?

Seems not. I think it's in v8.0 .

**Comment by Gowa2017** [comment]
> In MacDown we use v3.5.4. Is this feature available in this version?

I found the upgrade mermaid to v8.0 is not so diffcult in vnote，but how the macdown implemention the mermaid, or it use mermaid.js ?

**Comment by FranklinYu** [comment]
I think it’s https://github.com/MacDownApp/macdown/tree/master/MacDown/Resources/Extensions

**Comment by Gowa2017** [comment]
@FranklinYu Yes, I try to upgrade it .

**Comment by legoming** [comment]
Great!
I just looking for how to change x-axis from week number to date in MacDown.
The week number shown in MacDown is not unified with the week number used inside.
