### ISSUE TITLE
Mermaid sequeceDiagram arrow head not show.

### ISSUE THREAD

**Issue by Gowa2017** [MacDownApp/macdown#1155]
The Code is :

```mermaid
sequenceDiagram

a ->> b:c 
```

On MacDown, the render out is 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/33367355/75124884-10f5bf00-56ed-11ea-91aa-8aa17eb4b3ee.png">

I export the file to .html. Open it in safari, same as macdown. But in Chrome is Ok.

Same to be the `marker-end="url(#arrowhead)` problem

**Comment by FranklinYu** [comment]
For quick copy-paste:

````markdown
```mermaid
sequenceDiagram

a ->> b:c 
```
````

Probably upstream bug.

> https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cbmEgLT4-IGI6YyIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

**Comment by FranklinYu** [comment]
Upstream bug: mermaid-js/mermaid#1269
