### ISSUE TITLE
update to 0.8.0d71 fails upon extracting archive

### ISSUE THREAD

**Issue by alexkli** [MacDownApp/macdown#1161]
I'm on MacDown `0.7.3 (1008.4)` and macOS `10.15.2`. Steps to reproduce:

1. MacDown > check for updates
2. getting this screen (my macOS is set to German)
   ![macdown-update](https://user-images.githubusercontent.com/229022/75732709-17b1a280-5ca8-11ea-8d61-6469d5ab8ebd.png)
3. click "Install"
4. wait for download and then click "Update"
5. tries to unpack and quickly fails with "there was an error while unpacking the archive. please try again later" with an "Cancel update" button (I am actually getting this error message in German, seems to be OS level)

I have seen this for more than a week and tried it a couple times, it always fails the same way.

**Comment by FranklinYu** [comment]
If you directly download from https://macdown.uranusjr.com/history/testing/ would you be able to open it?

**Comment by alexkli** [comment]
@FranklinYu Well, no. The download link at the top, next to "Version 0.8.0d71" actually points to 0.7.2:

https://github.com/MacDownApp/macdown/releases/download/v0.7.2/MacDown.app.zip

And when I install this, this gives me 0.7.2.

What is the link to the latest version?

**Comment by alexkli** [comment]
Figured it out myself: https://github.com/MacDownApp/macdown/releases/download/v0.8.0d71/MacDown.app.zip

This worked, the about screen now says Version 0.8.0d71

**Comment by FranklinYu** [comment]
> The download link at the top, next to "Version 0.8.0d71" actually points to 0.7.2:

Ah my bad, that's the culprit. Fixed it in MacDownApp/macdown-site@3018ad3deac6a74bb3ecbcb7a24f3bf42a5fd097 so future user should be able to update.

Thanks!
