### ISSUE TITLE
Could we implement a outline view?

### ISSUE THREAD

**Issue by Gowa2017** [MacDownApp/macdown#1166]
Like this:
![image](https://user-images.githubusercontent.com/33367355/76499599-015ed000-647a-11ea-8cfe-2496e15ebd53.png)

Or,thers is some method.
I 'm not so familiar with OC.
But I think, Macdown use js lib to render the markdown to html.It is possible to get the rendered html element info and can anchor to it?

**Comment by FranklinYu** [comment]
> Macdown use js lib to render the markdown to html.

Not currently. Please check README:

> MacDown depends a lot on other open source projects, such as [Hoedown](https://github.com/hoedown/hoedown) for Markdown-to-HTML rendering…

**Comment by FranklinYu** [comment]
Duplicate of #62
