### ISSUE TITLE
Install problem with home brew cask

### ISSUE THREAD

**Issue by MediEvil** [MacDownApp/macdown#1169]
When I use this command 'brew cask install macdown', it always download the latest testing version(0.8.0.d71). However, i cannot open it because of macOS unable to verify integrity.

My question is HOW TO install the stable v0.7.3 by brew cask command line tool.

Thanks

**Comment by reccanti** [comment]
Are you able to open it when you right click on the icon and select "Open" like this? I've noticed this with other Mac applications downloaded through the browser or with cask

<img width="318" alt="The menu that's shown when right-clicking on the MacDown application" src="https://user-images.githubusercontent.com/10334948/77757092-f1f98e00-7006-11ea-9931-1d140e891851.png">

**Comment by FranklinYu** [comment]
What @reccanti said is correct.

The version issue is independent. We don’t maintain the Cask (this is how Cask works); I actually have no idea why the stable cask seem to refer to that testing release, while there is already a separate Cask for testing channel. Maybe the contributor just wasn’t aware. You can talk to them about this, but remember they are also volunteers so be nice to them.

**Comment by MediEvil** [comment]
I tried @reccanti 's method, it still doesn't work.
But i change my system language to English, and reinstall the macdown with brew. It's can open now. 
Maybe there is a language problem about macdown with Chinese?

**Comment by MediEvil** [comment]
I tried @reccanti 's method, but it doesn't work.
I tried to download macdown from the browser, which version is 0.8.0d71, and i can open it now. 
I think maybe there is something wrong with cask, and i will talk to them nicely.
