### ISSUE TITLE
Vote: New App Icon for macOS Big Sur

### ISSUE THREAD

**Issue by alexkaessner** [MacDownApp/macdown#1208]
![MacDown Big Sur Icons](https://user-images.githubusercontent.com/6615076/92605546-278eec80-f2b2-11ea-8011-7b89438e530a.png)

Some weeks ago I’ve made different Big Sur versions of @mdznr nice icon. Most are inspired by Apples own new icons. **I’d be happy to contribute any one of them!**

I’ve asked on [Twitter](https://twitter.com/alexkaessner/status/1279399102112059392) which version most people like and the 3D version seems to be the favorite. Let’s see what the community here thinks as well. **Let’s use reactions to vote for each version:**
👍 = App Store
😄 = Podcasts
🎉 = Bluetooth File Exchange
❤️ = Feedback Assistant
🚀 = Bordered
👀 = 3D

**Comment by oxcug** [comment]
Great work here! NGL, I love the 3D one.

**Comment by jchen3652** [comment]
Just curious, when will this be merged in? Seems like we may have a winner?

**Comment by alexkaessner** [comment]
<img height="256" alt="app icon" src="https://user-images.githubusercontent.com/6615076/101685485-1a77ca00-3a68-11eb-8186-f67fb6d4a0d3.png">

Thanks for everyone participating! Indeed it’s time to contribute the winner icon to the repo. As you can see I’ve created the pull request. Now it’s up for @FranklinYu to merge the new icon and make a release out of it.  

If you want to use the icon as a replacement in the meantime go ahead and use this ICNS file:
[MacDown Neue.icns.zip](https://github.com/MacDownApp/macdown/files/5668573/MacDown.Neue.icns.zip)

**Comment by alexkaessner** [comment]
Merged with #1221 👏
