### ISSUE TITLE
Cannot send a request to join translation team

### ISSUE THREAD

**Issue by bitigchi** [MacDownApp/macdown#1237]
Hello,

I am trying to send a request to join the Turkish translation team on Transifex, but for some reason the language is not listed on the drop-down menu, although it is partially translated already.

See screenshot below:

![Снимок экрана 2021-03-02 в 01 28 10](https://user-images.githubusercontent.com/2769571/109567648-c0caed00-7af6-11eb-9d9f-514b39cec9ac.png)

**Comment by DesantBucie** [comment]
@bitigchi You have probably already sent request for Turkish, that's why you don't see it. It's the same with me. We need to be accepted by someone who manages project

**Comment by bitigchi** [comment]
Ah, makes sense I guess. Let's ping @FranklinYu then.

**Comment by DesantBucie** [comment]
Any update?

**Comment by FranklinYu** [comment]
Hi, both are approved. Look forward to the contribution!
