### ISSUE TITLE
Unable to install the command line option

### ISSUE THREAD

**Issue by arpa42** [MacDownApp/macdown#1309]
Hi, 

I can't install the command line tool. Here is more information:

### Infos:
macdown version: Version 0.7.3 (1008.4)
os: macOS 12.6

### Procedure: 
Go to settings > terminal and I click on "install"

### Expected result:
Something is happening

### Actual result: 
Nothing happens

Hope my issue is complete and someone can help

**Comment by bucanero** [comment]
I was having the same issue, so I did a manual fix, creating a link to the `macdown` CLI:

```sh
ln -s /Applications/MacDown.app/Contents/SharedSupport/bin/macdown /opt/homebrew/bin
```

(This works if you have `brew` on Apple M1, but you can create the link in any other folder)

**Comment by arpa42** [comment]
I should have considered it. Thanks for the tip. Too bad it doesn't work directly in the application.

As this fix works, I close the issue.
