### ISSUE TITLE
TOC is gone in 0.7.3?

### ISSUE THREAD

**Issue by patrickkidd** [MacDownApp/macdown#1312]
It looks like the [toc] is not rendering in 0.7.3 and there is no "Render TOC" in the view menu or preferences. Has it moved somewhere?

Thanks!

**Comment by pink-ink** [comment]
I use Version 0.7.3 (1008.4) and ther [TOC] renders.
I have a menu item "View -> Render Markdown", but no item about TOC.
In preferences in tab "General" there is a setting "[X] Detect table of contents token", which is selected.

**Comment by patrickkidd** [comment]
Interesting. Here is what I can see. Maybe did the `[toc]` token change?

![Screenshot 2022-11-03 at 4 47 57 PM](https://user-images.githubusercontent.com/1631833/199861640-71d79172-d358-4709-8233-9be68b46a734.png)

**Comment by pink-ink** [comment]
This is what I see:

![Bildschirmfoto 2022-11-04 um 01 14 14](https://user-images.githubusercontent.com/12589334/199864407-8c672ea8-5836-4147-a9ba-d52643aee4f0.png)

![Bildschirmfoto 2022-11-04 um 01 14 27](https://user-images.githubusercontent.com/12589334/199864413-1a791202-a88a-496a-9475-50eab547dfd2.png)

For me it works with either [toc] or [TOC].
Maybe reinstall it?

**Comment by patrickkidd** [comment]
Ah! Either the preference was cleared after some macOS upgrade or it was moved/renamed. In either case I didn't see it when I looked in the preference. This is all good then, thanks!
