### ISSUE TITLE
Problems with syntax highlighting and fenced code block syntax

### ISSUE THREAD

**Issue by diguage** [MacDownApp/macdown#158]
（我去了您的Facebook頁面，發現您是台灣人，由於英語不好，就用漢語提意見了。）

最近試用了一下您開發的“MacDown”。感覺不錯，尤其是對語法高亮的支持，比Mou改進好多。

不過，還是發現了一些問題。我在嵌入SQL語句時，使用語法如下：
```sql
select \* from tName
```
意外的是，這裏不能正常高亮。

另外，MacDown官網上features頁面上，關於語法高亮的圖片，使用的語法是
~~~python 
// Code
~~~
這和首頁圖片的語法不一致；另外，親測這種語法也不支持。（剛剛試了一下，Github支持）

冒昧提了好多問題。期待下次改進的更好！

D瓜哥 敬上

**Comment by matschaffer** [comment]
For what it's worth, I also ended up on this issue page looking for highlighting information.

Seems like it could be a good idea to add a note or screenshot to http://macdown.uranusjr.com/features/ if you're not interested in enabling (or can't enable) github-style syntax highlighting by default.

**Comment by matschaffer** [comment]
And thanks for the bi-lingual response. Really helped! :)

**Comment by tcloaa** [comment]
你好！Macdown很好用，

但是我按照你的方法开启了
![image](https://cloud.githubusercontent.com/assets/8750937/19739523/e796c846-9b80-11e6-85bc-565350576a71.png)

然后在代码部分：
![image](https://cloud.githubusercontent.com/assets/8750937/19739547/fcb84646-9b80-11e6-8029-60a99af0607d.png)

还是没有做到code block highlighted...请问该怎么解决这个问题？

谢谢！

**Comment by franklinyu** [comment]
Agree. It is unlikely for users not expecting syntax highlighting to get confused, and syntax highlighting doesn't seem to affect the performance. Even if it does (maybe for thousands of lines of code), I believe those extreme users will always find the preference page.
