### ISSUE TITLE
Bug: HTML comment and > char disable preview

### ISSUE THREAD

**Issue by OzzyCzech** [MacDownApp/macdown#188]
Hi,

there is a small bug with repatin > char - preview not generate when you have more closing characters.

```
<!--
author: Roman Ožana <ozana@omdesign.cz>
-->

whatever
```

![snimek obrazovky 2014-10-11 v 13 36 42](https://cloud.githubusercontent.com/assets/105520/4602462/1f17e648-513b-11e4-89e3-b547cd5b2b71.png)

**Comment by uranusjr** [comment]
Note: The fix has been merged into Hoedown, but does not make it into 3.0.1, so this problem still exists in MacDown. We can follow master instead of stable releases, but that might cause other problems. Still pondering. :disappointed:
