### ISSUE TITLE
PDF export cuts off content on page breaks

### ISSUE THREAD

**Issue by joshbeard** [MacDownApp/macdown#190]
This relates to https://github.com/uranusjr/macdown/issues/126 I think.

Exporting to PDF now has 0 margins, and the content gets "cut off".

Here's a couple of images examplifying this:

Notice in this one the graphic is split:

![Imgur](http://i.imgur.com/B3Mt18s.png)

---

![Imgur](http://i.imgur.com/yWsUhZk.png)

---

![Imgur](http://i.imgur.com/qRBxGI7.png)

As a hacky workaround to get the desired rendering, I currently export to HTML and use "Print -> As PDF" in a browser.

**Comment by wasade** [comment]
Hi @uranusjr, this does still seem to be an issue. I'm using 0.4.3. I did **Export -> PDF**

![screen shot 2015-03-02 at 4 21 59 pm](https://cloud.githubusercontent.com/assets/474290/6453288/ad8b46bc-c0f9-11e4-852e-51908aa009d0.png)
