### ISSUE TITLE
Feature: Equations?

### ISSUE THREAD

**Issue by mkiang** [MacDownApp/macdown#27]
Probably a long shot, but do you envision ever incorporating equations using LaTeX or MathML syntax (something similar to R Markdown: https://support.rstudio.com/hc/en-us/articles/200488468)? It might just be me, but nearly everything I write requires an equation.

**Comment by ggrrll** [comment]
@uranusjr  first of all, thanks for the nice app!

I am probably doing something wrong...but I still don't see how to render properly math

Thanks for help
<img width="1168" alt="screen shot 2017-11-20 at 14 57 15" src="https://user-images.githubusercontent.com/15370425/33021774-4dbdf17a-ce03-11e7-8dac-ad1740de1640.png">

**Comment by morningmorningwind** [comment]
The '$$' seems not supported by GitHub, which seems using \[ and \] instead? So it doesn't display when viewed on Github.

**Comment by franklinyu** [comment]
@morningmorningwind That is expected; GitHub never intends to support any math rendering. That has nothing to do with MacDown though.
