### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by JanX2** [MacDownApp/macdown#282]
What is your position on adding an optional toolbar?

This is the toolbar I redesigned a few years ago for Markdown Live:
![markdown live toolbar](https://cloud.githubusercontent.com/assets/192294/6189496/5bc53ae2-b39b-11e4-84e9-bcf41322da6d.png)

I could contribute those icons if there is any interest in a toolbar.

**Comment by uranusjr** [comment]
I like the clean UI maximising edit spaces we inherited from Mou, but I can see this being helpful to some users, too. So, as long as this is an opt-in (the toolbar can be hidden *and is hidden by default*), I’m fine with that.

**Comment by dpinol** [comment]
+1
very useful for beginners. http://www.texts.io/features/ has it

**Comment by Jmuccigr** [comment]
+1 here. Very Mac-like. Beats hitting the menus all the time.

**Comment by uranusjr** [comment]
This has been raised a few times now, both on Gitter and Twitter. I believe we should make this happen. @JanX2 are you still interested in making the icons?

**Comment by JanX2** [comment]
The least I can do is supply the ones I designed for MarkDownLive. Most of the buttons are just text buttons with custom fonts. Only the quotes, list icons, link and image icons are real icons. They are available as “Template”-suffixed PDFs that can be used directly.

**Comment by uranusjr** [comment]
Cool! I’ll build a toolbar with them first; we can always add new buttons later.

**Comment by JanX2** [comment]
BTW: Even though they are vector files, these icons are designed for the specific dimensions used. Scaling them by non-integral factors will likely cause them not to look as sharp.

**Comment by 19peaches** [comment]
+1 Awesome, thanks TP!

**Comment by dpinol** [comment]
hi, any news about this? :-)

thanks

**Comment by polarathene** [comment]
@uranusjr Any updates on this feature? 

I have some non-technical staff that I'd like to have edit markdown, but they might have a better time getting familiar with it if they can start off with a toolbar like this that can be toggled on or added as a plugin.

**Comment by ProjectInfinity** [comment]
Anything?

**Comment by niklasberglund** [comment]
Not sure about touch bar guidelines, but should the layout of buttons in the toolbar resemble the layout of buttons in the touch bar? #714

**Comment by niklasberglund** [comment]
I have started implemented this, but lacking icons. Would @alexkaessner be interested in modifying the touch bar icons you created to fit the needs of the toolbar? 😇
Or send me either high res or 64x64 versions of the touch bar icons then I could change the color and scale. Would need the same icons in dark gray/black color, sizes 32x32 and 64x64(retina).

Also missing icons for bold, italic, underline. Apple supplies those icons for the touch bar but they're to be used in the touch bar only... Can't use those for the toolbar and I haven't found any system icons that can be used.

**Comment by alexkaessner** [comment]
@niklasberglund Yeah it would make sense to also adopt the Touch Bar icons for the Toolbar! 😉
I can look into the and create the Toolbar versions out of them. Guess I will create PDF versions like the [HIG](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/ToolbarIcons.html#//apple_ref/doc/uid/20000957-CH89-SW1) suggests.

**Comment by niklasberglund** [comment]
@alexkaessner thank you! I guess you're right about the PDF files. I'm not totally clear on the difference between the kind of image under the sections _Create Template Images to Put Inside Toolbar Controls_ and  _Create Full Color Images to Use as Freestanding Toolbar Icons_. My interpretation is that the first one(PDF) is for images within toolbar buttons like in Safari's toolbar while the other one is for freestanding icons more like the playback controls in iTunes. Buttons with icons is what we want I guess.

**Comment by niklasberglund** [comment]
@alexkaessner the header-buttons are in a sub menu for the touch bar. For the toolbar the there's no hierarchy. So should there be three heading buttons for h1, h2, h3?

**Comment by alexkaessner** [comment]
@niklasberglund I was also thinking about this. We could go with a Dropdown Button, but thats not really faster. I would say a segmented control with H1 | H2 | H3 is better.
Isn't it possible to make them switchable? Like when e.g. H1 is active and you press it again that nothing is enabled and it switches back to paragraph.

**Comment by niklasberglund** [comment]
@alexkaessner ah right, segmented control would be really nice. The buttons work just the same as their equivalent menu options in the _Format_ menu.

Toggling between normal/header and other formatting options when pressing a second time sounds like a useful feature but I think that'd be better as a separate issue requesting this functionality. That would be application-wide and cover both menu, toolbar and touch bar I think.

**Comment by alexkaessner** [comment]
I've tried if the Headings Segmented Control looks better with the _normal_ style or the _NSSegmentStyleSeparated_ style. What do you think?

![macdown 2x](https://cloud.githubusercontent.com/assets/6615076/22620091/12876d76-eb04-11e6-812a-9c720effb6da.png)

Guess the normal style fits better here as there is no strict difference in the action like with shift left/right.

**Comment by niklasberglund** [comment]
Nice, it looks great! I like B I U grouped into one control and the others tightly together, but that's just my personal preference. Should unordered and ordered list also be in a segmented control with the _NSSegmentStyleSeparated_ style?

**Comment by alexkaessner** [comment]
@niklasberglund Okay, let's but both the Headings and the Lists in the _NSSegmentStyleSeparated_ style. I think this should work. 😉

Btw, should I create a new branch to push the Toolbar Icons later? For the Touch Bar we've also created a new `touchbar-support` branch…

**Comment by alexkaessner** [comment]
What about these icons? This may could be the default toolbar? Or what do you think should be visible there and in wich grouping/order?

![macdown 2x](https://cloud.githubusercontent.com/assets/6615076/22752332/68815962-ee38-11e6-8d21-94834bdef96b.png)

The rest of the buttons:
<img height="25" alt="strikethrough button" src="https://cloud.githubusercontent.com/assets/6615076/22752342/78a8c226-ee38-11e6-99cb-28d6008e2cbc.png"> <img height="25" alt="highlight button" src="https://cloud.githubusercontent.com/assets/6615076/22752345/798265bc-ee38-11e6-9248-f3441468a6ae.png"> <img height="25" alt="comment button" src="https://cloud.githubusercontent.com/assets/6615076/22752344/793c1c60-ee38-11e6-997d-dda518b8974c.png">

**Comment by polarathene** [comment]
That's looking really good, I'm a little sad this great app only works on macOS :(

**Comment by franklinyu** [comment]
@polarathene Did you mean Linux or Windows?

**Comment by polarathene** [comment]
@franklinyu Mostly Linux, I have Windows but I only run it via para-virtualized VM. I'm presently using QOwnNotes, a Qt app but it's more focused on Markdown notes than files/articles. I used MacDown at my last job where I had macOS and it was great.

Due to the codebase I wouldn't think MacDown could run on Linux or Windows any time soon?

**Comment by niklasberglund** [comment]
@alexkaessner looks great. Should the show/hide editor/preview pane buttons indicate the state by highlighting similar to how Xcode highlights it's buttons for showing/hiding panes?
![image](https://cloud.githubusercontent.com/assets/331986/22769886/d5482a56-eec6-11e6-9e87-da25c7ac6fa2.png)

I'm not sure about the workflow on the main repo, but I think either create a new branch there which I could pull the icons from or a (remote)branch in your own fork of the repo.

**Comment by uranusjr** [comment]
@polarathene This is a two-way thing. MacDown is both nice to develop and nice to use *because* we only support macOS; the current completeness could have never been achieved had this project been cross-platform. It’s no coincidence all of the best Markdown editors (iA, Byword, Mou, and MacDown) are Mac-only. :)

**Comment by alexkaessner** [comment]
@niklasberglund Yeah, would be nice to try it the Xcode way. Can you higlight them by code or do you need a colored asset?

I will create a new branch and upload it there. :+1:

**Comment by franklinyu** [comment]
@polarathene Also refer to #723.

**Comment by niklasberglund** [comment]
@alexkaessner I think tinting it by code is good. Let's try all monochrome, I'll implement it with color tinting for highlight and we see how it looks like?

**Comment by JanX2** [comment]
@alexkaessner If you name files so their base name ends in “Template” they should highlight correctly (SomeThing Something Template.pdf). Assuming you have the correct NSButton type selected in IB.

**Comment by alexkaessner** [comment]
@JanX2 Good hint! But don't you define the .xcasset as Template Image?

<img width="259" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6615076/22826014/7096bfd0-ef90-11e6-9cd7-3185636d464b.png">

**Comment by JanX2** [comment]
That’s new to me. Never tried that route. I knew that you could programmatically set an NSImage to be a template.

**Comment by alexkaessner** [comment]
I've created a `toolbar-support` branch out of the master and I also added the icons there. Keep us updated. 😉

**Comment by niklasberglund** [comment]
Right now it looks like this in the branch I'm working on:
![screen shot 2017-02-11 at 13 20 23](https://cloud.githubusercontent.com/assets/331986/22851480/af75d57e-f05d-11e6-86b2-bb740fc21581.png)

Example of larger window size:
![screen shot 2017-02-11 at 13 25 18](https://cloud.githubusercontent.com/assets/331986/22851481/bdbcd1b4-f05d-11e6-9145-0d636a7b9b25.png)

How about using fixed space instead of flexible? For everything except the toggle editor/preview buttons which should stick to the right.

**Comment by niklasberglund** [comment]
And add some space between indent, text formatting and headings right

**Comment by niklasberglund** [comment]
@alexkaessner is this highlight state for the pane buttons correct?

![Highlight states](https://cloud.githubusercontent.com/assets/331986/23054643/2c7f07f8-f51c-11e6-8731-7b1362255224.png)

**Comment by alexkaessner** [comment]
@niklasberglund Sorry for the late response.
I think flexible are still better than fixed. Most users won't have such a big screen and with fixed spaces it's harder to get it look right.

Why are the Buttons in you latest screenshot so small? They should be bigger like on the screenshot before. The Icons here are almost cut off.
And btw, the icons are still plain black and not that grayish system color right?

About the pane buttons…I think they should be gray in default mode. If you press the hide Editor Button this one should get highlighted and if you press hide Preview this one should get highlighted and only this one. That's at least what the icons are saying right now. A bit confusing if you ask me! 😅 But this way, the icons need to change.

**Comment by niklasberglund** [comment]
@alexkaessner no worries. The buttons in this last screenshot are small because I had activated the _Use Small Size_ customization option.
![image](https://cloud.githubusercontent.com/assets/331986/23150707/78d2943c-f830-11e6-9c53-cd2089e7b0de.png)

Right, the color should be more grayish. I've changed so that they now look like in below screenshot. The icon images are still the same.
![image](https://cloud.githubusercontent.com/assets/331986/23151831/acc21eae-f838-11e6-935b-55c2fd24ad83.png)

> About the pane buttons…I think they should be gray in default mode. If you press the hide Editor Button this one should get highlighted and if you press hide Preview this one should get highlighted and only this one.

Not so sure about the blue highlight in that case. I only know this blue highlight from Xcode where the buttons are highlighted indicating that a pane is visible.
![image](https://cloud.githubusercontent.com/assets/331986/23151079/3f3f36aa-f833-11e6-833f-eead09a33911.png)

Since the icons we have symbolize **hiding** editor/preview maybe they should be stateless. I was seeing them as buttons for **toggling** visiblity which is perhaps not correct.

**Comment by alexkaessner** [comment]
@niklasberglund Ah okay, but is it possible to scale the icons down in small mode. Sure it will make them blurry, but better than keeping them in normal size and almost clip them. This looks more odd. 😉 

Nice, the system grey fits better!
Are the shift left/right buttons clipped by 1-2px on the right side or does it just look so on non-retina?

> Not so sure about the blue highlight in that case.
Yeah me too! As @franklinyu mentioned in #754 I would be fine with both ways.
If we want to use the Xcode highlight way I need to change the icons! The problem would be still, that you can only hide one of them. You can't hide the editor AND the preview.

**Comment by franklinyu** [comment]
My rationale is that: both approach is doable and we can do them bug-free, but the mutually exclusive button may convey the "one of three" idea better? For example, [the "radio" in HTML](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_radio) conveys the "one of three" idea very well, and I wish there is something we can do to achieve the same.

**Comment by alexkaessner** [comment]
So maybe something like this?

<img height="25" alt="button" src="https://cloud.githubusercontent.com/assets/6615076/23162622/3fc0ed48-f82f-11e6-92f3-1bdd9f0cdb58.png">

**Comment by uranusjr** [comment]
> Is it possible to scale the icons down in small mode.

Don’t think so; there doesn’t seem to be a way to detect toolbar button sizes. Common practice is too make the icon smaller (leaver more padding in the default mode) so it still has paddings inside a small button.

I think we need to rethink the segment control. The blue doesn’t really fit. Maybe we can make the logic tri-state, and push down one of the three segments to indicate the current state.

**Comment by niklasberglund** [comment]
I agree, pushed down item in segmented control would make it clear that it's tri-state with one selected at a time.

**Comment by niklasberglund** [comment]
@alexkaessner looks great. Will toggling pane visibility be confusing for users who have flipped the position of editor and preview though? Or will they still get it?

**Comment by franklinyu** [comment]
> Will toggling pane visibility be confusing for users who have flipped the position of editor and preview though? Or will they still get it?

Good catch!

**Comment by alexkaessner** [comment]
@niklasberglund Ah shit didn't know users can flip the positions. 😅 If you want I can provide flipped editions of the icons so you can change them dynamically based on the user setting.

**Comment by alexkaessner** [comment]
@niklasberglund Hmm thats maybe better, but harder to communicate trough the icon.

<img height="25" alt="button" src="https://cloud.githubusercontent.com/assets/6615076/23165372/1835e8ca-f83c-11e6-939f-f3ecf139fc60.png">
This for example is way less understandable…or?

**Comment by franklinyu** [comment]
How about using the [original icons](#issuecomment-281314364), but flip it in runtime with Objective-C like [this](http://stackoverflow.com/questions/5404706/how-to-flip-uiimage-horizontally)?

**Comment by uranusjr** [comment]
> How about using the original icons, but flip it in runtime with Objective-C like this?

Also need to remember to flip their position in the segmented control.

**Comment by niklasberglund** [comment]
True, without preview and editor graphics the icons are much less descriptive. Mirroring and moving them sounds good to me.

**Comment by alexkaessner** [comment]
How is the status? Do you still need resources?

**Comment by niklasberglund** [comment]
Was making good progress with this, it's almost done. But then got busy and haven't had time to finish it. Afraid it might take 1-3 weeks before I find time to finish it up. I got a bit stuck on changing the highlight appearance from the blue highlight to pushed down highlight appearance.

Let me know if anyone's interested in having a go at fixing the highlight appearance. Otherwise I'll fix it when I find some time.

Should have all the resources, thanks!

**Comment by dw808303** [comment]
I love the addition of the toolbar. I do have one request, however.  The toolbar as implemented in `0.7.2d49 (919)` has quite a bit of whitespace between the tool buttons. As a result, I find myself needing to make the editor/preview window very wide to accommodate them.   Would it be possible to tweak the intra-button padding a bit?

**Comment by niklasberglund** [comment]
@dw808303 glad you like it 😊 You can right click the toolbar and select _Customize toolbar_ to customize the spacing. Might also want to remove toolbar items you seldom use.

![image](https://user-images.githubusercontent.com/331986/30337620-64e7e9c8-981b-11e7-973d-db73d05e272d.png)

**Comment by alexkaessner** [comment]
Hey guys,
as the toolbar seems to be finished I wanted to point out some final thoughts before releasing it to the master branch. Would be bad if we stop here! 😉 

1. The naming of the buttons is quite unpleasing. I would suggest to name combined buttons like the headings buttons only with one label. E.g. "headings" describes the buttons enough, we don't need to split this in "heading 1", "heading 2" & "heading 3". Currently the labels are clipped anyway and this won't improve with translations. Speaking of them, they're not translated yet. Can't we use the translations from the menu? And I would also add the labels to the customize sheet.
2. Currently there're still the default buttons for font/colors/print. Do we need them? If yes, I could create a smaller icon to fit them in a button like the others.
3. With `Version 0.7.2d49 (919)` the button to switch the layout mode is combined in one. If we want to use this I would change the button icon (either to the static "normal" state icon or dynamically with the selected layout) and maybe add some icons to the dropdown menu. And what's the reason why we don't use the Xcode style?
4. Relating to the layout button but also in general maybe we can add more buttons to split the combined ones? This leads to more options for power users. For this approach **but also in general I would recommend a good default toolbar layout** (see my recommendation on my draft)
5. Thats another point. Currently there's a lot of strange spacing going on there. I would recommend to only use flexible spacing!
6. Last but not least I would reduce all of the button widths a little bit to make more room for smaller windows. Currently there are around 41pt wide. I would suggest a width of 37pt. Also the height of the "icon only" view is quite high (see image). I would tweak this as well.

![toolbar comparison](https://user-images.githubusercontent.com/6615076/33340739-3cdfd9ba-d47d-11e7-97e2-52f8dd6f0fd6.jpg)

I've combined all of these points in a draft here. This is my UI designer point of view. What do you think about all of this?
Btw. I would help to tweak these details, but I can't find the source to this. The `toolbar-support` isn't used for this…

My draft:
![macdown 2x](https://user-images.githubusercontent.com/6615076/33340786-5f262ca4-d47d-11e7-8251-b4bae0590111.png)

My suggestion for naming:
- <img height="24" alt="shift" src="https://user-images.githubusercontent.com/6615076/33341049-fc3eff8e-d47d-11e7-859d-59fb3dca326a.png"> Shift Left/Right
- <img height="24" alt="text styles" src="https://user-images.githubusercontent.com/6615076/33340910-a18e8294-d47d-11e7-9db0-58ebfd4f72a1.png"> Text Styles
- <img height="24" alt="list" src="https://user-images.githubusercontent.com/6615076/33340911-a1d9092c-d47d-11e7-8f86-01d0775eee57.png"> Ordered/Unordered List
- <img height="24" alt="text styles" src="https://user-images.githubusercontent.com/6615076/33340913-a219de66-d47d-11e7-8cf3-c492743e44a1.png"> Headings

Alternative Layout Dropdown:
<img height="87" alt="layout dropdown" src="https://user-images.githubusercontent.com/6615076/33341413-3c8fbe06-d47f-11e7-9ce5-79757c5ce6a0.png">

**Comment by franklinyu** [comment]
Just to confirm, the thing that comes with v0.7.2d49 is actually *toolbar* support (the icon list within the window, which is displayed on screen), instead of [*touchbar* support](https://support.apple.com/en-us/HT207055), right? (Terms are getting confusing...)

**Comment by alexkaessner** [comment]
@franklinyu Yep, that's right. The current version (0.7.2d49) brings **toolbar** support. The touchbar support is still "hidden" with the [`touchbar-support`](https://github.com/MacDownApp/macdown/tree/touchbar-support) branch.

**Comment by franklinyu** [comment]
@alexkaessner I assume that the [`toolbar-support`](https://github.com/MacDownApp/macdown/commits/toolbar-support) branch can be safely deleted then?

**Comment by alexkaessner** [comment]
@franklinyu As [suggested before](https://github.com/MacDownApp/macdown/issues/282#issuecomment-347646435) I would do some final touches on the toolbar before releasing and closing this issue! I would actively help, but I can't access @niklasberglund's code. Or is there a way to do this?

**Comment by franklinyu** [comment]
I got it. So this issue remains open, but that branch is done (since it's been merged), right? If there is anything further, I assume that would be another pull request, such as `toolbar-improve`.

**Comment by alexkaessner** [comment]
@franklinyu Yes, you can close the `toolbar-support` branch. :wink:
Now I also got it! I will create a new pull request, to improve it. Everything toolbar related is already merged in the `master` right?

**Comment by franklinyu** [comment]
Yes! And that new pull request would close this issue (hopefully). 😆

**Comment by alexkaessner** [comment]
@franklinyu I've finally created a pull request (#901) with most of the suggested.

I couldn't manage to set enabled/disabled of the underline/strikethrough/… buttons based on the app settings. Maybe we can create a new issue for this to close this 😅

**Comment by uranusjr** [comment]
I’m closing this because the thread is getting too difficult to follow. We have a toolbar now.
