### ISSUE TITLE
Smarter Quotes

### ISSUE THREAD

**Issue by Topher-the-Geek** [MacDownApp/macdown#318]
There's a few places smart quotes shouldn't be active. Or even better, smart quotes should convert from fancy quotes to basic quotes.

Inside html tags. I write

```
<a name="#tag"></a>
```

and smart quotes breaks it.

In links. I write

```
This is [an example](http://example.com/ "Title") inline link.
```

or

```
[id]: http://example.com/  "Title"
```

and smart quotes breaks that too.

**Comment by uranusjr** [comment]
AFAIK all your examples work correctly in MacDown. Can you provide a full document that I can use to reproduce this?

**Comment by Topher-the-Geek** [comment]
They worked? Really? This happens in every document; there's no special one. I'm using version 0.4.4.1. To reproduce:  Turn on smart quotes (Edit -> Substitutions -> Smart Quotes), open a new document, type:

    This is [an example](http://example.com/ "Title") inline link.

Type that, don't cut-n-paste.  Watch MacDown change the straight quotes to fancy quotes. Try the link in the preview window. Notice that it takes you to "http://www.example.com%20“Title”". The space and fancy quotes show up as part of the link, rather than as the <a> tag's title attribute.

**Comment by franklinyu** [comment]
@Topher-the-Geek Does this still hold in latest MacDown? I can't reproduce it now.

**Comment by Topher-the-Geek** [comment]
I don't know. I haven't used MacDown in about a year. Sorry.

**Comment by uranusjr** [comment]
Reading this again I think this has something to do with macOS’s [text substitution](http://www.iclarified.com/38772/how-to-disable-curly-quotes-in-mac-os-x-mavericks) feature. This used to cause some problems in MacDown, so I [disabled it](https://github.com/MacDownApp/macdown/blob/master/MacDown/Code/Document/MPDocument.m#L52) some time ago. This should probably be closed.
