### ISSUE TITLE
Plugin system? Syntax modifications?

### ISSUE THREAD

**Issue by SimplGy** [MacDownApp/macdown#356]
Feel free to close without comment--wondering if some kind of plugin system is in the roadmap.

I'd like to extend the editor window to highlight:

```
o an unfinished todo item
. an in-progress item
x a completed item
```

I can do this in TextMate and sublime with their bundles/plugin systems. How architecturally difficult would it be to add a layer of user-defined syntax parsing? Maybe something that runs after [peg-markdown-highlight](http://hasseg.org/peg-markdown-highlight/), or maybe this is the wrong approach?

**Comment by SimplGy** [comment]
Side note: I understand Github's `- [ ]` todo syntax is already supported, don't want to get hung up on the specific syntax feature.

**Comment by FranklinYu** [comment]
Just so you know, we now have a plug-in system. It’s not documented, but you can see https://github.com/MacDownApp/macdown-gistit for an example.

**Comment by SimplGy** [comment]
Oh cool, good to know! looks like it's existed for three years :)

Don't have time to play around with it these days, but maybe someday.
