### ISSUE TITLE
Add export to evernote and wordpress site feature

### ISSUE THREAD

**Issue by fushcpc** [MacDownApp/macdown#375]
Thanks for your great APP, but it will be greater and bring more users to your APP if you add the export to evernote and wordpress site.

**Comment by Fastidious** [comment]
Wow. Don't forget Movable Type, and OneNote and [insert whatever comes to mind here]. :-D

**Comment by nhoizey** [comment]
:+1: for Wordpress !

**Comment by grahamannett** [comment]
Hey, started using macdown and it's so great, was looking at adding some evernote functionality similar to (hopefully) what SublimeEvernote or Marxico, has anyone tried this with or without success?  Looking at https://github.com/bordaigorl/sublime-evernote I think I should be able to add the 'basics' but wanted to check here first

**Comment by robinkeunen** [comment]
:+1: for evernote!

**Comment by uranusjr** [comment]
I don’t want to tie MacDown to specific external services. (Well, especially to those I don’t use at all.) There is a [simple plugin structure](https://github.com/MacDownApp/macdown-gistit#the-macdown-plug-in-architecture) that might work in this case though. Feel free to roll your own.
