### ISSUE TITLE
scroll don't sync?

### ISSUE THREAD

**Issue by yuanji-dev** [MacDownApp/macdown#4]
scroll the source file part(left) the preview part(right) will scroll.
but scroll the preview part the source file part dont move.

**Comment by madranet** [comment]
@uranusjr: _The bottom line is, I don’t really see the point of syncing the editor when the preview scrolls..._

I do. 

When I've written a longish piece and am proof-reading it, I'll proof-read it in the preview window. Then, if I spot a typo or other error, I'll want to jump back to the edit window to fix it. If sync'd scrolling worked in both directions, this would be easy. As it is, I have to hunt through the edit window to find the offending markdown for correcting.

**Comment by FelixOutta** [comment]
still looking for this in 2021 ;) It would be nice if one could at least click "jump to preview position" in editor. I use markdown for summaries on studies and it is really awful to scroll through large summaries or find a certain position where I would like to continue working on.

**Comment by ychoi** [comment]
> still looking for this in 2021 ;) It would be nice if one could at least click "jump to preview position" in editor. I use markdown for summaries on studies and it is really awful to scroll through large summaries or find a certain position where I would like to continue working on.

Same here.

**Comment by cskeeters** [comment]
I just checked out [Dillinger](http://dillinger.io/), and when you activate the *Scroll Sync* in settings, it syncs the preview when you scroll the source **and** the source when you scroll the preview.
