### ISSUE TITLE
<kbd>text</kbd> formatting

### ISSUE THREAD

**Issue by NickVolynkin** [MacDownApp/macdown#404]
I use the <kbd>some button text</kbd> formatting a lot. It would be nice to have a formatting option for this, like the *italic*, **bold**, `code` and others.

**Comment by uranusjr** [comment]
The formatting is just some lines of CSS—I can add that. But a hotkey… I don’t know, it’s easy to accept one, probably a couple more, but it just doesn’t feel right.

Maybe it would be better if users can add customised hotkeys to suit their specific needs. I’ll think about this.

**Comment by NickVolynkin** [comment]
Yes, customized hotkeys would be just perfect. Thank you for a quick reply. Subscribed to the new issue too.

**Comment by uranusjr** [comment]
Come to think of it, it might be better to handle this with an external text expander. Something like [Typinator](http://www.ergonis.com/products/typinator/). It might feel like an overkill to spend €25 for something like this though.
