### ISSUE TITLE
Tex string formating hang when being splited

### ISSUE THREAD

**Issue by galaxy001** [MacDownApp/macdown#488]
Reproduce:
- Type `with probabilities \\((1 - p_l)^2, 2p_l(1 - p_l), or p_l^2\\), respectively.` and Enter.
- Try to edit the string to `with probabilities \\((1 - p_l)^2, 2p_l(1 - p_l)\\), or \\(p_l^2\\), respectively.`
- MacDown will hang when the first new `\\)` is inserted.

**Comment by franklinyu** [comment]
This bug seems to have disappeared in the latest version, did it?

**Comment by uranusjr** [comment]
Could be if this is related to a7f63ffdc. It was intended for a different syntax crash, but I wouldn’t be surprised if they are related. @galaxy001 can you confirm whether this is fixed?

**Comment by galaxy001** [comment]
It is fixed in `Version 0.6.4 (786)`.

**Comment by franklinyu** [comment]
Great. Please comment if it occurs again in the future.
