### ISSUE TITLE
Macdown not remembering theme setting on 10.11 El Capitan

### ISSUE THREAD

**Issue by benseven** [MacDownApp/macdown#501]
# Description:
Macdown won't retain my selected theme for new windows or opening documents.

# Steps to reproduce:
- Download Macdown (I installed via Brew Cask)
- Symlink a theme in from another location:
```
ln -s /Volumes/Macintosh\ HD/Users/seven/Dropbox/Sync/System/Themes\ and\ Styles/macdown.style
/Users/seven/Library/Application\ Support/MacDown/Themes/macdown.style
```
- Switch to theme with no documents open
- Open new document; theme will be in use
- Close window, open new document, old theme is there 

# Additional Info
- Originally I was just modifying one of the themes in situ, rather than symlinked. This still happened. I symlinked to preserve my theme (modified Tomorrow+) between uninstalling and reinstalling Macdown to try and fix this issue
- I don't believe the issue is the theme itself as it is a duplicate of an existing theme with colours and type sizes adjusted only.

**Comment by Jmuccigr** [comment]
I don't see this on Mavericks with MacDown 0.5.3.

There are various problems with theme handling though. See, for example, #333 (which isn't categorized yet). For example, MD doesn't seem to be able to follow an OS X alias, so you have to symlink instead.

**Comment by benseven** [comment]
I'm on El Capitan (10.11) with MacDown 0.5.3.

As mentioned, my custom theme is a symlink, but I have the same issue regardless of whether I was editing an existing theme or symlinking my own.

**Comment by wenbert-fishpond** [comment]
I experienced this problem yesterday. Quite annoying. Uninstalled and removed all related files for Macdown. Reinstalled. Copy-pasted "Tomorrow+" theme file. Renamed it. And then new custom theme now works as expected.

The buggy behaviour was that it just kept reseting to the "blank" theme option in the Preferences.

**Comment by wenbert** [comment]
I experienced this problem yesterday. Quite annoying. Uninstalled and removed all related files for Macdown. Reinstalled. Copy-pasted "Tomorrow+" theme file. Renamed it. And then new custom theme now works as expected.

The buggy behaviour was that it just kept reseting to the "blank" theme option in the Preferences.

**Comment by Jmuccigr** [comment]
I wonder if your pref file is corrupt. Try renaming it while MD is closed and then open it up and see what happens.

**Comment by wenbert** [comment]
If I remember correctly (not 100%), I also did that (Copied-renamed the file while MD was closed). I can no longer replicate it because it is working now after I did a clean reinstall. Thanks!

**Comment by benseven** [comment]
Thanks @Jmuccigr - can you advise on the pref file location?

**Comment by Jmuccigr** [comment]
Should be one of these two:

~/Library/Preferences/com.uranusjr.macdown.LSSharedFileList.plist
~/Library/Preferences/com.uranusjr.macdown.plist

**Comment by benseven** [comment]
— Removed preference file
— Copied (instead of symlinked) custom theme to Themes folder
— Opened Macdown and selected custom theme in preferences.
— CMD-N for new file; uses custom theme. Close window.
— CMD-N for another new file; uses blank non-theme (i.e. presentation does not match any of the existing themes).

So:
— Nuked preference file
— Nuked Application Support folder
— Ran `brew cask uninstall macdown`
— Did a system search for 'Macdown' and 'uranusjr' - no files left on system.
— Ran 'brew cask install macdown'
— Opened Macdown, preferences window, clicked reveal, copied custom theme across (again, custom theme is only text size and colour changes)
— Closed preferences window. Reopened preferences window. Selected custom theme.
— Cmd-N for new file has custom theme. Close window.
— Cmd-N for another new file uses random light non-theme again.
— _Let out garbled scream_.

**Comment by uranusjr** [comment]
This is… strange. And puzzling. I wish I could get my hands on your Mac to debug this directly.

Could you provide a copy of the `plist` files ([mentioned in the above comment](https://github.com/MacDownApp/macdown/issues/501#issuecomment-157740443)) so I can take a look inside?

**Comment by benseven** [comment]
Sorry, I got too frustrated and ditched the app. I wish you all the best with the continued development of the project though!

**Comment by uranusjr** [comment]
I understand that, sorry. :( I’ll close this for now then (because no-one seems to have the same problem).

To anyone seeing this in the future: Feel free to re-open and send me a copy of your plist files.
