### ISSUE TITLE
“MacDown” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by stanislaw** [MacDownApp/macdown#515]
Hello,

First of all thank you for this amazing project.

My suggestion is that you could codesign your project with your developer certificate because currently with the latest `Version 0.5.3 (697)` I have this warning:

> “MacDown” can’t be opened because it is from an unidentified developer.

> Your security preferences allow installation of only apps from the Mac App Store and identified developers.

Of course I can manage it by opening Security settings but still if you enable code-signing your MacDown app will become trusted.

That's the good style of distribution and is very easy to do. So I encourage you to do that.

Thanks again.

**Comment by Jmuccigr** [comment]
Just use the menu item "Open" on it (cmd-O) directly or right-click and "Open" instead of a double-click. Then the system will allow you to choose "Open" from the subsequent dialog box.

**Comment by massenz** [comment]
@Jmuccigr : no, the only way to enable it running is via the System Security dialog, which also will require unlocking and choosing an (extremely) unsafe option.

Those more technically-inclined among us, will do so, authorize MacDown and then disable it back, but you run the risk of (a) leaving out those who wouldn't know how (or want) to do this or (worse) (b) have them be left with an insecure system.

The "authorization" you refer to is an ulterior dialog that is relative to opening an app downloaded from the Web (as opposed to installed from the AppStore).

I would second @stanislaw suggestion to just codesign the project.

**Comment by Jmuccigr** [comment]
I have MacDown running without ever doing the procedure you describe: "authorize MacDown and then disable it back" (which I will admit to not quite understanding).

In the System pref "Security & Privacy", I have the "Allow apps downloaded from" set to the "Mac App store and identified developers". When I need to open an app (which includes updated versions of apps I already have, like Chrome), I need to follow the procedure that I outlined above. I don't have to change any settings in the preferences.

I believe this is a fairly secure method, since nothing that comes from outside the App store can run without my permission.

Perhaps I am missing something,

**Comment by uranusjr** [comment]
Well, either way, if clicking through the privacy settings feels insecure and bothering, please be so kind and send me $99 a year to pay for Apple’s “protection”.

**Comment by steakknife** [comment]
@uranusjr Just gpg sign release tar/zipballs, commits and tags... good enough.

**Comment by uranusjr** [comment]
@steakknife I don’t think this solves this particular issue.

**Comment by steakknife** [comment]
@uranusjr The standard fix: Ctrl-click and open adds an unsigned app to the
gatekeeper whitelist. This is the standard work-around for unsigned apps.
It won't ask again. However, it only makes sense to open apps downloaded
from a trusted source.

Gpg signatures would allow the verification of integrity and offer
non-repudiation before extracting a .app zip/tar. Many unsigned apps do
this, either with .dmgs or .zip-balls. IIRC torbrowser does this.

The other options are for people to build the code themselves to
self-codesign, raise funds every year for a developer account or have
someone with a developer account build releases and codesign (not sure if
that's totally okay, but as long as they're part of the project it should
be fine).

**Comment by franklinyu** [comment]
@steakknife What @stanislaw want is simply to get rid of the annoying dialog box. I don't think he is worrying about the integrity of the downloaded binary, since most people get MacDown from a trusted source ([GitHub release page](https://github.com/MacDownApp/macdown/releases)).

**Comment by steakknife** [comment]
@uranusjr Apply the standard fix, Christ!

[How to open an app from a unidentified developer and exempt it from Gatekeeper](https://support.apple.com/en-us/HT202491)

**Comment by franklinyu** [comment]
@steakknife How specifically is the live preview broken?

**Comment by massenz** [comment]
FWIW MacDown's preview works just fine and is beautiful to look at - Atom plugin is the one "totally broken:" I tried it, and it slows down to an unusable crawl soon as you have more than a handful of code snippets (filed an issue there, and the answer was a pretty unfriendly "won't fix").

@uranusjr I don't really think you need to fork out the $99 "Apple protection" fee to sign the app, but I can't be positive: I really wish I could help here, but just don't know enough about this to be useful. Sorry.

**Comment by jinsonkv** [comment]
Hi, The warning is due to Apple's Gatekeeper feature, which prevent all apps outside Apple Store. 
You can check this website to find a working solution.
[](https://techiestechguide.com/app-cant-be-opened-because-it-is-from-an-unidentified-developer/)

**Comment by franklinyu** [comment]
@jinsonkv Are you talking to the maintainers or OP? OP already knows this, and this issue has been closed for almost two years.
