### ISSUE TITLE
program crashing when typing colon in alternative reference style 

### ISSUE THREAD

**Issue by jcgu** [MacDownApp/macdown#532]
New user here and first issue reported on GitHub!

I'm using MacDown Version 0.5.3 (697).

I tried to follow the alternative reference style mentioned in the help.md:

```
[like this]: http://macdown.uranusjr.com  
```

When I tried it using a real-world example like the one below, the program crashed. 

```
[A Quick Guide to Organizing Computational Biology Projects
]: http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424
```

Initially, I had this following text I want to modify on:

```
[A Quick Guide to Organizing Computational Biology Projects
](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424)
```

I would delete the parentheses, which was fine. But it crashed at the moment when I typed ":". I tried it many times, and it crashed each time at that point.

**Comment by jcgu113** [comment]
I realized that I should have put the second square bracket on the same line as the first. When I move it to the same line as the first square bracket, the reference looks good. I think "]: url" on a line itself with an unclosed square bracket "[ some text" on the previous line is causing the crash. Like this:

```
[ some text
]: http://xxxx
```
