### ISSUE TITLE
Line breaks in help.md

### ISSUE THREAD

**Issue by mitselek** [MacDownApp/macdown#548]
You have issue with line breaking here
https://github.com/uranusjr/macdown/blame/master/MacDown/Resources/help.md#L30-L37
---
### Line Breaks

To force a line break, put two spaces and a newline (return) at the end of the line.

```
These lines
won't break

These lines  
will break
```

**Comment by mitselek** [comment]
This is not trivial issue to fix.
Problem is, that for non-coding ppl this looks confusing as they see in the preview two identical outputs.
Maybe something like this:

	These lines
	won't break

These lines
won't break

	These lines  
	will break

These lines  
will break

---
Duh. They are breaking a lot here, but You get the idea :)

**Comment by uranusjr** [comment]
Hmm. You’re right, this is confusing. And maybe I should put in some custom styles to somehow make the spaces visible. Thanks for raising this.
