### ISSUE TITLE
Copy selection as HTML

### ISSUE THREAD

**Issue by jerriep** [MacDownApp/macdown#549]
I have noticed that MacDown has a feature which allows you to copy the document to the clipboard as HTML. I am however looking for a feature which copies only the selected text as HTML.

Will it be possible to add such a feature?

**Comment by uranusjr** [comment]
I do intend to add it in the future, but currently it’s not possible.

A cruel workaround is to enable WebKit debugging for MacDown

~~~bash
defaults write com.uranusjr.macdown WebKitDeveloperExtras 1
~~~

Right click in the preview pane → Inspect Element, and copy what you want from the Resources tab.

**Comment by Jmuccigr** [comment]
Well, crude, maybe, but not so cruel. :-)

**Comment by jerriep** [comment]
No worries. I work around it for now by pasting the entire document as HTML, and then copying and pasting from there.

**Comment by Karlheinzniebuhr** [comment]
+1
