### ISSUE TITLE
Xcode Like Code Folding

### ISSUE THREAD

**Issue by Big-Pi** [MacDownApp/macdown#553]
When i'm writting longer MarkDown, I want to fold part of the text , hope this feature will be added ;

**Comment by lucasderraugh** [comment]
What would the expected behavior be in this case. Just that it hides what you've written, or also hides the preview?

**Comment by Big-Pi** [comment]
Both ,so that i can : write some - fold it - then focus on other parts

**Comment by yoiang** [comment]
is this a duplicate of #500?

**Comment by franklinyu** [comment]
@yoiang Great, thank you! I assume that this is a duplicate of #500. Closing this until @Big-Pi tells otherwise.
