### ISSUE TITLE
Select file name only when saving

### ISSUE THREAD

**Issue by JohJakob** [MacDownApp/macdown#585]
> The save dialog now always appends .md automatically when saving an untitled file. You can still change the extension if you want.

When saving an untitled file, the .md extension is appended automatically, but is selected in the text field. In other apps, only the file name and not the extension is selected. If the user is not careful, he/she saves the file without an extension. Also, the checkbox "Hide extension" in the save dialog is useless at the moment.

**Comment by Jmuccigr** [comment]
Good catch. I agree about selecting only the name *without* the extension.

**Comment by Jmuccigr** [comment]
Thoughts on this? Seems likely to be easy to fix.

**Comment by niklasberglund** [comment]
Had a look at this. Can be resolved by specifying `allowedFileTypes` of `NSSavePanel`. Currently set to nil.
Should it be set? Then only those file extensions would be allowed. These extensions should probably be pulled from _MacDown-Info.plist_.

**Comment by uranusjr** [comment]
Problem is custom extensions is also a valid usage I want to support. I use MacDown to edit [Lektor](https://www.getlektor.com) content files, and there are tons of Markdown files with `.txt` or even more exotic extensions out there.

**Comment by niklasberglund** [comment]
Ah yes. I find it odd that the behaviour of the selection is different just because of this. I haven't found any other way to make it select name only and not extension. But wouldn't be surprised if there's some way to do it that I haven't found.

**Comment by Jmuccigr** [comment]
I have no clue how it works, but I just tested with BBEdit and there the save dialog has only the filename selected, with `txt` as the default extension (which it's possible to change). It doesn't seem to care what extension you actually type in. I tried .doc and .asdf (the former real, the latter not, as far as I know).

So there's got to be a way!

**Comment by niklasberglund** [comment]
@Jmuccigr great. That's very useful to know. Actually had another look at it now and found how to do it 👍
