### ISSUE TITLE
[TOC] tag desupported in v0.6 (749)

### ISSUE THREAD

**Issue by gridmon** [MacDownApp/macdown#589]
I've been using the markdown extension [TOC] since for a year or two now  (an advantage that Macdown had over Mou).
However, you seem to have dropped it in this latest release.

Edit: Adding more detail...
The last release I know it was there for sure was 0.4.4.2d18 (642)
The View menu had a "Renders [TOC]" option that enabled the [TOC] tag to be interpreted into a UL composed of all Header 1..4 lines

**Comment by uranusjr** [comment]
The TOC option has been moved into Preferences in a previous release (couldn’t remember where). It seems that I didn’t code the backward compatibility correct to transfer the setting. You can turn it back on manually at **MacDown → Preferences → Rendering → Detect table of contents token**.

**Comment by gridmon** [comment]
That's brilliant Tzu-ping.
Cheers.
Andy

**Comment by alanhg** [comment]
here

![image](https://user-images.githubusercontent.com/9245110/80271304-b0d1c800-86f1-11ea-8daa-95d14266fc4f.png)
