### ISSUE TITLE
Wanted: word count selection

### ISSUE THREAD

**Issue by alexellis** [MacDownApp/macdown#590]
Word count for selection is really important in publishing - I have been using MarkDown to draft articles and I can't find a way of getting w/c for selection with MacDown.

I have not worked with Objective-C before, but I found this code in MPDocument.m

```
- (void)updateWordCount
{
    DOMNodeTextCount count = self.preview.mainFrame.DOMDocument.textCount;

    self.totalWords = count.words;
    self.totalCharacters = count.characters;
    self.totalCharactersNoSpaces = count.characterWithoutSpaces;

    if (self.isPreviewReady)
        self.wordCountWidget.enabled = YES;
}
```

Is DOMDocument a custom class or something which may support querying a selection's word-count?

Would you consider adding this feature? It is present in Atom which is what I was using previously.

**Comment by uranusjr** [comment]
As I’ve described briefly on GItter, MacDown’s word counter is implemented to ignore markup characters, and include only those in the rendered content. This is done by looking into the preview pane[1] and extract the content inside. The API it uses comes from the WebKit framework. Apple’s documentation on this is spotty, but it actually mirrors the standard JavaScript DOM interfaces. I usually refer to [MDN’s documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) on this.

The `DOMDocument` property on the web frame returns a `DOMDocument` instance, which is `Document` in JavaScript. MacDown then uses a category method `textCount` (in `DOMNode+Text.h`; `DOMDocument` is a subclass of it) to calculate character and word counts. The implementation is a bit complicated, but essentially it uses jQuery’s `$.text()` logic to extract the string, and then uses various ways to count it.

The good thing about this implementation is that, compared to simply counting things in the editor, the result is much more accurate. The down side, however, is that it cannot easily reflect real-time interaction in the editor. To implement this, MacDown will need to know what region in the preview pane corresponds to the selection in the editor, and count accordingly. While this is not impossible, it’s difficult to do efficiently, and requires a complete rewrite in the parser to carry much more information. It is something I would like to do if I have unlimited time, but for the time being I would like to focus on features that are more easy-picking (which is, like, most other features).

I’m closing this as a duplicate to #370.

[1]: This is also why the counter becomes unavailable if you hide the preview pane.
