### ISSUE TITLE
Sidebar and tabbed interface

### ISSUE THREAD

**Issue by trapias** [MacDownApp/macdown#603]
Feature request: what about adding...
- a sidebar to browse folders & files
- a tabbed interface, so to easily manage multiple open files 

I believe this would greatly improve usability. For example http://lightpaper.42squares.in has both 😄

**Comment by franklinyu** [comment]
For the tab interface, try macOS Sierra, as described in #617.

**Comment by kenbailey** [comment]
The tabbed interface #617 works great. Any chance we can have an option to open new windows via links in the Preview on the tab (rather than opening a separate window).  If this isn't desired default behavior, possibly extending the right click to "Open in tab...".

Great work on the app!

**Comment by franklinyu** [comment]
@kenbailey Interesting idea. That deserves a stand-alone issue!

**Comment by kenbailey** [comment]
I'll create a new issue for it then.

**Comment by franklinyu** [comment]
Closing this issue though. The tab part is duplicate of #631, so if anyone has any issue, please report at #631. The sidebar part is duplicate of #141.
