### ISSUE TITLE
Strikethrough using tilde not implemented

### ISSUE THREAD

**Issue by fazlearefin** [MacDownApp/macdown#604]
Using double tildes to ~~cross something out~~ has no effect in the editor. Please support the strikethrough tag.

![image](https://cloud.githubusercontent.com/assets/1625934/14821052/9831e9ec-0c0c-11e6-9ec1-cb910e059908.png)

**Comment by the0neyouseek** [comment]
![pref](https://cloud.githubusercontent.com/assets/4009175/15206169/7ce69fb2-181d-11e6-9606-55268eeffa73.jpg)

Go to Preferences &rarr; Markdown &rarr; enable Strikethrough in Inline formatting and it should work now 😉
