### ISSUE TITLE
Chinese symbol support like ＊＃

### ISSUE THREAD

**Issue by lyle-luan** [MacDownApp/macdown#605]
Switch language is such annoying.

**Comment by uranusjr** [comment]
No. This is too confusing. If we start supporting ＃(Fullwidth Number Sign), how about ﹟(Small Number Sign)? How about #️⃣(Keycap Number Sign) and #⃣(also called Keycap Number Sign but with a different Unicode code point for reasons I don’t understand)? This is a rabbit hole I’d rather not go into, and I’d like to think that Markdown specs have good reasons to not supporting them.

If you really believe this is a good idea, maybe you can start by [convincing CommonMark](http://talk.commonmark.org) to support alternative syntax tokens. They have a very good platform for discussing these kinds of topics, and if they support this idea, I would too.
