### ISSUE TITLE
Contents of .md files not visible when launching macdown from the command line

### ISSUE THREAD

**Issue by orlando21** [MacDownApp/macdown#612]
I installed macdown and then created the shortcut to launch it from the command line like so:
`ln -s /Applications/MacDown.app/Contents/SharedSupport/bin/macdown /usr/local/bin/macdown`

When I type for example `macdown file.md`, macdown launches and appears with the file open but the file is completely empty. As `file.md` is non-empty, I can view its contents by choosing File->Open from the macdown menu.

Since I'm a new user, I'm of course not sure if this has something to do with my configuration or if it's a bug. I'm on OSX Capitan version 10.11.5. I installed macdown version 0.6 (749). Thank you

**Comment by Jmuccigr** [comment]
Try just aliasing the standard OS X command in your .bash_profile, like this:

alias macdown='open -a MacDown.app'

**Comment by orlando21** [comment]
That works... thanks!

**Comment by orlando21** [comment]
I added `alias macdown='open -a Macdown.app` to my `.bash_profile` and it seemed to work at first (not sure anymore if that's what made iit work), but on subsequent days of restarting the mac I still get an empty MacDown file with `macdown file.md`.

I still can't figure out why empty macdown files still open instead of the contents of file.md. `.bash_profile` seems to have the correct alias command. Maybe it's something in my configuration?

**Comment by Jmuccigr** [comment]
I'm confused about exactly what you're doing. Can you post the steps?

**Comment by orlando21** [comment]
(Funny thing is, I modified the alias line in `.bash_profile` to `alias macdown='open -a /Applications/MacDown.app'`, quit macdown, reopened that file using `macdown` at the command line - same as before - and now MacDown opens with the file contents displayed.)

My step to use MacDown is probably what you expect:
1. Start my mac (just want to emphasize MacDown is not already running during the next steps).
2. Display Terminal.
3. cd to the subdirectory where `file.md` lives.
4. In Terminal, type `macdown file.md``
(A blank file opens.)

**Comment by orlando21** [comment]
Correction: `file.md` opens but it's blank!

**Comment by Jmuccigr** [comment]
This works fine for me. Are you sure you're getting the right file.md? Did you save the contents? If you open it up the usual way via MacDown, what happens?

**Comment by orlando21** [comment]
`file.md` is non-empty with saved contents.
I edited my comment directly above yours to say that:

- Typing `macdown file.md` displays a "blank" `file.md`
- I close that blank window.
- I return to Terminal and retype `macdown file.md`, which correctly displays `file.md` and its contents.

The above shows me it's the correct, non-empty file I'm opening.
Somehow the consequence of this strange error is that I have to type the command twice to correctly display files.

**Comment by Jmuccigr** [comment]
Works fine for me on Mavericks.

**Comment by adam12** [comment]
I can confirm the same, with similar pattern to @orlando21 - if Macdown is already running in the dock, the files open and render correctly. If Macdown has to launch first, plain and rendered panes are both empty.

OSX 10.11.5
MacDown: version 0.6 (build 749)

**Comment by Jmuccigr** [comment]
Using `alias macdown='open -a MacDown.app'` works fine for me, now in El Capitan, whether MacDown is running or not. I've got it installed via a download of the binary, not via home brew.

**Comment by uranusjr** [comment]
I just fixed this in 8e1fb45 and released 0.6.2 with this patch. Please give it a shot and tell me if things are working!

**Comment by franklinyu** [comment]
Note: 8e1fb45fc9e74b1c3b49f1da110241ce3e3aae66 works even in Homebrew version.
