### ISSUE TITLE
Show misspelled words

### ISSUE THREAD

**Issue by soarhevn** [MacDownApp/macdown#616]
Currently if a user right clicks on a misspelled word, expected functionality works. A suggestion (if available) is shown, and when chosen, replaces the misspelled word.

**However misspelled words are not shown in the editor.** This means the user must manually search for misspelled words or copy/paste to another editor that supports spell checking.

Please add in misspelled word highlighting.

**Comment by uranusjr** [comment]
Edit → Spelling and Grammar → Check Spelling While Typing.

**Comment by soarhevn** [comment]
Face palm. Sorry!

**Comment by UkiahSmith** [comment]
This tripped me up too. Maybe enabling it by default would improve the experience for new users.

**Comment by linmic** [comment]
@uranusjr enable it by default +1 *flee*
