### ISSUE TITLE
Tab support in macOS 10.12

### ISSUE THREAD

**Issue by stevemoser** [MacDownApp/macdown#617]
Supposedly it takes minimal work to support tabs in macOS 10.12.

**Comment by uranusjr** [comment]
I certainly hope so. Did anyone here actually get their hands on Sierra yet and try running MacDown on it?

**Comment by getaaron** [comment]
I haven't tried yet, but I think it happens automatically if you're using `NSDocument`

**Comment by abookyun** [comment]
@stevemoser @uranusjr Yes, it worked. Like a charm.

![screen shot 2016-07-20 at 00 08 18](https://cloud.githubusercontent.com/assets/2224554/16957221/19256e50-4e0e-11e6-88cc-7d647b799442.png)

![screen shot 2016-07-20 at 00 07 42](https://cloud.githubusercontent.com/assets/2224554/16957184/fe5199c8-4e0d-11e6-826e-630011f4a7f3.png)
