### ISSUE TITLE
QuickLook not working. 

### ISSUE THREAD

**Issue by civrot** [MacDownApp/macdown#618]
Quick look is not working. Is this future feature? I really like this app, but the fact that quick look is not working is making me rethink looking for another app.

**Comment by Jmuccigr** [comment]
Quicklook is a system thing. What exactly are you referring to?

**Comment by uranusjr** [comment]
It is possible for apps to include Quicklook plugins for specified document types. I think what OP wants is for MacDown to include a QL plugin for Markdown files.

And no, MacDown does not have one now. I look forward to any contribution if anyone is interested.

**Comment by Jmuccigr** [comment]
I use https://github.com/toland/qlmarkdown, installed via homebrew.

**Comment by georgexsh** [comment]
I guess OP wants QuickLook preview render as HTML? but I prefer it shows as plaintext, hope that will be simpler to implement.

**Comment by bennotkin** [comment]
My experience with MacDown is that it _prevents_ Quick Look from showing the plaintext, but doesn't show the html. I don't really care which I see, but would like to preview my text _somehow_
