### ISSUE TITLE
can i custom image url?

### ISSUE THREAD

**Issue by madordie** [MacDownApp/macdown#626]
in app, can you add a setting to set the URL prefix unified document Pictures do? Or tell me what this image's url reads?  thank you very much!

**Comment by madordie** [comment]
### Images
#### Inline
`![Alt Image Text](path/or/url/to.jpg "Optional Title")`
#### Reference style
`![Alt Image Text][image-id]`  
on it's own line elsewhere:  
`[image-id]: path/or/url/to.jpg "Optional Title"`

**Comment by franklinyu** [comment]
Doesn't it work now? At least it works for me.

**Comment by uranusjr** [comment]
Yes, both of the above already work. Closing.
