### ISSUE TITLE
auto reload the markdown file when other app edit it

### ISSUE THREAD

**Issue by jinleileiking** [MacDownApp/macdown#630]
when editing file, I like use vim.

when I have edited a file,  the macdown cannot reload the edited file automatically.

**Comment by Jmuccigr** [comment]
Same as #564.

**Comment by franklinyu** [comment]
#564 Have been in latest release, but according to the last two comments, this bug is not fully solved. The behavior seems to vary from machine to machine.

**Comment by ousui** [comment]
@franklinyu 
When I use vi to edit the same file, the content can't change in MacDown.

**Comment by timotheecour** [comment]
Likewise, not working on OSX; when editing file in sublimetext, change is not reflected in macdown

**Comment by uranusjr** [comment]
Should work in 0.7.2d126 (996).

**Comment by timotheecour** [comment]
@uranusjr  @Gidgidonihah  any way to publish the change so that 'check for updates' will pick this up without having to wait for next release?
unfortunately 
`brew cask reinstall --HEAD macdown` doesn't work

**Comment by franklinyu** [comment]
@timotheecour That release is in testing branch. We need more users to test it out before we push it to everyone. Or you may download from testing branch to try it.

**Comment by timotheecour** [comment]
@uranusjr I downloaded Version 0.7.2d126 2018-04-06 (996) Download Testing
from https://macdown.uranusjr.com/history/testing/
when open foo.md in macdown, then edit foo.md in sublime and save, the content is not updated in macdown.
Could we re-open this?

**Comment by timotheecour** [comment]
also, would be good if we don't even have to focus on MacDown for its view to refresh (as an option)

**Comment by silent-e** [comment]
I just installed the 0.7.2d126 (996) version and I am also not seeing changes I make in another editor (MacVim for me) reflected in the file in MacDown.  The Console app appears to indicate that MacDown detected a change though.

default	15:56:22.046669 -0700	MacDown	Making presenter AA4B31E9-35F6-4D97-B597-EABF59C0D6BD observe change

Running MacOS High Sierra 10.13.6

FYI

**Comment by megahall** [comment]
I tried version `Version 0.7.2d126 (996)` as well, editing the file using `nano` in a terminal, and the file update feature did not work for me either. Running High Sierra 10.13.4.

**Comment by themightyoarfish** [comment]
Same problem. Version 0.7.3 (1008.4), Mojave.

**Comment by themightyoarfish** [comment]
I think this is very important for a developer tool to have.

**Comment by uranusjr** [comment]
@themightyoarfish I would not disagree :) Any interests in helping implement this feature you consider very important?

**Comment by themightyoarfish** [comment]
I doubt i would be up to the task, considering it has bren tried before, but where would be the place to start?

**Comment by uranusjr** [comment]
This believe the detection-refresh framework is mostly there (which is why this was once closed). Here’s a list of things need figuring out:

1. Is the detection somehow not working? Why not? See #564 for how detection works right now.
2. If the current method is not working, are there alternative methods to detect changes? I’d start with looking into [FSEvents](https://en.wikipedia.org/wiki/FSEvents).
3. If the detection is working, maybe it’s the refreshing part that’s somehow failing? Why? (This part should be entirely contained in the editor implementation.)
