### ISSUE TITLE
tabedit multipule files

### ISSUE THREAD

**Issue by jinleileiking** [MacDownApp/macdown#631]
use tab manage many files.

**Comment by TwisterMc** [comment]
macOS is supposed to allow tabs everywhere, even apps that don't support tabs. So maybe this feature will fix itself?

**Comment by uranusjr** [comment]
Seems to be the case. I haven’t tried, but #617 says yes.

**Comment by franklinyu** [comment]
Wait for more macOS user to report whether this works.

**Comment by franklinyu** [comment]
https://github.com/MacDownApp/macdown/issues/603#issuecomment-280695653 also suggests yes, so it only fails for @jinleileiking. Try latest MacDown?

**Comment by jinleileiking** [comment]
recently, It cannot  merge autoly

**Comment by niklasberglund** [comment]
@jinleileiking do you mean merging windows into tabs using _Windows_ => _Merge All Windows_?

**Comment by jinleileiking** [comment]
@niklasberglund  yes. When open another md file , the two files will open two windows. This two windows cannot merge to one window(2 tab) automaticlly. We must push the auto merge button

**Comment by niklasberglund** [comment]
Maybe this is a duplicate of #757

**Comment by jinleileiking** [comment]
yes。 dup
