### ISSUE TITLE
I can't quit macdown

### ISSUE THREAD

**Issue by AZmake** [MacDownApp/macdown#632]
I write something  in macdown,but I want to rewrite,so,I delete all the content,and then I close the macdown. There is an alert ,and I click Don't save,macdown can't close,just waiting someting.This maybe a bug.Version 0.6 (749)

**Comment by franklinyu** [comment]
I didn't seem to reproduce this behavior. What's the OS X version?

**Comment by AZmake** [comment]
Yes,I can't find this "com.uranusjr.macdown.LSSharedFileList.plist" file, when I delete this "com.uranusjr.macdown.plist" file and restart macDown, it can help me ! May be there something wrong when I update macDown!  Thanks for your help!

**Comment by uranusjr** [comment]
Strange, this is not the first report that MacDown can crash under certain `LSSharedFileList` config. We don’t edit the file directly (only through OS behaviour), so this is either a bug in the OS, or I’m using some obscure API in a wrong way. Hopefully someone can preserve a copy of the file in the future, so we can either reproduce of inspect what can possibly go wrong in it…
