### ISSUE TITLE
-fobjc-arc is not supported on versions of OS X prior to 10.6

### ISSUE THREAD

**Issue by fero2004** [MacDownApp/macdown#633]
when i build the project,I get this error.

**Comment by JanX2** [comment]
@fero2004 MacDown uses APIs that are not available on 10.6 anyway. If the release build (binary) doesn’t run, you won’t be able to port it easily. You could try and check out an old version.

**Comment by uranusjr** [comment]
Yes, MacDown does not support OS X 10.7 and earlier, and I’m considering dropping support for 10.8 too. I’m sorry for the inconvenience, but I must scope the project somehow.

**Comment by fero2004** [comment]
My X-code version is 7.3.1 and OS X is 10.11.4. I solve this problem by set MASPreferences-dummy.m   compiler flags -fno-objc-arc

**Comment by uranusjr** [comment]
Hmm. Dummy files are produced (automatically) by CocoaPods, so if that’s the solution you might want to notify them as well, to see if it’s a bug on their side.
