### ISSUE TITLE
MacDown should support strikethrough e.g. "~~Not Any More~~"

### ISSUE THREAD

**Issue by heardrwt** [MacDownApp/macdown#637]
MacDown should support strikethrough e.g. "~~Not Any More~~"

**Comment by RoyiAvital** [comment]
Is MacDown still being developed?

**Comment by uranusjr** [comment]
> Is MacDown still being developed?

Not for the moment because I’m too busy. I hope I can resume development later this year.

Back to the original question though, MacDown already supports strikethrough as an opt-in feature. You can turn it on in MacDown → Preferences → Markdown.

**Comment by RoyiAvital** [comment]
@uranusjr , I really hope to see some progress.
Your program is great and it assists many students around the world.

Keep the great work!
