### ISSUE TITLE
Error in footnote example

### ISSUE THREAD

**Issue by akakie** [MacDownApp/macdown#641]
In the help file, the footnote example has a typo. The line 
``[^4]: You don't have to ...``
should begin with
``[\^4]:``

The missing backslash causes the footnote not to render at all. Adding the backslash fixes the problem.

**Comment by franklinyu** [comment]
Failed to reproduce this problem on my OS X 10.11.6 with latest MacDown. Minimal Working Example:

```
Some texts. [^foot]

[^foot]: This is footnote.
```

renders

![macdown footnote](https://cloud.githubusercontent.com/assets/3153452/17864446/2234c662-686c-11e6-935e-0605d3f1d167.png)

as expected.

**Comment by akakie** [comment]
Thanks for the reply. My problem certainly was operator error on my part. MacDown looks promising.

I'm writing documentation for PDF distribution. MacDown does render as described in your reply. I added a second footnote and that also rendered as expected. As long as the names or numbers designating each footnote are different, everything seems to work.
