### ISSUE TITLE
Macdown会支持多Tab吗?

### ISSUE THREAD

**Issue by ihaolin** [MacDownApp/macdown#642]
你好，
想问下，Macdown会支持多个Tab吗，有时会有编辑多个文件的需求。

**Comment by uranusjr** [comment]
根據回報，[10.12 的自動分頁功能](http://www.macworld.com/article/3088342/macs/how-to-use-tabs-in-macos-sierra.html)可以在 MacDown 正常使用，所以應該會直接使用了，不會支援 10.11 之前的版本。

See #617.
