### ISSUE TITLE
Is the MacDown project dead?

### ISSUE THREAD

**Issue by bartv42** [MacDownApp/macdown#643]
I use MacDown on a daily basis, but many small issues (all of which have been reported by others) are sometimes making it tedious to use. I haven't seen an update in months, so I wonder if this is still maintained?

**Comment by uranusjr** [comment]
I don’t have much time to push regular updates recently, but there are already some fixes in master, so either way there will probably be a new release sometime this year. I plan to make some progress before that happens, but no promises.

As always, forks and patches are much welcome.

**Comment by bartv42** [comment]
Ok, thanks for the update!

**Comment by franklinyu** [comment]
@bartv42 [The commit history](https://github.com/MacDownApp/macdown/commits/master) suggests not. We are moving slowly, but still moving.

**Comment by uranusjr** [comment]
I guess we can close this.
