### ISSUE TITLE
Duplicating Shortcut for 1:1 view and Ordered List.

### ISSUE THREAD

**Issue by ThePooE** [MacDownApp/macdown#645]
As the title suggested, the official version 0.6(749) has the conflicting shortcut for both 1:1 view and ordered list.

The shortcut to activate both functions is: Command ⌘ + Shift ⇧ + O

**Comment by uranusjr** [comment]
I think the 1:1 view shortcut is actually ⌘⇧0 (as in *zero*). Does this work?

**Comment by ThePooE** [comment]
Oh yeah it works, I miss took it as 'O'
