### ISSUE TITLE
Https Droplr Image not show

### ISSUE THREAD

**Issue by iShawnWang** [MacDownApp/macdown#646]
I use [Droplr](http://droplr.com) to host all my images and the link like `http://d.pr/i/1kuSw` not shown in MacDown, but this link works great in Safari and Chrome
**Is MacDown not support image with Https link ?**

**Comment by franklinyu** [comment]
MacDown works well with HTTPS link:

```
![img](https://avatars0.githubusercontent.com/u/20266594?v=3&s=400)
```

works on my computer. In addition, the link you provide (`http://d.pr/i/1kuSw`) is not in HTTPS.

**Comment by iShawnWang** [comment]
Great answer, I got it , 
### :D
Do you have any solution for this problem ? 
This confuse me a lot  ~

**Comment by franklinyu** [comment]
I thought I made it clear: just use a link to the image, instead of one to a webpage. That *is* the solution.

**Comment by iShawnWang** [comment]
I just brought [Droplr](http://droplr.com) , it makes share files with others super easy, 
I feel so sad cause when i drop a file to Droplr , it returns a link that i can't use directly on MarkDown, 
I plan to write a Email to Droplr for this , :(

---

And thanks for your great explaination 👍 
:D

**Comment by uranusjr** [comment]
I can’t seem to find Droplr’s pricing plans atm, but if you’re on a paid plan (maybe above a certain price) I think you can just append `+` to a URL to get the raw image. I use it all the time. Something like this:

~~~markdown
![An image from Droplr](http://d.pr/i/1ha3l+)
~~~

**Comment by iShawnWang** [comment]
### aaaaaaaaaaaaaaaaaaaaaaaaaaawesome 
It works like a charm ~
# :D
