### ISSUE TITLE
Support Versioning

### ISSUE THREAD

**Issue by stevemoser** [MacDownApp/macdown#648]
iCloud Drive relies on applications implementing their own versioning like the iWork apps. I know this would require a new file format probably but what are the chances that MacDown supports versioning/revisions in the future?

**Comment by franklinyu** [comment]
I did not see any description about versioning on [iCloud FAQ](https://support.apple.com/en-us/HT201104). Would you like to provide some more information about it? Particularly, what an app should do, to support this feature?

**Comment by stevemoser** [comment]
Never mind, it seems it is supported under the Browse Versions... menu item. Thanks.
