### ISSUE TITLE
Can't open markdown ".md" file in Devonthink Pro Office 2.9.2

### ISSUE THREAD

**Issue by mdking117** [MacDownApp/macdown#652]
I'm using Devonthink Pro Office 2.9.2 to manage project documents and I use macdown as the editor for my markdown notes.  By default the files have a .md extension.  My challenge is that when I try to open a file with macdown, I get an error message that macdown cannot open the file.  If I use other markdown editor, the contents shows up in chinese, though I'm only writing in English.
![dsg meeting notes 09-01-2016 md 2016-09-01 10 18](https://cloud.githubusercontent.com/assets/21684359/18171782/275eceb8-7031-11e6-8936-2d52b21b2815.jpg)

System Details:
* Mac OSX 10.11.6
* MacDown 0.6
* Devonthink Pro Office 2.9.2

**Comment by franklinyu** [comment]
How is the file created? If you created the file with another application, submit this issue to that application. The creator may have applied an encoding other than UTF-8.

**Comment by mdking117** [comment]
That did it.  the application !as creating the file in UTF-16 format.  Once I set the default to UTF-8, ti works as designed.
Thanks,
