### ISSUE TITLE
MathJax

### ISSUE THREAD

**Issue by victorivrii** [MacDownApp/macdown#660]
Mou recognized reference to external javascript, MacDown does not. However it is important: I want to use MathJax with my own configuration, like this (in particular, it makes numbering of equation etc, but not equation* (and so on)
```
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],},
        TeX: {equationNumbers: {
            autoNumber: "AMS"
          },Augment: {  Definitions: {
           macros: {
             overbracket:  ['UnderOver','23B4',1],
             underbracket: ['UnderOver','23B5',1],
           }
         }}},
    });
</script>
```

**Comment by uranusjr** [comment]
This is actually a safety measure: MacDown forbids remote scripts from HTTP. Use the HTTPS CDN link instead:

    https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
