### ISSUE TITLE
Critical Bug: HTML generation stuck if an image can not be loaded

### ISSUE THREAD

**Issue by CaledoniaProject** [MacDownApp/macdown#666]
If the MD file contains a image like this,

```
![AndroBugs_ReportByVectorKey.py](http://www.androbugs.com/images/v1.0.0/MassiveAnalysisTool1.png)
```

And if the image loads slowly, the right pane would be blank for a long time.
Looks like a bug to me.

**Comment by franklinyu** [comment]
Is there any slow image online for us to try this bug out? The file in your example is loaded on my machine in just a second.

**Comment by franklinyu** [comment]
Closed for lack of response.
