### ISSUE TITLE
macdown command line broken 

### ISSUE THREAD

**Issue by theooos** [MacDownApp/macdown#668]
Opening a file in the OSX terminal `macdown file.md` sometimes opens the file without any of its contents. Then when closing the window, it asks to save the changes, which would just overwrite the file with the blank contents.

> MacDown: version 0.6 (build 749)
> OSX 10.11.6 (15G1004)

**Comment by franklinyu** [comment]
The command line does not work for me either. At first it always open the developing version of MacDown (0.7); I got angry and deleted the binary for 0.7, and now it does nothing. I currently open my files with `open -a MacDown file.md`.

**Comment by uranusjr** [comment]
Fixed in 8e1fb45. I just released 0.6.2 that contains the patch. Please give it a shot and tell me if things are working!
