### ISSUE TITLE
Front-matter support doesn't go well with CR or CRLF new lines

### ISSUE THREAD

**Issue by doekman** [MacDownApp/macdown#669]
I first thought front-matter support didn't work, but it's a bug in handling line, see attached test-case files inside the zip:

* **Testing, with CR**: this causes MacDown to think the first three dashes is a horizontal line, the properties (except the last one) is a paragraph, and the last property is a heading (because of the 2nd tree dashes of front matter).
* **Testing, with CRLF**: Both three dashes of front-matter are interpreted as horizontal lines, and each property now is a paragraph.
* **Testing, with LF**: this one is the correct one, how it is expected.

[front-matter-bug.zip](https://github.com/MacDownApp/macdown/files/510402/front-matter-bug.zip)

**Comment by franklinyu** [comment]
I guess CR and CRLF case is simply not covered by design, since they are rare in OS X (macOS). This can well be a feature though (to support Windows newline style).

**Comment by uranusjr** [comment]
I added a simple change that relaxes the rule to match any combination of newlines, instead of just `\n`. This might be too naïve, but should be good enough for practical purposes.

**Comment by doekman** [comment]
Thanks for picking this up. It took me a while to figure out what the problem was.

**Comment by uranusjr** [comment]
Your observations are invaluable for the fix. Saved me a ton of effort to investigate so I can dive directly into the fix. Thanks a lot. :)

**Comment by doekman** [comment]
It started with a feature request to include auto front-matter detection ;-)

Is the next release planned yet?

**Comment by franklinyu** [comment]
@doekman [There are still some issues in the way](https://github.com/MacDownApp/macdown/milestone/11). Hard to tell when they will be solved, but we will try our best.

**Comment by doekman** [comment]
Sounds reasonable. I actually have an Apple Developer Account. I only have one iPhone app in the store, but don't intend to do much Apple development. 

But I could put MacDown in the app store, and keep it updated. Is that something you would like?

**Comment by franklinyu** [comment]
Sounds cool. I think anyone are legally free to redistribute the binary without asking for any additional consent as long as you conform to terms in the licenses. IANAL, but most of the licenses are MIT, so it doesn't seem to be a big deal. You can even make money out of it, if you like.

FYI, @uranusjr just released [v0.6.1](https://github.com/MacDownApp/macdown/releases/tag/v0.6.1).
