### ISSUE TITLE
support checkbox

### ISSUE THREAD

**Issue by chendongMarch** [MacDownApp/macdown#676]
[x] checked
[  ] unchecked

**Comment by uranusjr** [comment]
Already does as an opt-in. You need to enable the feature in the preferences, and use the following syntax:

```
* [ ] unchecked
* [x] checked
* [x] also checked
```

**Comment by YikSanChan** [comment]
Could you kindly point me to which settings to enable in the preferences?

**Comment by uranusjr** [comment]
@YikSanChan Rendering → Task list syntax

**Comment by YikSanChan** [comment]
Thank you!

**Comment by ocarlsen** [comment]
Hey would love to see this feature but not working fo me in version 0.7.1 (870).  Tried Preferences > Rendering > Task list syntax as suggested but rendering pane does not show checkbox.

**Comment by FranklinYu** [comment]
@ocarlsen Screenshot?

**Comment by ocarlsen** [comment]
@FranklinYu Oh my bad, I see I must use the bullet syntax.  I thought we would have "naked" checkboxes, without the bullets.  


<img width="1077" alt="Screen Shot 2019-04-10 at 1 22 05 PM" src="https://user-images.githubusercontent.com/2373329/55910813-2e34a400-5b94-11e9-9faa-de427a9c82de.png">

**Comment by FranklinYu** [comment]
@ocarlsen Yes, you need to use the bullet syntax. This requirement is consistent with GitHub and most other implementations.

**Comment by erikr** [comment]
Why is this feature opt-in? It is default for GitHub markdown. Perhaps it is not default for all flavors of Markdown, but I think it should be enabled by default.

**Comment by FranklinYu** [comment]
@erikr For backward compatibility to earlier version.
