### ISSUE TITLE
Logout with MacDown and crashed after prompting to save

### ISSUE THREAD

**Issue by xunlao** [MacDownApp/macdown#678]
I think a video says better:
https://vimeo.com/187716739

To reproduce:

Step 0 Make sure you are ready to logout your Mac.
Step 1 open MacDown
Step 2 type something and then remove then
Step 3 Mac Logout when MacDown stays as it was
Step 4 when prompted to save, click "don't save"
Step 5 BOOM. I might want to Force Quit (CMD+OPT+ESC) to close it if I want to logout.

Or there's a better way to avoid the crashed, in terms of how I should use it?

**Comment by franklinyu** [comment]
Confirmed on El Capitan, latest MacDown (0.6.2). Note that when logging out, the checkbox "Reopen windows when logged back in" should be **unckecked** to reproduce this bug, otherwise OS X will simply save the session without triggering the "Do you want to save" prompt.

**Comment by uranusjr** [comment]
I just released 0.6.3. Could you verify whether the crash persists?

**Comment by xunlao** [comment]
@uranusjr nice. It's fixed.
