### ISSUE TITLE
[feature]auto merge windows in MACOS 10.12

### ISSUE THREAD

**Issue by jinleileiking** [MacDownApp/macdown#679]

**Comment by franklinyu** [comment]
So it doesn't work for you? This is weird, since it is reported as working in #617. Just to make sure, both your MacDown and macOS are up to date, right?

**Comment by jinleileiking** [comment]
macdown
Version 0.6.2 (772)

macos: sirria

**Comment by franklinyu** [comment]
Duplicate of #631.
