### ISSUE TITLE
math formula not rendering

### ISSUE THREAD

**Issue by bsdis** [MacDownApp/macdown#680]
Hi, I have tried several types of math formula in macdown and its simply not rendering any formula.

Even the example given on macdowns homepage:
Lorem ipsum $$ y = ax + b $$ dolor sit amet…
is not rendering, its just simply writing $$ y = ax + b $$ in the output instead of the actual formula.

Is this a bug which has been introduced at some point or am I just missing something?

**Comment by franklinyu** [comment]
Try "Preferences -> Rendering -> TeX-like math syntax"

**Comment by bsdis** [comment]
ah ok, that is what I needed 👍

**Comment by uranusjr** [comment]
I’m closing this then. :)
