### ISSUE TITLE
Export PDF by my own css

### ISSUE THREAD

**Issue by Jy-Liu** [MacDownApp/macdown#692]
I think the built-in render css is not that pretty for my use when I export it in PDF out.
However, I find that the render doesn't change even if I choose my own css to be the default render file in Preference.

How can I change the css it export out?

**Comment by uranusjr** [comment]
You can add your own CSS files to `~/Library/Application Support/MacDown/Styles`. After reloading they will be available in Preferences.

**Comment by Jy-Liu** [comment]
I have write my own css and put it in the $PATH. But it did't works!!!
I mean when I EXPORT THE PDF VERSION out, the css I wrote didn't work!!!

**Comment by uranusjr** [comment]
Can you describe in detail how you do this, and how does it not work? As I understand this process does work.

**Comment by franklinyu** [comment]
@Jy-Liu Do you mean that the CSS does work in the preview pane, but not the exported PDF file? In my case it works for both.

**Comment by Jy-Liu** [comment]
@franklinyu, I mean that the CSS does NOT work in the preview pane, but work the exported PDF file. 

@uranusjr, Yes, this process is work for both. However, I should command+q to close the MacDown app and re-open after I change the customized css. I think it should work in the preview mode when I close the MacDown with command+w and re-open after I change the correspondent css.

**Comment by Jy-Liu** [comment]
Thank you for solving my question !!!
A nice app and I will recommend it to all my friends !!!
