### ISSUE TITLE
$$ Latex Support Not Working in 0.6.3

### ISSUE THREAD

**Issue by timothy-gibson** [MacDownApp/macdown#693]
Previously I could use the $$  (double dollar sign) syntax to do my inline maths equations. As soon as I updated, this is no longer rendering.

**Comment by onionyst** [comment]
Same problem. 
MacBook Air 2014 @ macOS Sierra 10.12.1

**Comment by uranusjr** [comment]
Damn, I implemented a new preview mechanism, and didn’t realise that it would break the MathJax hook… I’ll try to fix it asap. Please use 0.6.2 in the mean time.

I am so so so sorry for this. :(

**Comment by uranusjr** [comment]
I released 0.6.4 that rolled back the breaking change. Sorry for the trouble.

**Comment by timothy-gibson** [comment]
Thanks so much for the prompt response and fix!

**Comment by Clcanny** [comment]
latex support working in 0.7(the latest) now
