### ISSUE TITLE
rendering css solarized(light)

### ISSUE THREAD

**Issue by AZmake** [MacDownApp/macdown#695]
#why the style of exported file  pdf  is different  with html  ? The pdf isn’t include styles , but the html. Is it that pdf not support exported include styles now?
 PS:When the rendering css is solarized(light) the pdf is not regular, and  when I change rendering css to github2，the pdf is regular.
I have uninstall and install  MacDown.
macOS 10.12.1   MacDown Version 0.6.4 (786)

**Comment by franklinyu** [comment]
Didn't upgrade to macOS Sierra; waiting for anyone to confirm this.
