### ISSUE TITLE
Raw URLs preview as text not hyperlink

### ISSUE THREAD

**Issue by p-i-** [MacDownApp/macdown#701]
Most `.md` renderers (e.g. this one) seem to automatically convert a floating URL e.g. http://foo.com to a (clickable) hyperlink without having to use `[]()` notation.

It would be nice if MacDown's Preview pane also did this.

**Comment by franklinyu** [comment]
In "preferences -> Markdown -> Inline formatting", check "Autolink".

**Comment by Jmuccigr** [comment]
The MarkDown spec handles this with angle brackets:
```
Markdown supports a shortcut style for creating “automatic” links for URLs 
and email addresses: simply surround the URL or email address with angle brackets
```

So, `<http://nytimes.com/>` gets you <http://nytimes.com/>.

**Comment by franklinyu** [comment]
Closing for lack of feedback.
