### ISSUE TITLE
Automatic list numbering should all start with 1.

### ISSUE THREAD

**Issue by kocsenc** [MacDownApp/macdown#702]
Numbered lists do not need to sequentially increase. When using MacDown while starting a number list, the second item will be prefixed with a `2. ` and the third with a `3. ` automatically. 
Instead those items can all be prefixed by a `1. `. 

### Currently
```
1. first item <press enter>
2. second item <press enter>
3. third item
```

### Expected
```
1. first item <press enter>
1. second item <press enter>
1. third item
```

In both cases above the Markdown rendered will be a monotonically increasing numeric list so the result is no different. The reason this works is because if you wish to insert an element in the middle of the list you would not have to change all of the other elements. 

### Suggestion 
It could be a preference or the default.

**Comment by franklinyu** [comment]
Risky to set as default; may as well be a preference.

**Comment by kocsenc** [comment]
@franklinyu I agree. It may be confusing for those who don't really know that his is a feature.

**Comment by djstevenson** [comment]
Agreed, and there’s a precedent for it - the markup in Trac does exactly this.

**Comment by asmod3us** [comment]
I would suggest to go even further and use `-` for all but the first list item. This would make it very easy to switch list types between numbered and unnumbered by editing the first item.

**Comment by franklinyu** [comment]
@asmod3us That is an interesting point, but it involves modification (extension) of Markdown syntax, so we need a new Markdown parser for that. I have never heard about any parser with that extension.

**Comment by asmod3us** [comment]
@franklinyu Just to avoid any confusion, the preview for this works fine right now with MacDown 0.6.4 (786). I just changed the autocompletion from a number to `-`. Do you mean we'd need a Markdown parser to change the automatic list numbering behaviour?

![screen shot 2016-12-16 at 08 37 42](https://cloud.githubusercontent.com/assets/450168/21255251/01fb0ad2-c36b-11e6-908b-f3fcc2636722.png)

**Comment by franklinyu** [comment]
@asmod3us WOW, didn't know that. Sorry about confusion. Then the only thing to do is just to change the automatically inserted text from `n. ` to `- `, right? And I expect this to be configurable.

**Comment by asmod3us** [comment]
@franklinyu Yep, that sounds like a great approach.

**Comment by Jmuccigr** [comment]
This is not universal behavior though among markdown parsers, is it? pandoc, for example, will start a new list when the marker type changes, so
```
1. one
- two
- three
```
produces two lists, not one:

<ol class="incremental" style="list-style-type: decimal">
<li>one</li>
</ol>
<ul class="incremental">
<li>two</li>
<li>three</li>
</ul>

As does github:

1. one
- two
- three

**Comment by kocsenc** [comment]
As @Jmuccigr mentioned, this isn't default markdown behavior. And I'd argue ising '-' is more confusing. 

In hopes of keeping things separate I think it's one feature to have numbered lists all be capable of starting with 1's and another feature to switch numbered lists to a bulleted list. But mixing both in an unconventional markdown way is bound to be more problematic for usability and also compatibility.

**Comment by asmod3us** [comment]
This seems to be a MultiMarkdown feature. See [Babelmark](http://johnmacfarlane.net/babelmark2/?text=1.+one%0A-.+two%0A-.+three) for a comparison of how different Markdown implementations render it. Both Marked 2 and MacDown (unknowingly?) seem to support this feature.

@kocsenc I agree it makes most sense for a Markdown editor to insert '1.' as automatic numbering. If there was a MultiMarkdown mode in MacDown that preference could switch the behaviour to '- ' when enabled.

**Comment by franklinyu** [comment]
@kocsenc @Jmuccigr Yes, this is not widely supported, so even if this feature is available, it will definitely be opt-in. I personally prefer writing universal Markdown (like CommonMark), but it should be up to the users what style they choose. I appreciate this attitude of a tool; for example, Stroustrup allows you to override operators in C++ instead of just saying "oh you will screw things up so I made the decision for you".

**Comment by asmod3us** [comment]
@kocsenc @franklinyu @Jmuccigr Taking a closer look at the Babelmark output, I believe this is in fact default markdown behaviour, at least in the sense that the original Gruber Markdown implementation (Markdown.pl) renders an ordered list with the given input.

**Comment by franklinyu** [comment]
@asmod3us I am still not convinced that it's a feature in `Markdown.pl` instead of a corner case he didn't know, because:

 1. Gruber didn't mention this in his [official syntax page][1].
 2. It doesn't look that neat as the lists he mentioned. Looking at

    ```markdown
    ordered:

    1. foo
    2. bar

    unordered:

    - foo
    - bar
    ```

    a reader immediately know that it's a list *from plain text*.

Nevertheless, I agree with the freedom to choose.

[1]: https://daringfireball.net/projects/markdown/syntax

**Comment by uranusjr** [comment]
I admit I just skimmed through the thread, but nobody seems to have mentioned this is already implemented as a preference.

Preferences → Editor → Auto-increment numbering in ordered lists

This has been present since version 0.3 (released in 2014).

**Comment by kocsenc** [comment]
@uranusjr no it has not. The enhancement talks about having the automatic numbering always prefix with '1.'s.

**Comment by franklinyu** [comment]
@kocsenc You mean, even if you prefix the first one with "2."?

**Comment by kocsenc** [comment]
@franklinyu I don't think that starting prefixing with `2.` relates to any of the cases in this thread. I think the originating post explains it clearly.

**Comment by franklinyu** [comment]
@kocsenc I think I missed something. Just to make sure, I thought this behavior to be what you want:

1. Make sure that "Preferences → Editor → Auto-increment numbering in ordered lists" is *not* checked.
2. Type `1. Foo` in source code panel.
3. Hit <kbd>&#9166;</kbd>

Then I am able to see

```markdown
1. Foo
1. 
```

**Comment by kocsenc** [comment]
@franklinyu yup! Not sure about step number 1 though. That's an implementation detail.

**Comment by franklinyu** [comment]
@kocsenc I don't get it: why is it an implementation detail? It's in preference panel, available for user. For anyone who wants this feature, just go there and uncheck the box.

**Comment by kocsenc** [comment]
Ah i see. You must uncheck the box. Thanks.
