### ISSUE TITLE
Wrong Rendering for UNDERLINE, STRIKETHROUGH, HIGHLIGHT and FOOTNOTE

### ISSUE THREAD

**Issue by 7php** [MacDownApp/macdown#705]
Hi.
I'm using a Mac OSX v10.10.5 with MacDown v0.6.4 (786).
It has the following issues, or bug?  : 
1) UNDERLINE is not working, tried _So doge_ (\_So doge\_)
2) STRIKETHROUGH is not working, e.g: ~~Much wow~~ (\~\~Much wow\~\~)
3) HIGHLIGHT is not working, e.g: ==So good== (\=\=So good\=\=)
4) FOOTNOTE same thing, it's not working as expected and as explained in the default MacDown readme example that comes with the first install.

Are these bugs, or have these been superseded?

**Comment by franklinyu** [comment]
All four should be available in Preferences -> Markdown.

**Comment by 7php** [comment]
Perfect, everything solved. Thank you very much @franklinyu !
MacDown is a great piece of software, elegant. Thank for all you do!

PS: This was no bug, just needed more insight into the tool.

cheers
