### ISSUE TITLE
Having two dollar signs ($) in a document breaks the presentation in the edit pane

### ISSUE THREAD

**Issue by sebrose** [MacDownApp/macdown#713]
If you have two dollar signs in a document, the edit pane then displays all text between them in a different font color (grey on my install). All the enclosed text is rendered in the same font size as the line the opening $ sign.

The preview rendering is unaffected by this behaviour.

![image](https://cloud.githubusercontent.com/assets/2204142/21370572/2d460d12-c704-11e6-9476-8117617f5a7f.png)

**Comment by franklinyu** [comment]
Same as #489.
