### ISSUE TITLE
MacBook Pro Touch Bar support

### ISSUE THREAD

**Issue by alexkaessner** [MacDownApp/macdown#714]
I thing MacDown is one of the application that fit's perfectly for a custom new Touch Bar interface. What do you guys think? I would help to create the icons for the Touch Bar if @uranusjr is interested to add this. 😉

I would basically add the formatting options on a MacDown Touch Bar:
- H1, H2, H3
- Bold, Italic, Underlined
- List
- Image
- Link
- and so on

What do you think?

**Comment by brunophilipe** [comment]
I would like to claim this issue!

I have started working on it tonight, and now that I have a basic structure, adding new buttons/actions is a piece of cake.

Have a look at [this demo video I made](http://giphy.com/gifs/okqjkGd9by9O0/html5).

**Comment by alexkaessner** [comment]
Nice to see this!! 👌 

As suggested I would make the touch bar something like this: 

![touch bar](https://cloud.githubusercontent.com/assets/6615076/21788675/4ae1f51c-d6d0-11e6-8105-5816905a65a3.png)
_From left to right: Popover to select Heading or Paragraph; Formatting Group; Unordered List; Ordered List; Block Quote; Link; Image; Show Auto Completion._

The different List types could be packaged together to a popover like the Headings. But I don't know these are maybe the most important features? The best would be to make the Touch Bar Customizable and this maybe only the default! 😉

**PS: I could help to provide nice Icons. This is just fast thrown together.**

**Comment by brunophilipe** [comment]
I think what you suggested is perfect! If you'd like to generate images, these are the ones I already have from Apple's API:

![Imgur](http://i.imgur.com/TvXcErL.png)

You can generate any others you think are needed as templates (transparent pngs with grayscale colors only, colors are applied by Cocoa as required) and I'll be happy to adopt them! =)

**Comment by alexkaessner** [comment]
Thanks, I know the System Icons :wink:

I will look into this a little deeper and prepare the missing icons.

**Comment by brunophilipe** [comment]
Ok that's great! 😀

**Comment by brunophilipe** [comment]
I went ahead and added a plugin hook for touch bar items as well!

![Imgur](http://i.imgur.com/cJ3BWKs.png)

And if the plugin includes an image file called `TouchBarImageTemplate@2x.png`, then it looks even better:

![Imgur](http://i.imgur.com/CAk7nsS.png)

**Comment by alexkaessner** [comment]
@brunophilipe Nice progress! 👌 
I've prepared some of the icons, with a uniform style. Where/how can I upload them the best way to also get the contribution? 😀 

The customisation is nice! Is it possible to add the typing suggestions as optional to the touch bar? I think some people will use them.

PS: The plugin Item is awesome! 👌 Is it also possible to change the text on the plugin buttons as plugin creator?

**Comment by brunophilipe** [comment]
@alexkaessner One way to do it is by creating a clone from my repo from the branch `touchbar-support`, and then open a pull request back to that same branch on my repo.

And regarding the text on the plugin touchbar buttons, that could be done, but since the toolbar menu items just take the plugin name, I thought it would be more consistent if it also did the same for the touchbar.

**Comment by uranusjr** [comment]
I can grant you two push privilege to the main repo so you can just both work on the same branch together. Would that make things easier?

**Comment by alexkaessner** [comment]
@uranusjr Sure, that would be easier, but I don't have to make so many commits 😄 

So my thoughts on the Touch Bar interface are:

**Default Bar:**
![default](https://cloud.githubusercontent.com/assets/6615076/21890190/d0cf27aa-d8cc-11e6-9266-8000b90ada93.png)

**Default with extended Text Suggestions:**
![default with suggestion](https://cloud.githubusercontent.com/assets/6615076/21890202/dd6c2a1c-d8cc-11e6-93ae-e072041d8745.png)

**Inside the Header Popup:**
![heading](https://cloud.githubusercontent.com/assets/6615076/21890223/f8221e5c-d8cc-11e6-96ff-0e10e96643a1.png)

**Alternative Buttons for customized Bar:**
![alternative](https://cloud.githubusercontent.com/assets/6615076/21890218/f1c7fbe4-d8cc-11e6-8208-b3e24cd879e1.png)
_I thought it would be nice to have two buttons for the show/hide Editor/Preview (right two buttons)._

**Comment by brunophilipe** [comment]
@uranusjr That would help, even though I do like doing pull requests for the sake of doing code reviews.

@alexkaessner Those look really nice! Just a few comments: Is the one after the "<>" (code) button for markdown comments? Since markdown doesn't use double slashes for comments (like in C, Java, Swift, etc...), I think the icon could be a bit misleading. I don't think my version is a lot better, though. Is the one after that to copy the HTML code? I like that one, just to make sure!

Oh and I think I accidentally disabled the autocomplete text feature. I'll fix that.

**Comment by alexkaessner** [comment]
@brunophilipe Yeah I was thinking about the comment icon. I thought the `//` is more common for comments and better understandable than `<!--`. [Coda](https://panic.com/coda/) also uses the double slash for commenting even in a HTML doc. And I like this, but I'm unsure about the Icon. It looks very similar to the Code Block Icon…

![code](https://cloud.githubusercontent.com/assets/6615076/21892041/d019a7be-d8d5-11e6-98b8-926e5afc7399.png) ![comment](https://cloud.githubusercontent.com/assets/6615076/21892043/d136cfb4-d8d5-11e6-92ed-cb2cf14415c2.png) ![comment old](https://cloud.githubusercontent.com/assets/6615076/21892044/d25e35d0-d8d5-11e6-9f80-f7e795dcd013.png)

**Comment by uranusjr** [comment]
Alright I’ve sent the invitations. :) @brunophilipe Since the master branch is protected, you still need to push a new branch. You can then create a PR from that branch (yes, PR can be created within the same repo) for the code review.

**Comment by brunophilipe** [comment]
@alexkaessner Yeah I see your point and I agree a double slash icon is more universally understood indeed.

@uranusjr Ah that's great then! I'll accept it and push my branch to the main repo later today.

**Comment by brunophilipe** [comment]
@alexkaessner I have pushed my code to the [`touchbar-support`](https://github.com/MacDownApp/macdown/tree/touchbar-support) branch in this repo. You can just add the icons to the `xcassets` file and I'll plug them in the right places.

**Comment by alexkaessner** [comment]
@brunophilipe I've added the icons with commit 9c27577. I've also included two "new" icons for Strikethrough and Highlight:

![strikethrough](https://cloud.githubusercontent.com/assets/6615076/21928894/b59affa6-d98d-11e6-8249-7630c89c126c.png) ![highlight](https://cloud.githubusercontent.com/assets/6615076/21928895/b5c2e50c-d98d-11e6-9a7f-5dd823e0b8ae.png)

I'm not sure if we should include these in the format segmented control. If we would add this, the segmented control is so long.
Either we add them as single buttons (for optional customization) or a second format segmented control with them included. Or both… 😄

**Comment by uranusjr** [comment]
> I'm not sure if we should include these in the format segmented control. If we would add this, the segmented control is so long.

Also they are not standard Markdown, and not all people use them, especially Highlight (because GitHub doesn’t have it). I think they should be standalone.

**Comment by alexkaessner** [comment]
@brunophilipe How is the Touch Bar support going?

**Comment by brunophilipe** [comment]
Hey! I've been having a long week at work! However there was much progress already, have a look!

![Imgur](http://i.imgur.com/FQMq2Fu.png)
![Imgur](http://i.imgur.com/Vkcr9HL.png)

These are all the currently implemented and functional touch bar buttons:

![Imgur](http://i.imgur.com/gcMeqBG.png)

**Comment by alexkaessner** [comment]
@brunophilipe Thanks for the update, nice to see the progress! 😉

First, is it possible to put one more button into the default set? I think a good button to add here is the "Highlight" button?!

Also why did you put the Links and Images together? It makes sense for Lists and Shift Text, but Links and Images aren't that similar (even if they are syntax wise). I think it would be useful to have them divided for a higher customization possibility.

And the Text Formatting Group has a little different Style as what Apple uses. Here are two screenshots from Text Edit and Pages:

<img width="1085" alt="text edit" src="https://cloud.githubusercontent.com/assets/6615076/22087073/3267ea06-dddc-11e6-8818-e78677b85404.png">
<img width="1085" alt="pages" src="https://cloud.githubusercontent.com/assets/6615076/22087080/389e2386-dddc-11e6-9756-1813b4701146.png">

**Comment by brunophilipe** [comment]
Ok! I had some tough weeks at work but now I'll have some time to work on this again. My only concern of adding the highlight button to the default set is that I don't think the highlight extension is enabled by default. Having a button that "doesn't work" in the default set would be bad.

**Comment by alexkaessner** [comment]
@brunophilipe No problem.
You are right with the highlight button. I wasn't concerned about this! Having a not working button in the default set is indeed not the best.
Good question what else to add. Maybe the default set you made is fine. I mean users are still able to customize it. 😄

As you pointed out the problem with not working buttons…is it possible to hide the not working buttons in the bar selection or disable them? If not we should definitely show a small error that this formatting isn't enabled in the settings.
This is also a problem for underlined. I think it's disabled by default right? Is it possible to disable only the underlined section button here?

The other question is why underlined and so on are disabled by default @uranusjr?

**Comment by uranusjr** [comment]
This could be a bit late, but the *hide editor pane* and *hide preview pane* icons are a bit strange to me. The editor one, for example, seems to be indicate the editor will fill the window, i.e. the preview pane will be hidden. Not sure if it’s just me.

The non-standard syntax defaults are set based on their popularity I get from various sites, and whether they conflict with other syntaxes. Underline is disabled by default because it conflicts with emphasis, and does not exist in either StackOverflow and GitHub. Intra-word emphasis is on because GitHub has it. Etc.

**Comment by alexkaessner** [comment]
@uranusjr It's not too late yet, but you are right! The icons need to be switched!
This is hiding the editor pane:
<img height="30" alt="hide editor" src="https://cloud.githubusercontent.com/assets/6615076/22733822/b0385480-edf3-11e6-802d-9ab642a20618.png">

And this is hiding the preview pane:
<img height="30" alt="hide preview" src="https://cloud.githubusercontent.com/assets/6615076/22733823/b0605188-edf3-11e6-90e1-73619ff90e26.png">

**Guess it's my fault. My naming of the icons is wrong. I will fix this in a minute!**

Interesting to know. Thought the standard formatting is everywhere the same.
So we definitely need to hide/disable them or show an alert. Otherwise users will be confused whats wrong with the Touch Bar buttons.

**Comment by brunophilipe** [comment]
I will add code to hide the buttons depending on the settings now :)

**Comment by alexkaessner** [comment]
How is the status? Do you still need resources?

**Comment by brunophilipe** [comment]
I haven't had much free time at all in the past weeks, I'm sorry that haven't been able to contribute at all.

**Comment by niklasberglund** [comment]
@brunophilipe had a look at your _touchbar-support_ branch. Looking good! Looks near done. Wondering if I can help you out? What's left - adding the missing buttons?

Had a talk with @uranusjr about the show/hide preview/editor buttons in the toolbar. Turned them into a single "layout" button which shows a menu with choices. Maybe a similar approach for the touch bar would be good. At https://github.com/MacDownApp/macdown/pull/839 you can see what I mean.

**Comment by niklasberglund** [comment]
Okay I got it. Had another look at this. All the buttons are there - available to add by customizing the touch bar.

I guess what's left is highlight state of hide/show editor/preview buttons. However I'm wondering if they are necessary in the touch bar. I'm very new to touch bar but seems like most applications use the touch bar for text formatting. Toggling visibility of editor/preview is not such a frequent task as writing in bold etc.

Wouldn't hurt to have them, but to me the touch bar support looks complete even if they would be removed.

![image](https://user-images.githubusercontent.com/331986/29747245-ffada14e-8b25-11e7-9288-0dd69599f870.png)

**Comment by alexkaessner** [comment]
Nice! 👌

I would say it's better to give the hide/show editor/preview buttons a highlight state, because there both states indicators.
If you e.g. press the hide preview button the preview keeps hidden until you press this button again. So it just makes sense to also show this the user. Another reason is that we don't have a explicit "show" button.

I was wondering where some of the buttons @brunophilipe [added earlier](https://github.com/MacDownApp/macdown/issues/714#issuecomment-273606168) are?
There're missing: _underlined, strikethrough_ and _highlight_

**Comment by niklasberglund** [comment]
@alexkaessner my writing was a bit confusing. I meant maybe dropping the buttons, not the highlight state. Updated my comment to clarify.

Right, there should be more buttons. I'll see if I can find them in the code later when I look at this again.

**Comment by brunophilipe** [comment]
@alexkaessner you have to enable the respective plugins to get the buttons to show up! :-)

The only thing that’s missing from my perspective is to update the panel buttons to behave like the menu, right?

**Comment by brunophilipe** [comment]
<img width="1710" alt="screen shot 2017-08-28 at 21 10 25" src="https://user-images.githubusercontent.com/2136642/29789430-5495df3a-8c36-11e7-86b8-36902b4d461a.png">

**Comment by niklasberglund** [comment]
> @alexkaessner you have to enable the respective plugins to get the buttons to show up! :-)
Oh, I gotta update the toolbar PR 😊

> The only thing that’s missing from my perspective is to update the panel buttons to behave like the menu, right?
The panel buttons in the toolbar have changed a bit. Turned it into one button with menu alternatives. There's some discussion around it in the PR #839

**Comment by jeanfabre** [comment]
Hi,

 ok, I wasn't aware that there was touchBar support, and I went with BetterTouchTools.

![image](https://user-images.githubusercontent.com/1140265/30972424-26317780-a473-11e7-992b-385440c4905c.png)

 But How can I trigger the actual touchbar support? I have 0.7.2d49(919). I am confused... 

Bye,

 Jean

**Comment by alexkaessner** [comment]
@franklinyu @brunophilipe How is the state of the touch bar support? As the same with the issue #282  I would wrap this up and bring this to an official release. It's quite finished and would be sad to let it end here! 😉 

I would only change the grouped button style of _Lists_ and _Shift Text_ to the separated style like the _Text Formatting_.
And of course like with the toolbar the new Hide/Show Preview/Editor behavior. Whatever this will be now…so it in one style with the toolbar.
If we want to use the simplified icons for this, I can provide them!

**Comment by alexkaessner** [comment]
@brunophilipe I've updated some of the icons in the `toolbar-support` branch. So using these there's only the "new" Hide/Show Preview/Editor missing? Maybe we could do them with a Touch Bar Popover and this as button icon:

<img height="30" alt="hide preview" src="https://user-images.githubusercontent.com/6615076/34177255-47ba3362-e503-11e7-8a71-549b3d77393f.png">

**Comment by uranusjr** [comment]
closed by #978
