### ISSUE TITLE
how to generate a catalogue automatically?

### ISSUE THREAD

**Issue by betseyliu** [MacDownApp/macdown#717]
when i use cmd markdown , I can easily get a catalog by typing  [TOC]. So is there any way to generate a catalogue in the same way？

**Comment by franklinyu** [comment]
Please investigate the preference panel.

**Comment by alanhg** [comment]
![image](https://user-images.githubusercontent.com/9245110/80271637-94835a80-86f4-11ea-88d3-9efc80fd0d92.png)
