### ISSUE TITLE
Travis build failing on pod install

### ISSUE THREAD

**Issue by niklasberglund** [MacDownApp/macdown#718]
I see two ways to fix it.
Use a newer Xcode image with Travis:
`osx_image: xcode8.2`

Or...
Can probably be resolved by passing the `--no-repo-update` flag to `pod install`. Then of course the repo won't be updated, but *might* work as a temporary fix.

Excerpt from build log:
```
$ bundle install
$ travis_wait bundle exec pod install

Still running (1 of 20): bundle exec pod install
The command bundle exec pod install exited with 1.

Log:

Updating local specs repositories
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)
Update CocoaPods, or checkout the appropriate tag in the repo.
/Users/travis/build.sh: line 151:  3648 Terminated: 15          travis_jigger $! $timeout $cmd

The command "travis_wait bundle exec pod install" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by franklinyu** [comment]
Did Travis CI drop support for 0.39? Maybe we can just bump CocoaPods to v1.1.1 (latest)?

**Comment by uranusjr** [comment]
Honestly I seldom use CocoaPods now, and Travis CI less so, so I’m not very familiar with the problem... But if all dependencies can be built successfully with the latest CocoaPods version, we should probably bump it. This fix should be part of #719 I think.

**Comment by uranusjr** [comment]
Side note: We should probably upgrade the Xcode version in `.travis.yml`. But that’s a separate (non-critical) issue.

**Comment by niklasberglund** [comment]
I've barely used Travis. I thought the CocoaPods version was tied to the Xcode version in `.travis.yml` but seems like it's separate. Updating CocoaPods would solve the issue. It's CocoaPods who dropped support for 0.39 with the pods repo.
