### ISSUE TITLE
Shell support

### ISSUE THREAD

**Issue by niklasberglund** [MacDownApp/macdown#726]
Would shell support like TextMate's `mate` command line tool be useful? It's something I really miss in MacDown, but not sure about others. I'm using `mate` a lot just for opening documents in TextMate. One could argue that this functionality is already available by doing `open -a "MacDown" some-file.md` or even create an alias. I just find a dedicated command line tool way more convenient and it brings this convenience to all users.

Could also in the future implement something similar to TextMate's `rmate` for editing files from a SSH session in TextMate.

Created a mockup of preferences for shell support. I'd be happy to implement this if it's something you also think is a good fit for MacDown. Checking here first.

<img width="472" alt="screen shot 2017-01-11 at 15 04 10" src="https://cloud.githubusercontent.com/assets/331986/21838835/6126225e-d80f-11e6-9948-2c6b25bb34e5.png">

**Comment by franklinyu** [comment]
`macdown File.md` in terminal shall open MacDown with content of `File.md`.

**Comment by franklinyu** [comment]
Oh it's in `MacDown.app/Contents/SharedSupport/bin/macdown`

**Comment by niklasberglund** [comment]
@franklinyu  ah cool stuff. Now I see the `macdown-cmd` target. Guess it's the line `binary "#{appdir}/MacDown.app/Contents/SharedSupport/bin/macdown"` line in the MacDown cask that installs the binary in some `$PATH` dir or create alias. Can't find any (user friendly)way to do it with MacDown installed from .dmg. Of course I could create an alias, but is there some way for average Joe to use it?

**Comment by franklinyu** [comment]
Like copy/symlink the `macdown` file to your `$PATH`?

**Comment by niklasberglund** [comment]
Yea, but I mean like let MacDown do that for example through a settings view like above. Not all users are comfortable creating symlinks, and it seems like right now if installing MacDown from .dmg file there's no way to know of the command line tool unless you inspect the .app contents or source code.

**Comment by uranusjr** [comment]
When I first implement the CLI utility I did think about putting a UI to install it, but couldn’t think of a good one. Most applications I researched simply use a button or menu item that says “Install Command Line Utility” or something similar, which is way too vague, unsafe, and inflexible (e.g. what if I have Homebrew and want to install it somewhere else).

TextMate’s solution, however, seems much better. This is low priority for me, but I wouldn’t object if someone cares to send in a PR. :)

**Comment by franklinyu** [comment]
> Not all users are comfortable creating symlinks.

Did you mean the users who are not used to command line?

**Comment by niklasberglund** [comment]
> Did you mean the users who are not used to command line?

Actually no 😊  Some users use command line for basic stuff, but don't know what a symlink is or how to create one.

I think it'd be really useful if it can be installed through the UI. Currently user's who installed MacDown from .dmg file aren't given a fair chance of even knowing about this command line utility. 

@uranusjr cool, I'll implement it and see if the PR makes it through 😊

**Comment by franklinyu** [comment]
@niklasberglund I wish it's an opt-in, so that it won't conflict with Homebrew's installation…

**Comment by niklasberglund** [comment]
@franklinyu yea, opt-in and will be compatible with the Homebrew cask. If MacDown is installed from the Homebrew cask then the UI will show that the command line utility is already installed.

**Comment by uranusjr** [comment]
> If MacDown is installed from the Homebrew cask then the UI will show that the command line utility is already installed.

… and automatically shows the correct location of the symlink. Remember Homebrew can be installed to a custom path, so the location might not be as predictable as one would expect. This would require some heuristic because there isn’t (I don’t think) a systematic way to find where a certain file has been symlinked to. A simple way might be to search the user’s `$PATH$` at startup (or when then pref pane is revealed?) to find if there is a symlink pointing to the contained CLI utility.

**Comment by niklasberglund** [comment]
Would you be opposed to using `NSTask` to invoke `which macdown` for checking whether it's installed and at what location? Or is iterating over and searching in the user's `$PATH` preferred?

**Comment by franklinyu** [comment]
If MacDown is launched from Dashboard, `$PATH` in MacDown may be different from the one in terminal, because `~/.*rc` files are not loaded.

**Comment by uranusjr** [comment]
@niklasberglund I think you need an extra shell anyway because the problem @franklinyu mentioned, so using `which` is fine—just make sure you use `/usr/bin/which`, not just `which`. Launching a shell matching the current user’s seems pretty involved though, a simple search yield a lot of code snippets.

http://stackoverflow.com/questions/386783
http://stackoverflow.com/questions/208897

**Comment by uranusjr** [comment]
Oh, and by the way, if we do this we’ll need a new preference icon. @alexkaessner would you be interested?

**Comment by alexkaessner** [comment]
@uranusjr **Oh yeah, I can create a new one.** So we need a icon for the `Terminal` setting like on the first screenshot or does it changed?

**Comment by uranusjr** [comment]
@alexkaessner A *Terminal* icon should be right, unless @niklasberglund has something in mind?

**Comment by niklasberglund** [comment]
@uranusjr maybe using `brew cask info macdown` is even better. Want to avoid it, but maybe it's a somewhat good solution. Can't find any flag for listing only the binary. Not so happy about parsing output spanning several lines, since the format might change in the future.
```
$ brew cask info macdown
macdown: 0.6.4
http://macdown.uranusjr.com/
/opt/homebrew-cask/Caskroom/macdown/0.6.4 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/macdown.rb
==> Name
MacDown
==> Artifacts
MacDown.app (app)
/Applications/MacDown.app/Contents/SharedSupport/bin/macdown (binary)
```

@alexkaessner thanks! A _Terminal_ icon for a preferences view like in the first screenshot would be great.

**Comment by alexkaessner** [comment]
Good, I will look into this and upload the icon with the Touch Bar Icons ([#714](https://github.com/MacDownApp/macdown/issues/714)). 👍

**Comment by franklinyu** [comment]
@niklasberglund That has two issues:

1. Homebrew may not be even installed.
2. If Homebrew is installed in a custom location, you still need to load the `~/.*rc` to access Homebrew, so it doesn't seem to avoid anything convoluted.

<sub>I am not sure about loading `~/.*rc` because I am not sure what will happen if `~/.*rc` has side effect. When a user launch MacDown from terminal, the `~/.*rc` would be loaded twice. It seems no harm though, since sometimes we do need to `bash` in a `bash`, and a user should consider this case when he writes his `~/.*rc`.</sub>

**Comment by reitermarkus** [comment]
> @uranusjr maybe using `brew cask info` macdown is even better.

Homebrew-Cask maintainer here. If you're going to use `brew` to get the path, I'd suggest using `"$(brew --prefix)/bin/macdown"`.

**Comment by alexkaessner** [comment]
What about this Icon? I've slightly updated the other icons as well…

If they are okay, in which branch should I push it @uranusjr @franklinyu?

<img width="400" alt="design" src="https://cloud.githubusercontent.com/assets/6615076/21930109/94846576-d994-11e6-8809-90481c69dd22.png">

**Comment by uranusjr** [comment]
@alexkaessner Just push it in a new branch so @niklasberglund can `git fetch origin <branch>` to get it. :D

**Comment by alexkaessner** [comment]
**Pushed it to the [`shell-support`](https://github.com/MacDownApp/macdown/tree/shell-support) branch.** 👍 

I've changed the image type from "Universal" to "Mac", I hope this doesn't break things.

**Comment by niklasberglund** [comment]
@alexkaessner thanks! It looks really good in my opinion.

@franklinyu if homebrew isn't installed I think it'd be okay to not assume the `macdown` utility hasn't been installed by homebrew and check the location where MacDown might've installed it? If you mean the rare scenario of a user installing homebrew, installing MacDown using brew cask, then uninstalling homebrew.

@reitermarkus thanks. But if MacDown was installed in another directory it won't be found. Maybe casks can't be installed to custom location?

**Comment by reitermarkus** [comment]
Casks can be installed to a custom location by specifying `--appdir=`, but the `mdown` binary is always linked into `$(brew --prefix)/bin`.

**Comment by franklinyu** [comment]
@niklasberglund No, I mean the case where the user have never heard about Homebrew, and installed MacDown directly with the `.dmg` file.

**Comment by uranusjr** [comment]
I think it’s good enough to just default to `/usr/local/bin/macdown` if the user installs MacDown through DMG.

**Comment by niklasberglund** [comment]
The terminal preferences UI is looking like this now. Let me know if you see something that should be changed. I've implemented the functionality. Going to make some small modifications and more testing before creating a pull request.

<img width="472" alt="screen shot 2017-01-22 at 11 44 28" src="https://cloud.githubusercontent.com/assets/331986/22179879/aa590fc0-e09a-11e6-8502-6e290f651237.png">
<img width="472" alt="screen shot 2017-01-22 at 11 44 31" src="https://cloud.githubusercontent.com/assets/331986/22179881/abcd6086-e09a-11e6-8b39-9e48857b6159.png">

**Comment by uranusjr** [comment]
The italic font looks strange to me… Using monospace or putting the path in a text field might be better? Also **macdown** in the text could be made more pronounced.

**Comment by franklinyu** [comment]
If @niklasberglund find it weird to have `<Not installed>` in monospace, maybe the entire

> Location: *\<Not installed\>*

line can hide when the shell support is not installed.

**Comment by niklasberglund** [comment]
@uranusjr agree with you. Changed to monospace font(Monaco) for the path and for "macdown" in the description. The font change for "macdown" is quite discrete. Does it stick out enough?


<img width="472" alt="screen shot 2017-01-22 at 16 12 19" src="https://cloud.githubusercontent.com/assets/331986/22181032/b9b3fdf4-e0bd-11e6-80b3-6b5076793739.png">

**Comment by niklasberglund** [comment]
@franklinyu yea, or maybe it makes sense to make `<Not installed>` italic? The Install/Uninstall button is aligned with that label right now.

**Comment by uranusjr** [comment]
@niklasberglund Maybe making `macdown` bold? I’m not good at this either.

Both hiding the label completely (if we can make aligning work) and making `<Not installed>` italic makes sense to me.

**Comment by niklasberglund** [comment]
@uranusjr there's no bold variant for the Monaco font. Tried using _Courier_ and _Courier New_ bold variants but looks too much like typewriting. With no font family change but just bold it looks like this:

<img width="472" alt="screen shot 2017-01-22 at 17 47 14" src="https://cloud.githubusercontent.com/assets/331986/22181629/d4e008ea-e0ca-11e6-88dc-7778c33ba9a0.png">

**Comment by JanX2** [comment]
@niklasberglund Give the font Menlo a whirl. IMHO, it’s a better with with the rest of the UI.

**Comment by niklasberglund** [comment]
@JanX2 not bad. Menlo for paths below. Regular for "macdown" in the first, bold in the second.

<img width="472" alt="screen shot 2017-01-22 at 20 57 49" src="https://cloud.githubusercontent.com/assets/331986/22182649/8a5e9618-e0e5-11e6-94f4-9cbef29b7454.png">
<img width="472" alt="screen shot 2017-01-22 at 20 58 24" src="https://cloud.githubusercontent.com/assets/331986/22182648/8a5dfb5e-e0e5-11e6-89e1-79bf11e82efc.png">

**Comment by reitermarkus** [comment]
Where are the colors for the dot coming from? The red and green don't quite match the close/maximize buttons.

**Comment by niklasberglund** [comment]
@reitermarkus I chose these custom colors. Thought they somewhat fit the color theme. Maybe matching the colors of close/resize buttons is a good idea. Not sure as it's not really that similar functionality, but on the other hand one could say they're generic traffic light colors.

**Comment by niklasberglund** [comment]
#737 has been merged and this functionality is out in the just released pre-release.
