### ISSUE TITLE
Shell utility doesn't expand tilde

### ISSUE THREAD

**Issue by niklasberglund** [MacDownApp/macdown#727]
The shell utility `macdown` doesn't expand tilde `~`. So paths such as `~/file.md` doesn't work

**Comment by franklinyu** [comment]
It works for me… weird.

**Comment by uranusjr** [comment]
Hmm, yes it works for me too. It seems the shell does this automatically, so applications don’t really have to do this.

The case it doesn’t work is when you quote it:

```
$ macdown "~/Desktop/foo.md"
```

but observing what other CLI programs do, it seems we *should not* expand tilde in this case.

```
$ ls ~/Desktop
[output snipped]
$ ls "~/Desktop"
ls: ~/Desktop: No such file or directory
```

@niklasberglund Can you clarify how each case work for you?

**Comment by franklinyu** [comment]
Agree. If there is many space in the path, a user should type

```shell
macdown ~/'folder with spaces/file with spaces.md'
```

instead of

```shell
macdown '~/folder with spaces/file with spaces.md'
```

Even this may not work:

```shell
macdown ~'/folder with spaces/file with spaces.md'
```

because some shell only care about pattern `~/`.

**Comment by niklasberglund** [comment]
Ohh... You're right! I set up various paths as arguments in Xcode build scheme to try them out and found that tilde wasn't expanded. Probably Xcode wraps those argument in quotes, that's why it didn't work. And with this commit I made it work with quotes. So this should probably just be closed then if tilde in quotes isn't supposed to work.
