### ISSUE TITLE
Shell utility doesn't create file when it doesn't exist

### ISSUE THREAD

**Issue by niklasberglund** [MacDownApp/macdown#728]
If passing a non-existing file name to `macdown` it doesn't create the file.

**Comment by uranusjr** [comment]
This is a design decision—I opt not to create a file directly, but only open a new document, and set the filename when you actually save it. This is how CLI editors (e.g. vim, emacs) behave; you don’t get a blank file if you `vim foo` and end up not saving it (`:!q`). This makes a lot more sense to me than what some editors, e.g. Sublime Text, do.

**Comment by franklinyu** [comment]
@uranusjr In my machine Sublime Text does *not* create new file either, unless I manually save the file. The opened new file has state "modified".

**Comment by niklasberglund** [comment]
Alright sounds good. Created this issue and #727 for PR #729. Wanted to to these "fixes" before the UI work but turns out it's intended behaviour 😊  I'll close the PR.

**Comment by uranusjr** [comment]
@franklinyu Hmm, maybe I mistook it from another program, or they changed this in recent versions. But in any case this is the “correct” behaviour to me.
