### ISSUE TITLE
Ordered list items should not auto-increment

### ISSUE THREAD

**Issue by winstonford** [MacDownApp/macdown#731]
Hitting the return key after an ordered list item auto-increments the list item on the next line:

```
1. First list item
2. 
```

Instead, it should not auto-increment:

```
1. First list item
1. 
```

Keep the order list items re-orderable and leave the auto-incrementing to the preview.
This is a bug in every md editor I have tried.  Since Mac Down is the best of them all, seems only fitting that it be the first to fix. 

Cheers to a great app,
W

**Comment by uranusjr** [comment]
#702

**Comment by winstonford** [comment]
omg sorry for the trouble.  I just had my mind blown readin the 702 thread.  The confusion is fascinating.  The solution implemented.  Unclear as to why its even an option and set to flubber dub the champion that is the md ol feature!
