### ISSUE TITLE
Toggling between Editor and Markdown view minimises the other.

### ISSUE THREAD

**Issue by cschladetsch** [MacDownApp/macdown#739]
When Editing Text, pressing Shit-Command-H shows the markdown rendered version half and half with the text.

Now it goes full screen. Same for going to Edit mode from Mark down.

Please revert to older behaviour: when editing, and pressing Shift-Command-H, the screen is split between Edit and rendered Markdown.

**Comment by franklinyu** [comment]
Not quite sure whether I got it: <kbd>⇧</kbd> <kbd>⌘</kbd> <kbd>H</kbd> toggles between "editor only" mode and "editor and preview" mode. By "full screen" do you mean the window being maximized to occupy the entire screen, or one of the panels take the entire window?

**Comment by cschladetsch** [comment]
Hello,

Oh, I am very sorry. Perhaps the keys were rebound after I recently
updated. ⇧ ⌘ O does what I want. ⇧ ⌘ H toggles between full view-MD and
full-view rendered. Once it split the screen. Or, I thought it did...

Thanks for your rapid reply and a great product. ⇧ ⌘ O solves my problem.

Christian.
PS. Let me know if there's any low-hanging bugs I could help with. I love
the tool and have been a developer for 30 years.

**Comment by franklinyu** [comment]
Good to hear that your problem is solved. If you would like to contribute, I suggest looking into [issues labeled with "bug", ordered by number of comments](https://github.com/MacDownApp/macdown/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Acomments-desc). 😄

**Comment by franklinyu** [comment]
Note: Do you develop in latest Xcode? We plan to require Xcode 8 to develop (currently it's Xcode 7); leave comments in #737 if you are still using Xcode 7.
