### ISSUE TITLE
Scrolling code block in PDF not working

### ISSUE THREAD

**Issue by nightcoding** [MacDownApp/macdown#742]
Hi there,

when I'm creating a code block with longer lines so that the editor will render a horizontal scrollbar. If I'm exporting this to PDF, the block will be rendered including the scrollbar but the contents of the code block is not accessible. I have attached an image.

Used theme: github2
MacDown Version: 0.6.4 (786)
macOS Version: 10.11.6

![bildschirmfoto 2017-01-30 um 19 28 27](https://cloud.githubusercontent.com/assets/2564036/22435947/4d0ea24c-e722-11e6-8ca5-80a330c22042.png)

Is there any chance to deactivate the scrollbar?

**Comment by jayi** [comment]
I find a way to deactivate the scrollbar.

Add a new CSS of Prism that use `white-space: pre-wrap;` option in `<code>`  tag，and select this CSS in macdown.

```sh
cd  /Applications/MacDown.app/Contents/Resources/Prism/themes
sed 's/white-space:.*;/white-space: pre-wrap;/g' prism.css > prism-prewrap.css
```

Open macdown, open Preferences->Rendering, select Prewrap in Theme, then the scrollbar is deactivated.

If the "Syntax highlighted code block" option is not enabled, you should enable it or modify the main CSS file instead.

**Comment by pahoran** [comment]
I'm on MacDown Version 0.7.1 (870) - I don't see the option "Prewrap in Theme" in Preference -> Rendering.  Nor do I see the "Syntax highlighted code block" option...

What's happening to me is my longer lines in fenced code blocks are simply clipping when exporting into PDF.  I get a horizontal scroll bar in the preview pane, but exporting to PDF just clips the text, making the code block completely unusable.  How do I solve that issue?

![image](https://user-images.githubusercontent.com/16611613/29498867-4e14a37c-85d2-11e7-80ac-d0d76593a403.png)

![image](https://user-images.githubusercontent.com/16611613/29498854-310c45c8-85d2-11e7-8c77-299db214b41f.png)

**Comment by palkoc** [comment]
@pahoran When you create a new prism-prewrap.css, try to restart MacDown.
You should be able to see it in preferences:

![screen shot 2017-10-02 at 19 16 11](https://user-images.githubusercontent.com/6809559/31090018-6bf8b91e-a7a6-11e7-92eb-945e621464b8.png)
