### ISSUE TITLE
Disable period auto-insertion after two consecutive space key presses

### ISSUE THREAD

**Issue by akrueger** [MacDownApp/macdown#744]
Every time I hit `space` + `space` in succession (usually because I want to break to a new line), a period is auto-inserted. 

While this would be handy for certain markdown outputs (traditional writing), it's not great for the way I use it--programming readme files.

Is there a way to turn this auto-insertion off?

**Comment by franklinyu** [comment]
I didn't reproduce this issue. I suspect it is related to input method, or some system configuration. Did you try another editor?

**Comment by akrueger** [comment]
I haven't tried it with any other thick-client markdown-specific editor (Mou doesn't seem to work with Sierra), but I have no trouble with browser based markdown editors (Github, Bitbucket, dillinger.io) or more general text editors/IDEs: Sublime, Visual Studio Code, and Eclipse all behave normally when I'm writing markdown in them.

**Comment by franklinyu** [comment]
Oh that's weird. I assume you are on Sierra, so I suspect this is Sierra specific. I hope someone else with Sierra can help to verify this issue.

**Comment by akrueger** [comment]
Yep, `Sierra` `10.12.3 (16D32)`. I just bumped that from .2 however and it was present there as well. I'm not aware of any OS level settings I have changed to key inputs. Normally I have `Karabiner` installed, but Sierra broke that :/

**Comment by niklasberglund** [comment]
This is a Sierra feature which is disabled by default. Can be enabled/disabled in _System preferences_ => _Keyboard_ => _Text_ tab.
https://www.tekrevue.com/tip/macos-sierra-add-period-double-space/

**Comment by akrueger** [comment]
@niklasberglund That was it! Thanks

**Comment by rachitkinger** [comment]
True for Catalina as well 
> This is a Sierra feature which is disabled by default. Can be enabled/disabled in _System preferences_ => _Keyboard_ => _Text_ tab.
> https://www.tekrevue.com/tip/macos-sierra-add-period-double-space/
