### ISSUE TITLE
Modified image not updated in preview

### ISSUE THREAD

**Issue by niklasberglund** [MacDownApp/macdown#746]
1. Insert an image
2. Modify image in external program and save
3. Go back to MacDown. The image haven't changed.

Would be nice if the image could be automatically updated when coming back to MacDown. But the issue I observed is that even by:

4. Remove image's markdown
5. Insert image markdown again

Expecting step _5_ to trigger a reload of the image but the image is using a cached version so it's still not updated. **Sometimes** it will be updated after removing and inserting again, sometimes not. `⌘R` reloading the preview also doesn't help.

I'm thinking it's because of caching in the `WebView`

**Comment by niklasberglund** [comment]
I looked into this a bit. Haven't gotten it to work. What I've tried is:
* Disable caching globally by setting the application's `sharedURLCache` to an empty one (`NSURLCache *urlCache = [[NSURLCache alloc] initWithMemoryCapacity:0 diskCapacity:0 diskPath:nil];`)
* Implemented `WebResourceLoadDelegate` callback method to explicitly disable cache like so:

```
- (NSURLRequest *)webView:(WebView *)sender
                resource:(id)identifier
                willSendRequest:(NSURLRequest *)request
                redirectResponse:(NSURLResponse *)redirectResponse
                fromDataSource:(WebDataSource *)dataSource
{
    // Explicitly setting cache policy
    request = [NSURLRequest requestWithURL:[request URL]
                            cachePolicy:NSURLRequestReloadIgnoringLocalCacheData
                            timeoutInterval:[request timeoutInterval]];
    return request;
}
```

Haven't worked much with WebKit's `WebView` but cache handling with the old `UIWebView` is cumbersome and very limited in what you can do.

**Comment by uranusjr** [comment]
This is a pretty long-standing issue, and I think there is actually a duplicate somewhere. I also tried the second method a while ago (and it didn’t work, obviously). I’m thinking maybe the best way around this is to implement some kind of [cache busting](http://stackoverflow.com/questions/9692665) logic in the Markdown renderer.

**Comment by niklasberglund** [comment]
Good idea. But I think it won't work for local files? Gave it a shot anyway. I tried adding a per request unique GET parameter value for images in the `- (NSURLRequest *)webView:resource:willSendRequest:redirectResponse:fromDataSource:` callback without any luck. 

I then tried something really nasty just to see if it'd work. I prepended an incremental number of `/..` so a path would be something like `/../../../../../../Users/niklas/image.jpg`. Also not working. Maybe internally it all translates to the same path. Or maybe I'm poking around in the wrong place.

**Comment by uranusjr** [comment]
Paths are probably manipulated internally. This has been a problem with PDF exports—Safari would export files with absolute URLs, breaking links. I would have thought GET parameters would work… but maybe it just treats the `file://` protocol differently. :(

**Comment by uranusjr** [comment]
One thing I’m curious about: Would the “new” WebKit API (classes with `WK` prefix) solve this issue? It is only supported in 10.10+, but it has a `WKWebsiteDataStore` class with `-removeDataOfTypes:modifiedSince:completionHandler:` that looks like a solution. I didn’t find a similar method with the old API.

**Comment by niklasberglund** [comment]
Ah perhaps. That'd be a nice way to solve the issue.
Found a private API in WebKit which solves the issue - `[WebCache setDisabled:YES]`.
Since MacDown isn't in the app store is it somewhat okay to use private API?

Would it be a good idea to use it for now and then look into moving over to `WKWebView`?
Using `WKWebView` should be good either way. I could do the migration.

**Comment by niklasberglund** [comment]
`WKWebView` for 10.10+ and `WebView` for earlier for backwards compatibility?

**Comment by FranklinYu** [comment]
@niklasberglund FYI I’m planning to migrate to WKWebView in #1181.
