### ISSUE TITLE
Italic syntax parsing issue 

### ISSUE THREAD

**Issue by jianghuiyou** [MacDownApp/macdown#764]
I use Macdown 0.6.4 version  in my macbook pro Yosemite 10.10.5,  I know *word* is the Italic in markdown syntax, and Macdown has realized this. However, why _word_ will be parsed into Italic syntax, cause in **UNIX variable naming style** there will be more than one underscores in  one variable.
These variables are not in coding quote.The picture below show the example.

![example](http://oa576fej8.bkt.clouddn.com/macdown.png)

**Comment by niklasberglund** [comment]
In cases like this where you don't want the markdown to be parsed you'd have to escape the underscore, something like:
`call\_ip\_frag\_procs`

Does this solve your issue?

**Comment by jianghuiyou** [comment]
Oh, yeah ~it makes senses! Thanks for your timely solution.

**Comment by franklinyu** [comment]
In addition, `underscore_in_code_span` won't be rendered as italic, which makes more sense in your case.
