### ISSUE TITLE
Multi reference links render error

### ISSUE THREAD

**Issue by ZhiruiLi** [MacDownApp/macdown#765]
If I write these text: 

```markdown
test[^tag] hello world[^tag]

[^tag]: [Tag](localhost)
```

What I hope is two reference tags link to the same references, but the rendering result is:

```html
<p>test<sup id="fnref1"><a href="#fn1" rel="footnote">1</a></sup> hello world[^tag]</p>

<div class="footnotes">
<hr>
<ol>

<li id="fn1">
<p><a href="localhost">Tag</a>&nbsp;<a href="#fnref1" rev="footnote">&#8617;</a></p>
</li>

</ol>
</div>
```

only the first occurrence of the `[^tag]` is rendered as a reference link.

version: 0.6.5d56 (842)
platform: OSX 10.12.3

**Comment by franklinyu** [comment]
This is intended, because we want to link the end of the footnote back to the reference location. See hoedown/hoedown#92.

**Comment by ZhiruiLi** [comment]
Thanks a lot

**Comment by ZhiruiLi** [comment]
Thanks a lot
