### ISSUE TITLE
Smartypants not rendering double " as “ and ”

### ISSUE THREAD

**Issue by dajare** [MacDownApp/macdown#766]
As the subject line says: the double-quote mark is not getting rendered **but only when it is paired** ... which is most of the time (of course!). This should illustrate the issue:

[![sreenshot](http://i.imgur.com/FQpeyWA.png)][1]

Basically, as soon as you close a double quote, you lose the "curly quote" rendering. Single quotes are not affected.

Using: OSX Yosemite 10.10.5 early 2015; MacDown Version 0.6.5d56 (842).

---

**Update** - I just noticed that using paired double-quote marks in `#` headings of any level removes the heading rendering for the `"words in quotes"` only. Weird -- but might suggest some further weirdness about the parsing of `"`.

Or is it possible it is related to bug #318 (which is now fixed, I think)?

[1]: http://i.imgur.com/FQpeyWA.png "Click for larger image"

**Comment by franklinyu** [comment]
I assume this is what you tried (note that "Render newline literally" should be on, to get what you see):

```markdown
Quote "unclosed &larr; double quote!

Quote "closed with
&emsp; linebreak" :( not curly

Quote "closed" :( not curly

This---is 'good' (em-dash + single-quotes)!
```

There are actually more than one case, so let's discuss them separately. In this case

```markdown
Quote "unclosed &larr; double quote!

Quote "closed with
&emsp; linebreak" :( not curly
```

MacDown rendered second quote as straight one, last as curly (closing) one, which makes sense to me.

**Comment by dajare** [comment]
The point is that cases 2 and 3 are behaving the same -- badly! The double quote mark should be properly rendered in both those cases. Here's how they look on the [Markdown Dingus][mdd] using "Both" Markdown + Smartypants:

[mdd]: https://daringfireball.net/projects/markdown/dingus

[![screenshot](http://i.imgur.com/zRqK3XYl.png)][1]

(And note how the `&#8220;` and `&#8221;` entities are used, rather than `<q>`, but that's a different matter.) Something in MacDown's double-quote recognition is borked, it seems. I'm not sure which implementation/flavour is being used, but it sure looks like a bug to me!

And just to fill out the picture, this is how the behaviour of double-quote marks works in headers:

[![Imgur](http://i.imgur.com/Pah2Nxl.png)][2]

Again, I wonder if this is related to an overly aggressive fix for bug #318 as noted above. It seems possible, anyway.

[1]: http://i.imgur.com/zRqK3XY.png "Click for larger image"
[2]: http://i.imgur.com/Pah2Nxl.png "Click for larger image"

**Comment by franklinyu** [comment]
> The point is that cases 2 and 3 are behaving the same -- badly!

Hold on, what's case 2 and 3?

By the way, if source code as well as screenshots is provided, we can reproduce the issue more easily.

**Comment by dajare** [comment]
> By the way, if source code as well as screenshots is provided, we can reproduce the issue more easily.

Yes, of course - I'm sorry! I should have thought of that.

> Hold on, what's case 2 and 3?

I meant the 2nd and 3rd "lines" of my first example, so re-doing them:

```
(1) Quote "unclosed &larr; double quote!

(2) Quote "closed with
&emsp; linebreak" :( not curly

(3) Quote "closed" :( not curly

(4) This---is 'good' (em-dash + single-quotes)!
```
In the examples above ## 2 and 3 should both have curly-quote rendering, like in the Markdown Dingus example (my second screenshot, above).

The only problematic example in my last screenshot of "headings" is the last one:

    ## Open "and" Closer

in which `"and"` is incorrectly rendered.

I hope that's more clear now! And thanks for engaging with this issue.

**Comment by franklinyu** [comment]
A new document with

```markdown
## Open "and" Closer

Nothing weird.
```

gives me

![screenshot 2017-03-05 pm 9 14 02](https://cloud.githubusercontent.com/assets/3153452/23594563/f658c054-01e8-11e7-9c5a-5b10be315ab3.png)

**Comment by dajare** [comment]
Right, I looked at this with a friend (HT: @caorongjin), and you could think of it as "user error". More specifically, I had the "Quote" option checked under "Inline formatting" along with "Smartypants":

![options](http://i.imgur.com/LoB7wl7.png)

Clearing that checkbox gives me the behaviour I was expecting:

[![fix-version](http://i.imgur.com/j0wxb91.png)][1]

[1]: http://i.imgur.com/j0wxb91.png "Click for larger version"

It seems `(2)` still doesn't behave as "canonical" Markdown+Smartypants, but this clearly explains the issue I was having. (I'm still wondering why MacDown uses `<q>` rather than the `&#8220;` and `&#8221;` entities ... but that's a different matter!)

**Comment by franklinyu** [comment]
MacDown uses `<q>` when you enable "Quote", as you mentioned in the screenshot.

MacDown behaviors differently from the canonical implementation because behavior in such situation is not even specified in the official website. I don't know whether John Gruber really meant it. From what I see, John Gruber's implementation chooses shortest possible pair, while MacDown chooses longest. In contrast, emphasis (`<em>`) is clearly specified in CommonMark.
