### ISSUE TITLE
Button to change base font is hidden if it was set too big

### ISSUE THREAD

**Issue by Zhengquan** [MacDownApp/macdown#768]
The base font of editor tab can't be changed if the base font was set too big. The button to `change` the base font will be hidden somewhere no matter how I tried to resize the window:

![image](https://cloud.githubusercontent.com/assets/251222/23661136/b57ebd64-0386-11e7-9b65-24e4eedf5d26.png)

Does anyone know how to reset the configuration?

**Comment by franklinyu** [comment]
The preference of MacDown is saved in these two files:

```shell
$HOME/Library/Preferences/com.uranusjr.macdown.plist
$HOME/Library/Preferences/com.uranusjr.macdown.LSSharedFileList.plist
```

**Comment by uranusjr** [comment]
For reference, the following command can modify the font size directly with resetting everything:

```bash
defaults write com.uranusjr.macdown editorBaseFontInfo -dict-add size 14
```

Replace `14` with any font size you think appropriate.
