### ISSUE TITLE
Don't require mouse on export to html or pdf in overwrite dialog

### ISSUE THREAD

**Issue by jimk-xcira** [MacDownApp/macdown#769]
Please allow the tab key to change the selection from "Cancel" to "Replace" in the modal save dialog when overwriting a file for export.  I hate reaching for the mouse when tab is quickly typed.

Thank you.

**Comment by franklinyu** [comment]
You don't have to. "Cancel" is the default button, but "Replace" is highlighted. You hit <kbd>Enter ↵</kbd> to cancel, or <kbd>Space</kbd> to replace.

**Comment by jimk-xcira** [comment]
Wow!  That’s great, thank you very much.

**Comment by franklinyu** [comment]
Glad that it works for you. Re-open this issue if you have further problem or question. 😄

**Comment by jimk-xcira** [comment]
Sorry, I was overly optimistic.

I tried, but it didn’t work for me.

**Comment by jimk-xcira** [comment]
Let me add some more detail.

I have a document that I want to export to .html, but I have a previous version.

Enter Option-Command-E

Save dialog is presented with Save highlighted




Press the enter/return key and I get:



Notice that Cancel is highlighted, not Replace.

Hope this helps, and I apologize for the previous lack of detail.

Jim

**Comment by niklasberglund** [comment]
If I'm not mistaken this dialog is from macOS. I don't know of any way to toggle between the buttons in these dialogs. What @franklinyu suggested would be awesome but it doesn't work for me either.

**Comment by franklinyu** [comment]
That's weird, it still works for me in that case. When I hit <kbd>⌥ Option</kbd> <kbd>⌘ Command</kbd> <kbd>E</kbd> I get a drop-down notification box asking for filename, tag, and location. After I hit "Save" (or alternatively <kbd>↵ Return</kbd>), a new drop-down box telling the duplication covers the previous one. The new box has two buttons, "Cancel" as default button (blue background), and "Replace" as activated (glowing in blue) button. Anything different from your system? (I mean both of you.)

Note the difference between an activated button and a default one. This is how a button is activated:

![activate](https://i.stack.imgur.com/4avgK.png)

Sorry if the term "highlight" confused you.

**Comment by niklasberglund** [comment]
@franklinyu is that a screenshot of the OS X you're on? I'm on macOS Sierra.

For me the same dialog looks like this:
![image](https://cloud.githubusercontent.com/assets/331986/23726692/7b9eab52-0455-11e7-9e55-9b7979295e53.png)

**Comment by franklinyu** [comment]
@niklasberglund You may want to check out [this answer](http://apple.stackexchange.com/questions/7263/how-can-i-activate-buttons-with-just-the-keyboard#7269).

**Comment by jimk-xcira** [comment]
Typing command-r (command with first letter) toggles to the non-selected button with a “button-up” event which solves the issue for me.

On Mar 8, 2017, at 18:16, Franklin Yu <notifications@github.com<mailto:notifications@github.com>> wrote:


@niklasberglund<https://github.com/niklasberglund> You may want to check out this answer<http://apple.stackexchange.com/questions/7263/how-can-i-activate-buttons-with-just-the-keyboard#7269>.
