### ISSUE TITLE
How can I ignore  a pair of double underscore in macdown

### ISSUE THREAD

**Issue by firelyu** [MacDownApp/macdown#775]
I want to ignore underscore in macdown. 

I can ignore a pair of single underscore with `Preferences->Markdown->Inline formatting -> Intra-word emphasis`.

<img width="411" alt="2017-03-23 11 53 53" src="https://cloud.githubusercontent.com/assets/1694674/24231440/aad4b3f6-0fbf-11e7-8061-4479d5820796.png">

But I can't ignore a pair of double underscore.

<img width="717" alt="2017-03-23 11 57 30" src="https://cloud.githubusercontent.com/assets/1694674/24231509/ff0f0d72-0fbf-11e7-88aa-d172b596e9da.png">

**Comment by uranusjr** [comment]
You can use backslashes to escape any character like this: `\_\_init\_\_`. But for this particular situation you should use code constructs:

```markdown

## Magic method

* `__init__(self, ...)`
* `__del__(self)`
* `__len__(self)`
* `__getitem__(self, key)`
* `__setitem__(self, key, value)`
* `__delitem__(self, key)`

```
