### ISSUE TITLE
No ToC in PDF export

### ISSUE THREAD

**Issue by Hipska** [MacDownApp/macdown#782]
The exported PDF should have a table of contents based on the markdown headings.

**Comment by franklinyu** [comment]
Just to clarify, did you mean a table of contents as *bookmarks* in the generated PDF like this:

![bookmarks](https://blogs.adobe.com/acrolaw/files/acrolaw/01_bookmark_panel.gif)

**Comment by Hipska** [comment]
Yes, in _MacOS Preview_ it is called "Table of Contents".

**Comment by franklinyu** [comment]
I said so because you can get a "table of contents" within the page with `[TOC]` token if you enable that. I wanted to make sure that, instead of the in-page table of content, you meant the one embedded in PDF formats.

I'm not sure whether this is possible within Cocoa framework, but this feature looks nice to me.

**Comment by uranusjr** [comment]
> I'm not sure whether this is possible within Cocoa framework.

Somebody mentioned this before and I did some research. The answer is no.

**Comment by franklinyu** [comment]
>> I'm not sure whether this is possible within Cocoa framework.
>
>Somebody mentioned this before and I did some research. The answer is no.

Sad. Then I'm closing this until anyone has found any way to do that. I guess Apple is just not that interested in the "generate PDF from documents" feature.

**Comment by Hipska** [comment]
Erm, why closing this? Someone else might want to pick it up and implement it?

And also, a lot of other applications from Apple (Pages), but also other vendors do export PDF with a correct ToC included, so I don't think it's impossible.

**Comment by niklasberglund** [comment]
@Hipska MacDown currently have 290 open issues. Personally I think closing issues like this one is a good idea. @uranusjr already did research and didn't find any way to do it with the Cocoa framework. If anyone find information about this being possible with Cocoa then that's great news and the issue will probably be reopened.

**Comment by franklinyu** [comment]
@Hipska I'm not sure how Pages does it (since it's closed-source), but I doubt that it does so with public API from `NSDocument` (or even `NSDocument` at all). Is there any example of "other vendors" doing so, that we can look into?

Take it easy, we can re-open this issue if we find it possible to do so (without totally rewriting the code base, of course).

**Comment by uranusjr** [comment]
There is actually a series classes and functions lying inside the macOS API that can be used to generate arbitrary PDF content. WebKit’s printing to PDF is based on it, iWorks likely use it, and NSDocument as well. IIRC those are not completely undocumented, but are *under*-documented and very low level (like drawing directly onto the canvas), and to use it you not only need to familiarise yourself with those (again, under-documented) APIs but also the WebKit API, which is also very difficult.

Alternatives exist (PDF is an open format, after all), but most I found have been commercial solutions. Adobe PDF Library SDK is obviously the most prominent one, but it would be difficult to integrate it into either NSDocument or WebKit. Another solution would be [wkhtmltox](https://wkhtmltopdf.org), but it’s GPL, and incompatible to MacDown’s license (MIT).

**Comment by Hipska** [comment]
Next to wkhtmltox, I also found [Pandoc](http://pandoc.org), which outputs to many formats. But that one seems GPL too.
