### ISSUE TITLE
Maths mode not working?

### ISSUE THREAD

**Issue by AlastairHeffernan** [MacDownApp/macdown#784]
Hi,

I absolutely love your app: beautiful design and so easy to put together reports for my supervisor. Preview is a superb feature.

My question: is the $$ x=y $$ maths mode working at the moment? I tried to put in some latex-style maths like this and it just displays it as raw text "$$ x=y $$" in both the preview and the exported html. Am I doing something wrong - my example was just to open a blank MacDown document and write $$ x=y$$ and see what happened. 

Thanks

**Comment by franklinyu** [comment]
Please re-open if this doesn't help: Preferences -> Rendering -> TeX-like math syntax

**Comment by AlastairHeffernan** [comment]
Great. The tick-box was disabled. Thanks for getting back to me so fast.
