### ISSUE TITLE
Mermaid syntax support

### ISSUE THREAD

**Issue by alu0100892833** [MacDownApp/macdown#785]
I was wondering if there was any way to integrate [mermaid](https://knsv.github.io/mermaid/#mermaid) support on MacDown. I´m a student and it would really make a difference for me to be able to draw trees and graphs on the fly while taking notes in class.

**Comment by franklinyu** [comment]
Or just continue the work in #625?

**Comment by FranklinYu** [comment]
Should be closed by #865. Please comment if you think otherwise.
