### ISSUE TITLE
Remove MathJax CDN reference

### ISSUE THREAD

**Issue by uranusjr** [MacDownApp/macdown#789]
We currently use cdn.mathjax.org to provide math functionality. But [they are shutting down their CDN at the end of April](https://www.mathjax.org/cdn-shutting-down/). We need to either switch to another CDN (CDNJS is a reasonable choice, but still not future-proof), or bundle the whole thing locally (will bloat the distribution considerably).

**Comment by franklinyu** [comment]
I vote for CDNJS.

**Comment by daviewales** [comment]
I vote for bundling locally.
I live in a place with no internet, and I would love to be able to use mathjax offline.

**Comment by franklinyu** [comment]
So the current implementation already troubles @daviewales? We should have started this discussion earlier?

**Comment by daviewales** [comment]
I only discovered MacDown today, but it looks really good.
However, I was disappointed to see in the preferences that Math support requires an internet connection.

Although, testing it just now by typing maths with internet, then disconnecting internet and restarting MacDown, the math support continued to work.

Do you cache the mathjax components offline after initially downloading them?

**Comment by niklasberglund** [comment]
What if MathJax support was downloaded and installed similarly to how the terminal utility is installed -  by an install/uninstall button in the preferences

**Comment by daviewales** [comment]
@niklasberglund That would be good. So long as I can download it when I have internet, then know that it will keep working without internet I'm happy.

**Comment by franklinyu** [comment]
I think the `WebView` automatically does that; duration depends on server policy. For example, the CDNJS server tells browser to expire the resource in a year.

**Comment by uranusjr** [comment]
I’m moving the downloadable MathJax distribution to another issue. This will be closed as the mathjax.org reference is removed.
