### ISSUE TITLE
Max font size cannot be reverted

### ISSUE THREAD

**Issue by natalia-osa** [MacDownApp/macdown#790]
If you increase the font size to the maximum, the size of the preferences/font window does increase. Unfortunately the view with font size is constraint too far up, and as a result, the font cannot be changed back to normal.
Removing and reinstalling the app does not help, as these settings must be set up somewhere aside and config file is not removed during installation.

![screen shot 2017-04-17 at 13 08 33](https://cloud.githubusercontent.com/assets/1477880/25087436/32a28fe8-236f-11e7-97e5-0b0579bc16cf.png)

**Comment by uranusjr** [comment]
This is mentioned in #768. macOS persists preferences seperate from the application, so reinstalling does not help. You can remove the two files mentioned in that issue to reset preferences, or edit the property with the following command:

```bash
defaults write com.uranusjr.macdown editorBaseFontInfo -dict-add size 14
```

Replace `14` with any font size you think appropriate.

**Comment by natalia-osa** [comment]
I understand that reinstalling does not help because preferences are in separate place. Thank you for mentioning the other thread and workaround. Reinstalling etc was just a "first try fix" for a bug, which is stretching the field too much, what is causing "Change" button never to appear (out of bounds). It would be probably good to fix that layout.
