### ISSUE TITLE
Exported PDFs don't include a table of contents

### ISSUE THREAD

**Issue by manuelciosici** [MacDownApp/macdown#792]
By its nature, MarkDown includes semantic annotations for document structure (i.e. headings). The exported PDFs should include a PDF table of contents.

To be clear, I am not talking here about a page containing a table of contents, but I am talking about having a table of contents directly in the PDF file that PDF readers can utilize to allow users to jump directly to specific sections of a document.

**Comment by franklinyu** [comment]
Duplicate of #782.

**Comment by Hipska** [comment]
You see, that's why I suggested to keep 1 issue about ToC open, so nobody will create new ones again ;-)
