### ISSUE TITLE
How to add new syntax highlighting themes for code blocks?

### ISSUE THREAD

**Issue by adelredjimmy** [MacDownApp/macdown#794]
(I'm not referring to the MacDown editor syntax highlight) on top of the Prism default themes offered.

**Comment by franklinyu** [comment]
Rendering -> Syntax highlighted code block -> Theme

**Comment by franklinyu** [comment]
About the new question, just drop your own theme in the Themes folder. The folder is accessible by "Rendering -> CSS -> Reveal (button)".

Note: Changing the title or contents won't notify other participants; reply is the better approach to add information or raise further questions.

**Comment by brandondurham** [comment]
I have the same question. I’d like to add a new *Syntax highlighting* theme that doesn’t currently exist in the “Theme” select menu. I see themes like _Coy, Dark, Funky, Okaidia, etc._ in the menu, but I can’t find those theme files anywhere.

How do you go about adding a new Syntax highlighting theme?

**Comment by franklinyu** [comment]
@brandondurham All Prism related stuff are in [`Dependency` folder](https://github.com/MacDownApp/macdown/tree/master/Dependency). Prism is a Git submodule there.

And there is no response from @adelredjimmy so I'm closing this issue. Feel free to add more comments.

**Comment by brandondurham** [comment]
Thanks so much, @franklinyu!

**Comment by marc-medley** [comment]
As FYI, in my case, edits to a copy of the "default" `prism.css` in the MacDown v0.8.0 application Prism resources on macOS Sequoia 15.3 works OK. The `prism-mydefault.css` shows up as `Mydefault` in the MacDown preferences panel.

``` sh
cd /Applications/MacDown.app/Contents/Resources/Prism/themes

ls

# prism-coy.css     prism-okaidia.css          prism-twilight.css
# prism-dark.css    prism-solarizedlight.css   prism.css
# prism-funky.css   prism-tomorrow.css

cp prism.css prism-mydefault.css

#edit prism-mydefault.css
#nano prism-mydefault.css
open .  ### edit prism-mydefault.css with some plain text code editor
```
