### ISSUE TITLE
Changes are saved to file, without manual save

### ISSUE THREAD

**Issue by DagW** [MacDownApp/macdown#795]
Opening a file triggers a direct write to the opened file.
Changing text and exiting MacDown causes the changes to be saved to the file.

I noticed this by using macdown as an editor for an scp application. It registered a change just after the file was opened and so on.
I double checked by adding a python file watcher to the file.

Love the app, thanks!

**Comment by franklinyu** [comment]
Could you provide more details about "changing text and exiting MacDown"? Was there any confirmation about whether to save the file before you exit MacDown?

**Comment by DagW** [comment]
Sure
When the file is open, I remove three characters with backspace, press the red close button on the titlebar.
The file is detected as changed and uploads.

No confirmation dialog.

**Comment by franklinyu** [comment]
After you remove three characters with backspace, and before you press the red close button, did you notice whether there's a dot in the button? And whether there is "- Edited" in the title?

**Comment by DagW** [comment]
No dot, said "Edited" in the title.

The system preference did the trick for editing and closing. Now it asks if I want to save or revert when exiting. Then this might not be an issue after all. Thanks for your time.
