### ISSUE TITLE
no space after '##' renders in macdown, but not on github

### ISSUE THREAD

**Issue by davecampbell** [MacDownApp/macdown#799]
interesting - i may be able to demonstrate right here in this comment.

in macdown, when i use a "##" followed directly by some characters, it is interpreted as an H2.

but when that same text is viewed directly in github, it is not.  github markdown seems to require a space after the "##".

##here is an example.

<img width="1048" alt="captures- 2017-05-05 at 3 16 38 pm" src="https://cloud.githubusercontent.com/assets/584933/25760702/ff286526-31a5-11e7-8511-e8b0f570a602.png">

**Comment by uranusjr** [comment]
#791
