### ISSUE TITLE
regular crashes, including after update

### ISSUE THREAD

**Issue by chipbrock** [MacDownApp/macdown#806]
Hi
I like MacDown a lot. But I have regular crashes on two computers in the editor. I *think* when I delete a number of characters and when I paste text into the editor. There's no way out except to force-quit. 

Any ideas? Pretty standard editing stuff so I don't think I"m doing anything exotic or abusive!

thanks for your work 

Ray Brock

**Comment by franklinyu** [comment]
Did it crash and suddenly quit itself, or it hangs? If latter, I think I'm merging this issue with #807 (closing this one because #807 has a better title).

**Comment by chipbrock** [comment]
It hangs and I have to force quit.
