### ISSUE TITLE
install with home brew fail

### ISSUE THREAD

**Issue by marshalys** [MacDownApp/macdown#809]
➜  Homebrew git:(stable) brew cask install macdown
==> Downloading https://github.com/MacDownApp/macdown/releases/download/v0.7.1/MacDown.app.zip
######################################################################## 100.0%
==> Verifying checksum for Cask macdown
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 9856d701739fab66b75aa52c98ba54d93eb10de765f63ffe149e666e6e035578
Actual: 4b26fb70b399cd998f226a78f81cd74348da19a8953aca80169fd7d00667496c
File: /Users/mars/Library/Caches/Homebrew/Cask/macdown--0.7.1.zip
To retry an incomplete download, remove the file above.

**Comment by uranusjr** [comment]
Arrgh this is probably because I used the same 0.7.1 for #805. I don’t maintain the cask, and why the cask maintainer uses pinned versioning instead of `latest` I have no idea. In any case this should be filed to Homebrew Cask’s issue tracker instead.

**Comment by franklinyu** [comment]
@marshalys You may want to vote for caskroom/homebrew-cask#34171.

**Comment by marshalys** [comment]
👌 thx
