### ISSUE TITLE
Menu in chinese

### ISSUE THREAD

**Issue by arnaudmiribel** [MacDownApp/macdown#814]
Since the last update of MacDown (v0.7), some of the menu tasks were turned in Chinese...
Don't know how to change this. 

Happened to someone else ?

<img width="747" alt="capture d ecran 2017-05-17 a 11 28 34" src="https://cloud.githubusercontent.com/assets/7164864/26147627/6afe5af6-3af4-11e7-9cc1-7be293b1b9ce.png">

**Comment by franklinyu** [comment]
Yes, from the [release page](https://github.com/MacDownApp/macdown/releases/tag/v0.7):

> MacDown now has i18n! Thanks to all people giving feedback on this issue, and all our contributors on Transifex. Visit our project page if you would like to help translating MacDown to your language:
>
> https://www.transifex.com/macdown/macdown/

Isn't this desired?

**Comment by arnaudmiribel** [comment]
Oh thanks for the link. Well because my version was in English before, and it seems to be the source language, I would expect it to have remained English. (and I can't find the way to do this, because commands are in 中文！）我學了中文可是我不什麼都懂！謝謝

**Comment by uranusjr** [comment]
Hi, the detection follows your system language, and this is expected if you put *Chinese, Traditional* before all other supported languages, including English. You can drag any English entry before the *Chinese, Traditional* one in System Preferences → Languages & Region panel to use the English interface.

Another way to override this if you really don’t want to mess with System Preferences is with [App Language Chooser](https://itunes.apple.com/tw/app/app-language-chooser/id451732904?l=zh&mt=12). The usage should be pretty straightforward.

**Comment by uranusjr** [comment]
(Closing since this is not really a bug. Feel free to continue the discussion if you can’t make it work.)

**Comment by arnaudmiribel** [comment]
> this is expected if you put Chinese, Traditional before all other supported languages, including English

Thank you very much, that was indeed the problem. 

Problem solved!
