### ISSUE TITLE
How to switch panels?

### ISSUE THREAD

**Issue by IvanShamatov** [MacDownApp/macdown#816]
Hi,
I looked through all preferences and menu tabs but could not find how to switch panels.
<img width="1347" alt="2017-06-02 6 37 42" src="https://cloud.githubusercontent.com/assets/160239/26709798/0c93d812-475e-11e7-9a2b-cc76dad7389b.png">
It's little bit wierd to write on right panel to see result on the left.
Though even on website preview panel is on the right
![](https://macdown.uranusjr.com/static/images/macdown-demo.png)

I would be really appreciate if you can help me with that.

**Comment by IvanShamatov** [comment]
Disclaimer: I'm not os X developer at all, so my decision can make no sense. 
I'm looking at MPDocument.xib and it looks like editor should be on the left.

**Comment by IvanShamatov** [comment]
I'm looking at MPDocumentSplitView.m and swapViews method looks like what switches views

**Comment by IvanShamatov** [comment]
Ok I found some settings string
```
    if (!changedKey || [changedKey isEqualToString:@"editorOnRight"])
```
going this way

**Comment by franklinyu** [comment]
Preference -> General -> Editor on the right

**Comment by IvanShamatov** [comment]
Ok, I found it, it's in `Put editor on the right` menu of general, and it helped me.
![2017-06-02 7 03 15](https://cloud.githubusercontent.com/assets/160239/26710348/d246ce90-4761-11e7-99de-e2d1fd28876c.png)

**Comment by franklinyu** [comment]
Come on, it *is* in the preference…

**Comment by IvanShamatov** [comment]
@franklinyu Thanks for response, I've just updated this page.
