### ISSUE TITLE
Add option to disable autosave

### ISSUE THREAD

**Issue by ffxsam** [MacDownApp/macdown#821]
Could you please add a way for us to disable autosave? Thanks!

**Comment by franklinyu** [comment]
Check your macOS system preference: General => Ask to keep changes when closing documents.

**Comment by ffxsam** [comment]
Got it. Strange though.. because that option is system-wide, and has to do with prompting the user to keep changes when closing documents. And what MacDown is doing is auto-saving as soon as the user stops typing, which is something quite different. I would still recommend an option in-app to enable/disable that.

**Comment by franklinyu** [comment]
That behavior is expected and consistent with other applications like TextEdit.

I would say the description “Ask to keep changes when closing documents” is pretty misleading though. That option actually means “automatically save the document”.

**Comment by ffxsam** [comment]
Roger that. thanks!
