### ISSUE TITLE
Translate MacDownApp to Brazilian Portuguese (pt_BR)

### ISSUE THREAD

**Issue by ronisbr** [MacDownApp/macdown#832]
Hi @uranusjr ,

First of all, congratulations for MacDown, it is an amazing app!

I would like to translate it to Brazilian Portuguese (pt_BR). I have requested the new language in Transifex, but I have never used the system so I don't know if I did everything right. If you accept it, I will be glad to translate MacDown to pt_BR.

Cheers,
Ronan

**Comment by ronisbr** [comment]
@uranusjr ,

Hi! I am seeing the pt_BR language in Transifex, but I am not able to do anything. Am I doing something wrong?

**Comment by uranusjr** [comment]
I think you can now. Transifex requires me to manually accept every join requests. I do this when I can, which is unfortunately not very often…

**Comment by ronisbr** [comment]
Thanks @uranusjr !

Actually, I finished the translation to pt_BR, as you can see in Transifex. I build a local MacDown with the translation and everything seems to be fine. I only found two minor bugs that were reported here: #836 and #837 .

By the way, congratulations for MacDown, it is an amazing app.
