### ISSUE TITLE
Message box string is not being translated

### ISSUE THREAD

**Issue by ronisbr** [MacDownApp/macdown#836]
Hi guys,

There is a string (maybe more) in message box that was not translated by the file from Transifex:

<img width="557" alt="captura de tela 2017-08-05 as 16 52 18" src="https://user-images.githubusercontent.com/1068295/28998342-8cc31246-79fe-11e7-94a5-6eddadb2bbe8.png">

I checked and it is included in .strings file in my build, but the text is not being translated.

**Comment by uranusjr** [comment]
It seems import utility has some issues with strings with escape characters 😞 This is the case of [two strings in MPDocument.m](https://github.com/MacDownApp/macdown/blob/master/MacDown/Code/Document/MPDocument.m#L1667); the export tool erroneously keeps the linebreaks, and therefore fails to match the real source string at runtime. I’ll need to think of a way to work around this bug.

**Comment by ronisbr** [comment]
Hi @uranusjr 

One question, in the `master`, something is wrong with pt_BR translation. Many things are not translated. Is it expected? Look for example the sub-menu and the main menu here:

<img width="960" alt="captura de tela 2017-08-06 as 14 02 16" src="https://user-images.githubusercontent.com/1068295/29005352-ea513594-7aaf-11e7-9255-ab530d553dd0.png">

It works if I manually import the XLIFF file from Transifex.

**Comment by ronisbr** [comment]
Yeah, something weird happened. For example, look at the file `macdown/MacDown/Localization/pt-BR.lproj/MainMenu.strings`. It is in English, but it is fully translated in Transifex.

**Comment by uranusjr** [comment]
I just synced the translations again, could you check for me if the entries are correct now? I can’t read most of the languages myself (only Chinese, which is far from complete), and if one language is working I think it’s safe to assume others are as well.

**Comment by ronisbr** [comment]
Hi @uranusjr 

Thanks, things got better but there are still non-translated string. I tracked down and every string translated in this file is not being used https://github.com/MacDownApp/macdown/blob/master/MacDown/Localization/pt-BR.lproj/Localizable.strings

Here is the diff that I obtain when I manually import the XLIFF file, which fixes everything:

```diff
diff --git a/MacDown.xcodeproj/project.pbxproj b/MacDown.xcodeproj/project.pbxproj
index 7931a4b..1fca60b 100644
--- a/MacDown.xcodeproj/project.pbxproj
+++ b/MacDown.xcodeproj/project.pbxproj
@@ -422,6 +422,9 @@
                7A8EA75FA95818275755F0B6 /* Pods-macdown-cmd.release.xcconfig */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = text.xcconfig; name = "Pods-macdown-cmd.release.xcconfig"; path = "Pods/Target Support Files/Pods-macdown-cmd/Pods-macdown-cmd.release.xcconfig"; sourceTree = "<group>"; };
                852D52391E260A6400BA7162 /* MPTerminalPreferencesViewController.h */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.h; path = MPTerminalPreferencesViewController.h; sourceTree = "<group>"; };
                852D523A1E260A6400BA7162 /* MPTerminalPreferencesViewController.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = MPTerminalPreferencesViewController.m; sourceTree = "<group>"; };
+               8AF09B891F3796E7005ABD0D /* pt-BR */ = {isa = PBXFileReference; lastKnownFileType = text.plist.strings; name = "pt-BR"; path = "Localization/pt-BR.lproj/Localizable.strings"; sourceTree = "<group>"; };
+               8AF09B8A1F3796E7005ABD0D /* pt-BR */ = {isa = PBXFileReference; lastKnownFileType = text.plist.strings; name = "pt-BR"; path = "Localization/pt-BR.lproj/InfoPlist.strings"; sourceTree = "<group>"; };
+               8AF09B8B1F3796E7005ABD0D /* pt-BR */ = {isa = PBXFileReference; lastKnownFileType = text.plist.strings; name = "pt-BR"; path = "pt-BR.lproj/InfoPlist.strings"; sourceTree = "<group>"; };
                8CDC5EA0050D2F722FB1AADD /* Pods-MacDownTests.debug.xcconfig */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = text.xcconfig; name = "Pods-MacDownTests.debug.xcconfig"; path = "Pods/Target Support Files/Pods-MacDownTests/Pods-MacDownTests.debug.xcconfig"; sourceTree = "<group>"; };
                905EF1A7196164CA00FC3CE9 /* macdown */ = {isa = PBXFileReference; explicitFileType = "compiled.mach-o.executable"; includeInIndex = 0; path = macdown; sourceTree = BUILT_PRODUCTS_DIR; };
                905EF1A8196164CA00FC3CE9 /* Foundation.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = Foundation.framework; path = System/Library/Frameworks/Foundation.framework; sourceTree = SDKROOT; };
@@ -1353,6 +1356,7 @@
                                1F9034361EC556EC00D97F9C /* ja */,
                                1F9034411EC556F300D97F9C /* sk */,
                                1F90344C1EC5576E00D97F9C /* ar */,
+                               8AF09B8A1F3796E7005ABD0D /* pt-BR */,
                        );
                        name = InfoPlist.strings;
                        sourceTree = "<group>";
@@ -1370,6 +1374,7 @@
                                1F9034371EC556EC00D97F9C /* ja */,
                                1F9034421EC556F300D97F9C /* sk */,
                                1F90344D1EC5576E00D97F9C /* ar */,
+                               8AF09B891F3796E7005ABD0D /* pt-BR */,
                        );
                        name = Localizable.strings;
                        sourceTree = "<group>";
@@ -1452,6 +1457,7 @@
                                1F9034381EC556EC00D97F9C /* ja */,
                                1F9034431EC556F300D97F9C /* sk */,
                                1F90344E1EC5576E00D97F9C /* ar */,
+                               8AF09B8B1F3796E7005ABD0D /* pt-BR */,
                        );
                        name = InfoPlist.strings;
                        sourceTree = "<group>";
```

Would you like me to create a PR?

**Comment by uranusjr** [comment]
I found this is happening not only with pt-BR but also some other languages, so I added them to the project in the latest commit. Hope it works!

**Comment by ronisbr** [comment]
Hi @uranusjr !

Seems to be working perfectly now, thanks! :)

**Comment by franklinyu** [comment]
According to the context, this issue can be closed?
