### ISSUE TITLE
Strange alignment in localized preferences dialog

### ISSUE THREAD

**Issue by ronisbr** [MacDownApp/macdown#837]
Hi guys,

Sometimes a phrase in Brazilian Portuguese can be much larger than the same in English. This happened in the preference dialog. The problem is that the alignment of two components became very strange as you can see in the following picture:

<img width="632" alt="captura de tela 2017-08-05 as 16 46 26" src="https://user-images.githubusercontent.com/1068295/28998356-144cc1a8-79ff-11e7-852d-5a24a2c9d2f0.png">

Notice the alignment of the two components right below the TeX option.

**Comment by uranusjr** [comment]
Fixed! Autolayout is hard. 😉

**Comment by ronisbr** [comment]
Thanks @uranusjr ! It is working perfect now. However, I still need to import the XLIFF file from Transifex so that the pt_BR translation can be correctly applied as I mentioned in #836.
