### ISSUE TITLE
String about Shell utility is not being localized

### ISSUE THREAD

**Issue by ronisbr** [MacDownApp/macdown#838]
Hi guys,

I found a string in MacDown without option to be translated:

<img width="472" alt="captura de tela 2017-08-05 as 17 03 05" src="https://user-images.githubusercontent.com/1068295/28998386-0ccf36f8-7a00-11e7-8fe7-6f754488974e.png">

**Comment by uranusjr** [comment]
Thanks for catching this! I’ve marked the source and the strings should show up on Transifex soon (after the export hook picks it up).
