### ISSUE TITLE
brew cask install v0.6.4

### ISSUE THREAD

**Issue by majia29** [MacDownApp/macdown#842]
run cmd  `brew cask install macdown`
show message 
`==> Downloading https://github.com/MacDownApp/macdown/releases/download/v0.6.4/MacDown.app.zip`

but latest releases is 0.7.1.

**Comment by niklasberglund** [comment]
Which macOS version are you using? 0.7.1 cask requires macOS Mountain Lion or newer.
For me it's downloading 0.7.1. I'm on Sierra.

```
$ brew cask reinstall macdown
==> Satisfying dependencies
==> Downloading https://github.com/MacDownApp/macdown/releases/download/v0.7.1/MacDown.app.zip
```

**Comment by uranusjr** [comment]
IIRC 0.6.4 requires Mountain Lion as well though. Something is right with your Homebrew Cask, or even Homebrew proper.

**Comment by niklasberglund** [comment]
The 0.6.4 cask doesn't specify required macOS version. But in the 0.7.1 cask it's specified: `depends_on macos: '>= :mountain_lion'`

**Comment by uranusjr** [comment]
Ah I see.

**Comment by majia29** [comment]
Uh .... I'm on Sierra(ver 10.12.6), too. 
I downloaded and installed the 0.7.1, manually. I try reinstall, but it is still wrong...

> ~ brew cask reinstall macdown
> ==> Downloading > https://github.com/MacDownApp/macdown/releases/download/v0.6.4/MacDown.app.zip

It's *bad luck*,  I still thanks you for nice work.

**Comment by uranusjr** [comment]
@majia29 Can you try checking the Cask file for me? Maybe we can still help resolve this issue, even if it’s not relevant here. I vaguely remember Homebrew (or Homebrew Cask) messed up something a while back, and require some manual intervention to fix your repository. Can you run `brew update` and `brew cask update` and show the output here? It should contain some valuable information debugging this issue.

**Comment by majia29** [comment]
Thanks. I try `brew update`, then it's ok.
```
~ brew cask reinstall macdown
==> Satisfying dependencies
==> Downloading https://github.com/MacDownApp/macdown/releases/download/v0.7.1/MacDown.app.zip
```
