### ISSUE TITLE
Open Recent list always blank 

### ISSUE THREAD

**Issue by ethering** [MacDownApp/macdown#845]
Hi,
Over the past couple of weeks my 'Open Recent' list of files has been totally blank. Previously it would list the 10 most recent files. There used to be an option in the Preferences to pick the number of recent files, but this seems to have disappeared.
I'm using v0.7.1 (870) on Mac Sierra v10.12.6.
Cheers,
Graham

**Comment by franklinyu** [comment]
Not happening on my machine; does this happens only to MacDown? How about other applications?

By the way, the MacDown Preferences should not affect the “Open Recent” list; it should be "System Preferences -> General -> Recent items", like

![recent items](https://images.techhive.com/images/article/2012/12/general-sys-pref-100017091-large.png)

**Comment by uranusjr** [comment]
And there’s nothing we can do either. That menu is managed by the OS. [File a radar](https://developer.apple.com/bug-reporting/) to Apple if the problem persists with the above settings.

**Comment by suculent** [comment]
This happens in Sonoma as well and only in MacDown.

**Comment by liviurad** [comment]
still happening in macOS 14.4, Macdown 0.7.3

**Comment by copernico** [comment]
Still happening in macOS 14.5, Macdown Version 0.7.3 (1008.4).
This is not happening with any other application on my machine.

**Comment by Typraeurion** [comment]
I’ll add that the Open Recent list is full of entries, but they all appear to be “null”.
<img width="348" alt="image" src="https://github.com/user-attachments/assets/9df21595-f672-482c-b05b-72175b055ccd">
Clicking on any of these blank entries shows an error, demonstrating all of the recent files have been forgotten.
<img width="263" alt="image" src="https://github.com/user-attachments/assets/41eeda05-c2d5-4a52-9ede-ea6f05a9cc75">
(FWIW I’m on MacOS 13.6.7, MacDown 0.7.2)

**Comment by maartenmarx** [comment]
Same here, on Macos 15.1.1 and macdown 0.7.3, started when I switched to segoia

**Comment by copernico** [comment]
Hi, can we reopen this issue? This is clearly an unintended behaviour that is specific to MacDown, so [this](https://github.com/MacDownApp/macdown/issues/845#issuecomment-333741653) is not a solution.

**Comment by halukbingol** [comment]
I still have the "Open Recent" problem. It shows "Clear Menu" in gray.
MacDown: Version 0.7.3 (1008.4)
MacOS: 15.6.1 (24G90).

**Comment by ojalaquellueva** [comment]
Still happening. "Open recent" list always empty. No other applications are affected, only MacDown.

macOS 15.6.1
MacDown 0.7.3 (1008.4)
