### ISSUE TITLE
\vec and \hat rendered with offset in mathmode

### ISSUE THREAD

**Issue by mitchnegus** [MacDownApp/macdown#846]
I find when rendering math (either in-line or display mode with $$) my vector and hat symbols show up as offset. For instance, when I use the following text
`
$$ \int_V{ n(\vec{r}, E, \hat{\Omega}, t) \; d^3r }$$
`
I get the following output in the display:
<img width="172" alt="screen shot 2017-08-31 at 1 51 34 pm" src="https://user-images.githubusercontent.com/21086604/29944751-895f0f9c-8e53-11e7-8e91-b4851abb355e.png">

**Comment by adamwulf** [comment]
Looks like this was fixed in MathJax 2.7.2, so upgrading that lib in MacDown should fix the issue. https://github.com/mathjax/MathJax/issues/1913
