### ISSUE TITLE
add table format

### ISSUE THREAD

**Issue by chendongMarch** [MacDownApp/macdown#847]
May I format the table in MacDown?

**Comment by franklinyu** [comment]
Preferences -> Markdown -> Block formatting -> Table.

Comment if this is not what you want, and I will re-open.

**Comment by chendongMarch** [comment]
Thanks,I mean the edit area is formatted instead of the preview area。

```
colA|colB|colC
:--|:--|:--
value1|value2|value3
```

format to ->

```
colA		        |colB		|colC
:--			|:--		        |:--
value1		|value2		|value3
```

**Comment by chendongMarch** [comment]
Thanks,I mean the edit area is formatted instead of the preview area。

```
colA|colB|colC
:--|:--|:--
value1|value2|value3
```

format to ->

```
colA		|colB		|colC
:--			|:--		|:--
value1		|value2		|value3
```

**Comment by chendongMarch** [comment]
Thanks,I mean the edit area is formatted instead of the preview area。

```
colA|colB|colC
:--|:--|:--
value1|value2|value3
```

format to ->

```
colA	|colB	|colC
:--		|:--	|:--
value1	|value2	|value3
```

**Comment by chendongMarch** [comment]
Thanks,I mean the edit area is formatted instead of the preview area。

```
colA|colB|colC
:--|:--|:--
value1|value2|value3
```

format to ->

```
colA	|colB	|colC
:--	|:--	|:--
value1	|value2	|value3
```

**Comment by franklinyu** [comment]
You mean "to reformat the Markdown source code and align the table boundaries"? Then it may be duplicate of #560, so currently there is no plan for it.

**Comment by chendongMarch** [comment]
Thanks!
