### ISSUE TITLE
I can't get preview using Macdown

### ISSUE THREAD

**Issue by lewton75** [MacDownApp/macdown#848]
I have the same problem with https://github.com/MacDownApp/macdown/issues/403.
And the methods provided by uranusjr doesn't work for me.
The preview pane is still empty.

**Comment by franklinyu** [comment]
Then could you please paste the HTML, as described in #403?

**Comment by lewton75** [comment]
<html><head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>interrupt-configure</title>


<link rel="stylesheet" type="text/css" href="file:///Users/liudun/Library/Application%20Support/MacDown/Styles/GitHub2.css">

<link rel="stylesheet" type="text/css" href="file:///Applications/MacDown.app/Contents/Resources/Prism/themes/prism.css">

<link rel="stylesheet" type="text/css" href="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/line-numbers/prism-line-numbers.css">

<link rel="stylesheet" type="text/css" href="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/show-language/prism-show-language.css">


</head>

<body>

<h1 id="toc_0">test yy</h1>

<p>This is a test text...</p>



<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Extensions/tasklist.js"></script>

<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Prism/components/prism-core.min.js"></script>

<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/line-numbers/prism-line-numbers.min.js"></script>

<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/show-language/prism-show-language.min.js"></script>

<script type="text/x-mathjax-config">
(function () {

MathJax.Hub.Config({
	'showProcessingMessages': false,
	'messageStyle': 'none'
});

if (typeof MathJaxListener !== 'undefined') {
	MathJax.Hub.Register.StartupHook('End', function () {
		MathJaxListener.invokeCallbackForKey_('End');
	});
}

})();
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>





</body></html>

###########################################

The above html codes is what I paste according to #403. And the markdown text is:
"# test yy
This is a test text..."

Now the macdown sometimes can preview, but I must wait for 20~30 seconds and maybe sometimes it won't preview at all. I don't know why.

This problem is happened after I accidently deleted macdown app, then reinstalled it.

**Comment by franklinyu** [comment]
I updated your description; I hope this is what you meant.

The HTML seems just right; for better debugging, is it possible to dump the HTML before the content get previewed? (That is, during the 20-second gap.)

**Comment by lewton75** [comment]
<img width="1280" alt="macdown-debugging" src="https://user-images.githubusercontent.com/12171323/30527770-b696baa0-9c5e-11e7-9a25-29beda0b2dc6.png">
Sorry for my poor description.
I followed your instruction, the picture is my screenshot and the corresponding html codes is:

<html><head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">



<link rel="stylesheet" type="text/css" href="file:///Users/liudun/Library/Application%20Support/MacDown/Styles/GitHub2.css">

<link rel="stylesheet" type="text/css" href="file:///Applications/MacDown.app/Contents/Resources/Prism/themes/prism.css">

<link rel="stylesheet" type="text/css" href="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/line-numbers/prism-line-numbers.css">

<link rel="stylesheet" type="text/css" href="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/show-language/prism-show-language.css">


</head>

<body>

<h1 id="toc_0">test</h1>

<p>test again...</p>

<p>and test again and again</p>



<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Extensions/tasklist.js"></script>

<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Prism/components/prism-core.min.js"></script>

<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/line-numbers/prism-line-numbers.min.js"></script>

<script type="text/javascript" src="file:///Applications/MacDown.app/Contents/Resources/Prism/plugins/show-language/prism-show-language.min.js"></script>

<script type="text/x-mathjax-config">
(function () {

MathJax.Hub.Config({
	'showProcessingMessages': false,
	'messageStyle': 'none'
});

if (typeof MathJaxListener !== 'undefined') {
	MathJax.Hub.Register.StartupHook('End', function () {
		MathJaxListener.invokeCallbackForKey_('End');
	});
}

})();
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>





</body></html>

**Comment by franklinyu** [comment]
I guess the HTML you pasted was copied after the 20-second gap, because it is different from the one in the screenshot. In the screenshot, the paragraph

```html
<p>and test again and again</p>
```

did not appear (unlike in the HTML you pasted), so probably it was the conversion from Markdown to HTML that took 20 seconds. Could you please confirm this, or is there anything to add to your description?

**Comment by lewton75** [comment]
The HTML codes is correct, just as the last comment say.
I know the reason why I get the preview after 20 seconds. See the new screenshot, when macdown will have loaded the `MathJax.js - cdnjs.cloudflare.com` successful, I will get the preview.
<img width="634" alt="macdown-debugging" src="https://user-images.githubusercontent.com/12171323/30530522-e83d56e8-9c79-11e7-91b3-9e5ad2f6b6d7.png">

**Comment by franklinyu** [comment]
I tried testing the performance in China with sites like [this one](http://tool.chinaz.com/speedtest.aspx); results show that requests were routed to `104.19.193.102` in Kansas. I guess the requests didn't take 20 seconds; instead they failed and MacDown retried them again and again until 20 seconds later it succeeded. How often does this 20-second gap happen to you? It shouldn't have been very often because the MathJax script on CloudFlare can be cached by MacDown for 30672000 seconds, that is 355 days, according to the response header

```text
Cache-Control: public, max-age=30672000
```

@uranusjr any ideas?

**Comment by niklasberglund** [comment]
@lewton75 if you're not using MathJax you can probably get rid of the delay by unchecking the checkbox for MathJax support in settings. But it's great that you found this bug so it can be fixed 👍

![image](https://user-images.githubusercontent.com/331986/30579718-590e9602-9d4c-11e7-9ac3-a74d8300a303.png)

**Comment by lewton75** [comment]
@franklinyu thank you very much. Just as you say, the 20 seconds delay didn't appear very often. Sometimes it takes 3 seconds, sometimes it takes 5 seconds, the worst situation takes 20~30 seconds. Maybe the reason is the Great Firewall of China and my VPN sometimes is very unstable.

@niklasberglund thank you. When unchecked the `TeX-linke math syntax`, the preview will present in a second.

I love macdown very much, so when the preview is quite slow, I get quite unhappy.

Now I almost knew the reason, and I need to thanks again for @franklinyu 's patient.

**Comment by franklinyu** [comment]
I think #804 or #851 will solve this. I'm closing this issue to keep the repository clean, so @lewton75 please subscribe to #804 and #851 for updates. You are probably just one of the users with slow connection to CDN-JS...
