### ISSUE TITLE
Theme support for strikethrough

### ISSUE THREAD

**Issue by eunjae-lee** [MacDownApp/macdown#85]
As I know, themes can't specify color of texts stroked through.
I want texts to fade out when gets stroked through by giving strikethrough more darker color.

**Comment by hesanford** [comment]
I've looked at the PEG Markdown Highlight [documentation](https://github.com/ali-rantakari/peg-markdown-highlight/blob/master/stylesheet_syntax.md) and they appear to support styling on the strikethrough syntax so I am not quite sure why this isn't working in MacDown.
