### ISSUE TITLE
revert file using command-r ?

### ISSUE THREAD

**Issue by parmentelat** [MacDownApp/macdown#852]
Hi

Most editors allow to reload the current file from disk
This is typically useful in a git-oriented workflow, when you know that git has changed the file.
It can also be useful when you use another more powerful editor to do mass changes, etc
This 'revert' feature is generally bound to Command-R

I have not found that feature in macdown, is this just me who looked in the wrong places, or some choice made on purpose, or just a lack of time maybe ?

insofar as possible I would really welcome a similar feature. Let me know what you think..

**Comment by uranusjr** [comment]
If you’re talking about the standard macOS Versions feature, MacDown does support that, in the Files menu

![screen shot 2017-09-18 at 23 27 50](https://user-images.githubusercontent.com/605277/30550126-1ecf0afe-9cc9-11e7-9590-7d2f610704af.png)

I don’t see any editors bind it to ⌘R though. All document editors I tried bind it to Show/Hide Rulers. TextWrangler has its own Revert and Reload from Disk commands (not Versions), but I don’t think it binds ⌘R to it by default either.

**Comment by uranusjr** [comment]
I’m closing this because

1. The Versions feature works fine
2. Binding ⌘R to that feature doesn’t seem to be common.

Please elaborate if you were talking about something else, or have more dominant examples showing ⌘R is indeed a common, de facto standard.

**Comment by parmentelat** [comment]
I'm using build 0.7.1, and I've never noticed the 'Last Saved' option that your screenshot depicts

here's what I see; and the 'last opened' version is not what I want in this case
![screen shot 2017-09-18 at 18 04 18](https://user-images.githubusercontent.com/4519227/30551756-dfcdfcde-9c9b-11e7-8aaa-6c7a7b02f11a.png)

as to command-R; it is I believe relevant on all web browsers for example; I just checked chrome, firefox and safari, that's what it does (reload or revert or whatever)

I don't mind if the keyboard shortcut is not bound out of the box, but I'd appreciate a simple fixed menu entry so that I can bind that to a shortcut myself

**Comment by parmentelat** [comment]
I should add that I've just tried to 'Browse All Versions' but that won't show me the version currently on my disk.. 
Right now the only way I can do this is to close the file and open it again; which is a hassle :)

**Comment by b3ross** [comment]
👋 Yo guys - the problem here is not to revert to what MacDown saved, it's to revert to what is actually on disk, like if you're using claude to edit the file.
