### ISSUE TITLE
Can not tab multiple lines

### ISSUE THREAD

**Issue by jeffcai** [MacDownApp/macdown#855]
the issue is that: by choosing multiple lines and click tab, it just tab the first line instead of all selected lines.

**Comment by franklinyu** [comment]
To indent multiple line, use <kbd>⌘</kbd> <kbd>]</kbd>.

**Comment by jeffcai** [comment]
does not work for me.

**Comment by franklinyu** [comment]
That's weird. For example, if I have

```text
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Proin rhoncus tortor sit amet pharetra iaculis.
Praesent sollicitudin vitae quam at pharetra.
Fusce gravida purus ut ipsum molestie convallis.
```

Select second and third line, then press <kbd>⌘</kbd> <kbd>]</kbd>. I then get

```text
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	Proin rhoncus tortor sit amet pharetra iaculis.
	Praesent sollicitudin vitae quam at pharetra.
Fusce gravida purus ut ipsum molestie convallis.
```

**Comment by uranusjr** [comment]
*Both* <kbd>⌘</kbd><kbd>]</kbd>/<kbd>⌘</kbd><kbd>[</kbd> and <kbd>Tab</kbd>/<kbd>⇧</kbd><kbd>Tab</kbd> are supposed to work.

![Indent/dedent demo](https://d.pr/i/tsBi83+)
