### ISSUE TITLE
Feature Request: Support Extensions

### ISSUE THREAD

**Issue by rei-vilo** [MacDownApp/macdown#863]
Does supporting extensions figure on the MacDown roadmap? There's already an **Extensions** menu on MacDown but I've found no information about how to use it.

The extensions I use the most are [admonition](https://pythonhosted.org/Markdown/extensions/admonition.html) and [fontawesome](http://bmcorser.github.io/fontawesome-markdown/).

Thank you!

**Comment by franklinyu** [comment]
We already support them, but it is not documented. I guess you may want to track #752 instead, so I'm closing this issue to keep it tidy.
