### ISSUE TITLE
Viewing Files Currently Open in MacDown

### ISSUE THREAD

**Issue by ajschmidt8** [MacDownApp/macdown#869]
Hello. I'm having an issue with MacDown. I'm trying to write a script that determines whether or not a file is currently open in MacDown. The `fuser` and `lsof` commands are not behaving as expected with MacDown.

**Issue & Observed Behavior:**
When I open a file in MacDown (i.e. `~/Desktop/Test.md`) and run `lsof +D ~/Desktop`, `Test.md` does not appear in the output as seen below.

![Test.md should be shown here](https://cl.ly/1h213Y3t473N/Image%202017-10-11%20at%205.32.05%20PM.png)

Additionally, when I run `fuser ~/Desktop/Test.md`, no process IDs are returned as seen below.

![Process IDs should be shown here](https://cl.ly/2I313x2T0D26/Image%202017-10-11%20at%205.34.17%20PM.png)

**Expected Behavior:**
When I open `Test.md` in Atom and run the same commands again, I get the output below:

![Test.md is shown here](https://cl.ly/3h2G1r1c071a/Image%202017-10-11%20at%205.50.23%20PM.png)

![Atom process ID is shown here](https://cl.ly/3y3h0C182K3W/Image%202017-10-11%20at%205.50.47%20PM.png)

**Conclusion:**
Is this is an issue with MacDown? Is there any way to get the same results with MacDown that I got with Atom? Please help!

**Comment by uranusjr** [comment]
Well, as a general rule, `fuser` and `lsof` are extremely unreliable when dealing with GUI applications on Mac. Atom (and Electron-based apps in general) are the exceptions here: most macOS GUI applications play poorly with them.

Unfortunately I don’t have a good solution to this either. Judging from what I found from the Internet it is next to impossible acquiring this information from Cocoa applications. I don’t rule out the possibility of implementing this, but it is non-trivial and well outside of common usages. I would be happy to help if someone wants to put effort on this issue, but lacking related knowledge, don’t think it’s worth the effort investigating myself.
