### ISSUE TITLE
Increase Font Size in Rendering Pane

### ISSUE THREAD

**Issue by saulspatz** [MacDownApp/macdown#870]
Unless I'm missing it, there isn't a way to increase the font size in the rendering pane.  My eyesight isn't what it was, and this would be very useful.  I can increase the font size in the editor pane, which is okay so far as it goes, but I'm usually writing math, so unless I can read the text in the rendering pane, it doesn't help much.

**Comment by Jmuccigr** [comment]
MacDown just uses a css file for the rendering pane, so you can create your own, or just edit the one you're using to employ a larger font.

**Comment by saulspatz** [comment]
Thanks, I'll look at that.

**Comment by uranusjr** [comment]
Or there is a setting that scales preview to match editor’s font size.
