### ISSUE TITLE
Checkboxes not working

### ISSUE THREAD

**Issue by DiegoBM** [MacDownApp/macdown#871]
Hi all,

I have downloaded today the latest version from the website and the preview is not rendering any form of checkboxes.
I have enabled the property "Rendering" -> "Task list syntax" and tried all possible combinations of
```
- [] -[ ] - [ ] - [x] * [] *[ ] * [ ] * [x]
```
and so on, but I never get a rendered preview of a checkbox. Is there any other setting that I need to enable in order to get checkboxes rendered?

Note: I'm working on a MackBook Pro using Mac OS High SIerra

**Comment by uranusjr** [comment]
MacDown only supports checkboxes in a task list context, like this:

```markdown
- [ ] Task 1
- [x] A finished task
- [ ] Another pending task
```

The rules are:

1. The block-level construct needs to be a list (either unordered or ordered).
2. The checkbox should be the first thing in each list item.
3. One list item per line (combining with 2. this also means one checkbox per line).
