### ISSUE TITLE
Feature request: Flow charts and sequence diagrams

### ISSUE THREAD

**Issue by iabraham** [MacDownApp/macdown#872]
Hello, 

I have been using MacDown for taking lecture notes during class and its been absolutely brilliant (I take a lot of math classes and the Tex rendering was a killer feature, plus). I initially started by using stackedit.io but then switched to MacDown because it was open source and local. 

I was wondering if it would be possible to include flow chart rendering and sequence diagrams using

- https://bramp.github.io/js-sequence-diagrams/
- http://flowchart.js.org/

This feature was recently added to stackedit.io and since both the applications offer very similar functionality, I am hoping this won't be too much effort.

**Comment by franklinyu** [comment]
It might be bloated now that we have [mermaid](https://mermaidjs.github.io/) and [Graphviz](http://www.graphviz.org/Home.php). Are they compatible?

**Comment by cfilipov** [comment]
@iabraham, to clear up a misconception: stackedit.io is both [open source](https://github.com/benweet/stackedit) and local (it uses IndexedDB + Service Workers to work offline).

That said, I also use MacDown and would be *very* happy to see mermaid integration. I suggest also integrating [viz.js](https://github.com/mdaines/viz.js).

**Comment by franklinyu** [comment]
@cfilipov Mermaid has been in master branch and will be available in next release. Stay tuned.

**Comment by DiamondI** [comment]
I see there are three files related to mermaid in Extensions,  but I don't know how to use it. May I ask how to integrate those files into MacDown? @franklinyu  Thanks a lot.

**Comment by franklinyu** [comment]
@DiamondI There is a switch in preference panel.

**Comment by DiamondI** [comment]
sorry, I still can't find it. @franklinyu Is there anything I missed?

<img width="353" alt="1" src="https://user-images.githubusercontent.com/18584660/38534316-3fd33e00-3cb0-11e8-8be1-ffc348ae9bd1.png">
<img width="400" alt="2" src="https://user-images.githubusercontent.com/18584660/38534324-48396d30-3cb0-11e8-8364-f9fcc28072dc.png">
<img width="482" alt="3" src="https://user-images.githubusercontent.com/18584660/38534333-5015ec9a-3cb0-11e8-9424-bea3fd0f5d8c.png">
<img width="405" alt="4" src="https://user-images.githubusercontent.com/18584660/38534338-580f2952-3cb0-11e8-91ae-2bae6b044480.png">
<img width="360" alt="5" src="https://user-images.githubusercontent.com/18584660/38534345-601c8a4a-3cb0-11e8-9dde-bd1462425e81.png">

**Comment by franklinyu** [comment]
@DiamondI Oh it’s only release in testing branch. You can try it out at <https://macdown.uranusjr.com/history/testing/>

**Comment by DiamondI** [comment]
@franklinyu It seems that a duplicate mermaid graph occurs.

<img width="1368" alt="1" src="https://user-images.githubusercontent.com/18584660/38537089-39d58b16-3cbf-11e8-996d-8a93cb41c895.png">

**Comment by franklinyu** [comment]
@DiamondI please search for issue and pull request. It's #958 in this case.

**Comment by DiamondI** [comment]
@franklinyu I'm sorry for not searching for the issue first. Anyway, it works now! And thanks a lot!

**Comment by wingCi** [comment]
@DiamondI @franklinyu Thx,i have same issue,and dialogue help me a lot.
