### ISSUE TITLE
Editor freezes when there are many latex formulas

### ISSUE THREAD

**Issue by goodman-capu** [MacDownApp/macdown#879]
The editor freeze once in a while when typing for about 10-60 seconds, if there are many latex formulas.

I consider this as a **bug** rather than a performance issue because there seems to be a **threshold** for this. If the text is not too long and contain not too much latex, the editor is always ok. But after some sort of threshold, the editor begins to freeze once in a while.

I don't know whether it's related to latex or it's just a general problem.

**Comment by franklinyu** [comment]
Was it just the preview panel, or the entire application, that froze?

**Comment by goodman-capu** [comment]
Entire app freezes

**Comment by franklinyu** [comment]
Does it looks like #807?

**Comment by goodman-capu** [comment]
Yes it's like #807. The CPU comes to 100%, but seems that the memory won't increase dramatically.

**Comment by goodman-capu** [comment]
I think it's a duplicate of #807 . So I'm closing this issue.
