### ISSUE TITLE
UI components change randomly

### ISSUE THREAD

**Issue by snakeninny** [MacDownApp/macdown#881]
<img width="960" alt="screen shot 2017-11-06 at 16 36 13" src="https://user-images.githubusercontent.com/641869/32432132-fc71ef14-c29b-11e7-8113-954eec727862.png">

**Comment by franklinyu** [comment]
Sorry but which component changed?

**Comment by snakeninny** [comment]
Shouldn't it be like this?
![image](https://user-images.githubusercontent.com/641869/32480619-5138d9a4-c355-11e7-8291-d0d4dae92c9f.png)

**Comment by franklinyu** [comment]
This is actually two different issues. Please check:

 1. Preferences => Editor => Theme
 2. Preferences => Rendering => CSS

Whether these two values are changed? I'm using `Tomorrow+` (I believe this is the default) and `github3` respectively.

**Comment by snakeninny** [comment]
Seems there's something wrong:

![image](https://user-images.githubusercontent.com/641869/32548600-2df88120-c4c1-11e7-88cf-8a35651797c3.png)

Version 0.7.1 (870)

**Comment by franklinyu** [comment]
The preference of MacDown is saved in these two files:

```shell
$HOME/Library/Preferences/com.uranusjr.macdown.plist
$HOME/Library/Preferences/com.uranusjr.macdown.LSSharedFileList.plist
```

Try moving these preferences to somewhere else (like `/tmp`), then restart MacDown. It would be appreciated if you would provide the corrupted preference file, if the issue disappear after resetting the preference, so that we can debug on that to prevent it from happening again.

**Comment by snakeninny** [comment]
Here you are:
[com.uranusjr.macdown.plist.zip](https://github.com/MacDownApp/macdown/files/1456105/com.uranusjr.macdown.plist.zip)

**Comment by franklinyu** [comment]
So removing the two files *does* fix this issue?

**Comment by uranusjr** [comment]
stale
