### ISSUE TITLE
Preview pane empty until user input

### ISSUE THREAD

**Issue by seren** [MacDownApp/macdown#885]
Hi, thanks for your work on this great project. I found a minor bug in version 0.7.1 (870). When opening an existing file, sometimes the preview pane on the right remains blank until I modify the text by typing something into the text pane on the left.

I've been able to consistently reproduce this by saving this readme: https://raw.githubusercontent.com/sous-chefs/sysctl/master/README.md
and then opening it with MacDown.

This is running on Mac OS 10.13.1.

**Comment by franklinyu** [comment]
#908 suggests that the images (three badges) might be blocking the render process. Could you please try accessing the image in browser (or in Wget/cURL or whatever client you like) with cache disabled?

**Comment by seren** [comment]
This may have been the problem. The README.mb file now renders with no delay, so maybe an image was broken or slow and was blocking things. I'll close this issue out since it should really be a "Rending blocks on slow images" issue. Thanks!
