### ISSUE TITLE
Relative URIs starting with //

### ISSUE THREAD

**Issue by JetForMe** [MacDownApp/macdown#891]
I tend to write the URLs to my image assets as starting with `//`. This means the user-agent should use whatever scheme the enclosing page was requested with (e.g. `http:` or `https:`). In the Macdown preview, I just end up with broken images.

Could Macdown try `https`, and if that fails try `http`? Thanks!

**Comment by franklinyu** [comment]
> the user-agent should use whatever scheme the enclosing page was requested with

I believe it does. In MacDown preview pane, the page was probably requested with `file` protocol. I don't think the Markdown engine changes your link, so if you export the HTML and serve it with HTTP, then the image would be loaded through HTTP. That makes sense to me.

**Comment by JetForMe** [comment]
I'm suggesting that it should not do this. It should deliberately re-write the URLs with https: or http: if they fail to load (and they start with //). Because it makes previewing break otherwise.

**Comment by franklinyu** [comment]
Then are you proposing it to rewrite the URL with HTTP or HTTPS?

**Comment by JetForMe** [comment]
No. I'm only talking about the preview pane, as you're editing markdown.

**Comment by franklinyu** [comment]
Then we need to keep both, in case user want to export the HTML; or generate it again when user export HTML. Neither can be done trivially.

**Comment by JetForMe** [comment]
Okay. I'm not sure how you implement your preview, but as-is, it makes for a very broken preview when using scheme-relative URIs. I don't export to HTML from Macdown, I use Jekyll.

**Comment by franklinyu** [comment]
I assume that the resource you mentioned is available both through HTTP and HTTPS right? And you are not writing some web-page for mobile users in some region where they are still stuck in GPRS or 2G network or similar legacy technology? Then I would just use HTTPS.

**Comment by JetForMe** [comment]
I think generally, it would be available as HTTPS, but not always (it's up to each individual user to host their images, and they might not make them available via HTTPS, even though they should). In my case, I use Flickr and Imgur to host my images, and they both use HTTPS.

But I think one way to handle this would be to use the delegate callback on WKWebView to handle failed resource loads and re-try them, first with HTTPS and then with HTTP. I'd have to look at the docs to see specifically how to do this (or even if you can).

**Comment by franklinyu** [comment]
I think you are talking about [`- webView:resource:didFailLoadingWithError:fromDataSource:`](https://developer.apple.com/documentation/webkit/webresourceloaddelegate/1537843-webview?language=objc). The statement still holds: either keep both HTML, or re-generate HTML on export.

> it's up to each individual user to host their images, and they might not make them available via HTTPS, even though they should

If by "user" you mean MacDown user, then when they writes the Markdown, they should at least be able to know whether their image is available through HTTPS or not.

**Comment by JetForMe** [comment]
I don't know what HTML export has to do with the preview pane.

And the user may have numerous different `//`-style URLs. Some may serve up HTTPS, and others HTTP.

**Comment by franklinyu** [comment]
> I don't know what HTML export has to do with the preview pane.

"HTML export" currently just exports the HTML in the WebView, AFAIK.

> And the user (yes, the Macdown user) may have numerous different //-style URLs. Some may serve up HTTPS, and others HTTP.

When I insert image into Markdown, I typically copy the link from somewhere (for example, the "copy image URL" in browser context menu), and the protocol just come with it. I thought this is the workflow of most user…

**Comment by JetForMe** [comment]
It might be, but if the resulting markdown is then converted to HTML (say, using Jekyll), and it has a hard-coded `http:` or `https:`, then when that HTML gets to the server, it might cause problem on the client end, because the enclosing page might mismatch. This is common when using Jekyll and previewing your content locally without HTTPS, and then putting it on the server with HTTPS.

By using IMG URLs that begin with `//` and no `https:` or `http:`, you avoid this problem altogether.

**Comment by franklinyu** [comment]
> when that HTML gets to the server, it might cause problem on the client end, because the enclosing page might mismatch.

Do you mean that the original link expired?

**Comment by JetForMe** [comment]
A mismatch between the scheme used to retrieve the root resource, and the scheme in the image link. None of this has anything to do with links expiring.

**Comment by uranusjr** [comment]
For local assets, the solution is to just use relative links, which (I believe) is the most wildly used solution when developing HTML that would be served later via HTTP. For remote assets, you should always prefer HTTPS because virtually all browsers support that out of the box, and the performance impact is minimal, defeating the original purpose of `//`.

Related reading: https://www.paulirish.com/2010/the-protocol-relative-url/

It is still possible we might need this feature, but I don’t think it is the correct solution to your particular usage.

**Comment by JetForMe** [comment]
Okay, that's an acceptable alternative.
