### ISSUE TITLE
Add link to GitHub project in application

### ISSUE THREAD

**Issue by ajmas** [MacDownApp/macdown#893]
MacDown 0.7.1 indicates it is open source, but contains no reference to the project on GitHub. I checked in both the 'About MacDown' and 'MacDown Help', but I see nothing there.

Possible options:
   - Add link in about dialogue
   - Add link in help.md
   - Add new help item, 'Contribute to MacDown', with a contribute.md document that gets opened.

If you have any preferences then we just need to find a resource and the cycles to make the change.

**Comment by uranusjr** [comment]
Good idea. Would you be interested to write a simple `contribute.md` file? I’m pretty terrible at this kind of things. (There’s already a CONTRIBUTING.md in the repo, but that’s not a very good first impression for new contributors…)

**Comment by ajmas** [comment]
Here is 10min initial draft to get the ball rolling:

---

# Contributing to MacDown

MacDown is open source and is a volunteer effort. This
means that it depends on people to give some of their free
time to improve it and make it even better.

If you are reading this, then you are probably curious or
want to contribute in some way. Read on to see how you can
do so.

## Getting the Source Code

MacDown is hosted on GitHub:

https://github.com/MacDownApp/macdown

Here you can get the source code, read through the issues
and start contributing.


## I am not a Coder

Contribution is not limited to software developers, since
there are other ways you can help. For example, contributing towards documentation, translation and
support. Join the room on Gitter to see how you can help
(see below).

## Joining the Conversation

If you are new the project, then a good place to start
is Gitter:

https://gitter.im/MacDownApp/macdown

Join the room, introduce yourself and find out how you
can help out.

## License

MacDown is released under the terms of MIT License. For
more details take a look at the [README](https://github.com/MacDownApp/macdown/blob/master/README.md).


---

**Comment by franklinyu** [comment]
Also mention that translating is done through [Transifex](https://www.transifex.com/macdown/macdown/)?

**Comment by ajmas** [comment]
Updated text.
