### ISSUE TITLE
Rotating rainbow disk

### ISSUE THREAD

**Issue by Morane** [MacDownApp/macdown#897]
Hi,

Always happy to use Macdown 👍. Just a feedback : now that I use High Sierra, the rotating rainbow disk sometimes appears, and Macdown freezes. In the " Force to quit " menu, I see that Maccdown no longer react. However, after about 15 s, it goes on again. An idea of the cause of this issue ? Mentioned by other users ?

Cheers

**Comment by franklinyu** [comment]
Since it recovers in your case, I assume this is different from #807?

**Comment by franklinyu** [comment]
Any more information?

**Comment by Morane** [comment]
Hi Frank,

Sorry. I give up and return to HTML.

Best,

Alain
