### ISSUE TITLE
Release differences?

### ISSUE THREAD

**Issue by gcstang** [MacDownApp/macdown#909]
On GitHub the last release was 0.7.1 but on the MacDown website the release at the bottom of the page is 0.7.2d49 (919).   What is the difference are you only posting the latest to your website and not GitHub or is there another reason?

**Comment by franklinyu** [comment]
0.7.2d49 is [testing release](https://macdown.uranusjr.com/history/testing/) and 0.7.1 is [stable release](https://macdown.uranusjr.com/history/stable/). I guess @uranusjr thinks too few people uses test release, and he wants to promote it.

**Comment by gcstang** [comment]
Is there a way to create a Table of Contents (ToC) from all the header fields on a document?

**Comment by franklinyu** [comment]
Sure. It can be enabled in preferences (it's opt-in for compatibility), and the token is `[TOC]`. I cannot tell the exact location immediately because I don't have access to my personal mac from work, but it should be easy if you go through all five preference tabs.

**Comment by gcstang** [comment]
Awesome!  Thank you found it in Preferences > Rendering Tab > Detect table of contents token

**Comment by uranusjr** [comment]
Actually I didn’t realise the link points to the dev version until now 😨 Fortunately that version happens to be perfectly functional, so I guess I’ll keep it. It should point to the latest *stable* though.
