### ISSUE TITLE
How to edit version？

### ISSUE THREAD

**Issue by jaybenjaminlee** [MacDownApp/macdown#914]
when I archive，the version is 0.0（0），how to change it？   I have change the version of  .xcodeproj，but it don't work

**Comment by franklinyu** [comment]
Archiving works for me. The current version says 0.7.2d81 (951).

**Comment by uranusjr** [comment]
The version number is updated automatically at compile time based on Git metadata. It should work if you use `git clone` to get the repository. If for some reason you can’t do that, path `Tools/utils.sh` to hard-code the version to something else.

https://github.com/MacDownApp/macdown/blob/master/Tools/utils.sh
