### ISSUE TITLE
anchor links not responding in Preview Pane (High Sierra)

### ISSUE THREAD

**Issue by marc-medley** [MacDownApp/macdown#924]
Anchor links do not jump to the anchored section in the MacDown Preview Pane on macOS High Sierra. 

**Scenario**

Steps to replicate:

1. Launch MacDown 0.7.1 on an up-to-date macOS High Sierra system.
2. Open the `help.md` by selecting Help > MacDown Help from the MacDown top menubar.
3. Click on any of the "**Markdown preference pane**", "**Rendering preference pane**", "**Editor preferences pane**" or "**General preference pane**" links near the first part of `help.md`.

Result: The preview anchor link does not jump to the corresponding anchored section.

Expected: Expected the anchor link to jump to the corresponding anchor section.

**Background**

This issue was noticed shortly after upgrading a system to macOS High Sierra.  The same issue was observed on two additional macOS High Sierra machines.

This issue does not occur on yet another system which remains on macOS Sierra 10.12. 

**Environment**

MacDown 0.7.1 (870)
macOS High Sierra (10.13.3)

**Comment by DiamondI** [comment]
Same issue with MacDown version 0.7.2d49 (919) and system Mac OS X 10.13.3.

**Comment by marc-medley** [comment]
A rerun of my Markdown test page and the MacDown `help.md` on MacDown 0.7.1 (870) running on High Sierra (**10.13.4**) and _found the Preview Links are now working OK._

``` markdown
<a id="toc"></a>
[Images](#Images) | … | [Resources](#Resources)
…
## Images <a id="Images">[▴](#toc)</a>
…
## Resources <a id="Resources">[▴](#toc)</a>
…
```

/System/Library/Frameworks/WebKit.framework/Versions/Current/Resources/version.plist and Info.plist show the WebKit CFBundleVersion to be "13605.1.33.1.2". 

So, since the Preview Links now work on the same MacDown 0.7.1 (870) version, then the issue appears to have been external to MacDown and fixed with some macOS System and/or Safari/Safari Preview update.

I'm ok if this issue is closed.

**Comment by uranusjr** [comment]
🕵️‍♂️

**Comment by DiamondI** [comment]
Yeah, MacDown does well with **10.13.4**. Thanks a lot.

**Comment by SidSethi** [comment]
Is anyone else experiencing this same issue with MacDown version 0.7.1(870) on MacOS 10.13.5?

**Comment by marc-medley** [comment]
A rerun of my Markdown test page and the MacDown help.md on MacDown 0.7.1 (870) running on High Sierra (**10.13.6**) and _found the Preview Links are working OK_.

**Comment by grumBit** [comment]
I'm having this problem on macOS 10.13.6 and MacDown 0.7.1(870).

From previous posts I'm guessing this maybe a macOS problem.

/System/Library/Frameworks/WebKit.framework/Versions/Current/Resources/version.plist and Info.plist show the WebKit CFBundleVersion to be "13605.3.8" ([compared to "13605.1.33.1.2 as previously mentioned on 10.13.4"](https://github.com/MacDownApp/macdown/issues/924#issuecomment-379913889) .  

Anyone got ideas about how to address this?
