### ISSUE TITLE
Support for Github style checkmarks?

### ISSUE THREAD

**Issue by andrewhuang** [MacDownApp/macdown#925]
Any support now or in the future for checkmarks? If one wanted to make a PR for this, where would one start? Thanks!

- [x] Use MacDown
- [x] ???
- [ ] Profit!!!

**Comment by uranusjr** [comment]
Already does.

**Comment by andrewhuang** [comment]
@uranusjr maybe I'm missing something, but I don't see it on 0.71:

<img width="684" alt="screen shot 2018-02-12 at 9 50 25 am" src="https://user-images.githubusercontent.com/1175612/36111225-43a3b76a-0fda-11e8-88b9-b94bd637cf54.png">

**Comment by franklinyu** [comment]
@andrewhuang You need to enable it in preferences. It's opt-in.
