### ISSUE TITLE
what library is used to export the rendered HTML to PDF?

### ISSUE THREAD

**Issue by oquirozm** [MacDownApp/macdown#927]
I'm looking into creating a cli-tool to automatize converting Markdown with HTML to PDF  and I  MacDown's PDF exporting feature works amazingly well for what I need. But I have zero experience in MacOS development so this repo is like a foreign language for me. Can someone give some hint on the library used for this? Any idea if there's a port of that for node.js?

**Comment by uranusjr** [comment]
It’s the built-in macOS PDF generation API.  Basically everything (well, modern things) you see on a macOS desktop is drawn with a format that can be easily [converted to PDF with one single call](https://developer.apple.com/documentation/appkit/nsview/1483797-datawithpdf). There are some additional configuration involved (e.g. page size), but that is basically it.

This API requires you to draw *somewhere* on the screen, unfortunately, and cannot be used very easily in a CLI tool. One approach I’ve seen is to use draw the content off screen, but that would require quite some knowledge of how the GUI event system works on macOS to be pulled off.

I would recommend [wkhtmltopdf](https://wkhtmltopdf.org) instead. It is based on Qt’s WebKit engine, and already did all the heavy-plumbing mentioned above for you. It is quite good.

**Comment by oquirozm** [comment]
thanks @uranusjr!
