### ISSUE TITLE
#Header or #Comments getting rendered as Headers 

### ISSUE THREAD

**Issue by jijojv** [MacDownApp/macdown#934]
Hi
I think per MD spec headers should have a space after # but macdown renders any lines with # as headers even without space  e.g. 
#test
would show as H1 in macdown but no other markdown which leads to bugs when reviewing and later pasting into other place like GitHub issues.
Thanks.

**Comment by uranusjr** [comment]
The space is not required per Markdown spec. It is CommonMark, a variant of Markdown, that enforces this. GitHub uses CommonMark, but not everyone does (e.g. StackOverflow).

I recommend using code blocks (indent or use fences around the block that should be treated as code). This is best practice anyway.

~~~markdown
Text text text

```
This is code
#comment look like comment
# Even with a space!
```
~~~
