### ISSUE TITLE
Quote characters are processed inside a quote block when preceded by two spaced newline

### ISSUE THREAD

**Issue by eedwards-sk** [MacDownApp/macdown#938]
A code block is supposed to disable all processing / interpretation for the contents inside.

When placing text above a code block and using two spaces to move the following text to a newline, quote character inside the code block ends up being processed.

(Since I'm showing a markdown code example inside markdown itself, I will use a single quotation mark in place of the backtick character for the 'given')

#### Given
```
my code block:[space][space]
'''
> contents inside starting with > character
'''
```

#### Expected:

my code block  
```
> contents inside starting with > character
```

#### Actual:

my code block  
\`\`\`
> contents inside starting with > character

**Comment by eedwards-sk** [comment]
It seems that any time you use a double-space to add a newline and then use a multi-line code block after it, that line gets turned into a 'single line' code block, rather than a 'multi line'.

e.g. I noticed if I specify a json blob in a multiline code block with a double-spaced text heading, it converts it to single line.

#### Given

```
my json blob:[space][space]
'''
{
    "foo": {
        "bar": "baz"
    }
}
'''
```

#### Expected

my json blob:  
```
{
    "foo": {
        "bar": "baz"
    }
}
```

#### Actual

my json blob:  
```{ "foo": { "bar": "baz" } }```

**Comment by franklinyu** [comment]
Currently code block requires an empty line before it. See #892. Please track that issue instead.
