### ISSUE TITLE
Graphviz does not render multiple graphs within single document

### ISSUE THREAD

**Issue by stemberamichal** [MacDownApp/macdown#940]
If multiple graphviz codeblocks are present within single document. Only the first one is rendered.
I've installed the latest version from master (e7d3cf7).

I was running  macOS High Sierra 10.13.3

**Content of file to reproduce**
````markdown
```dot
digraph First {
    A -> B;
}
```

```dot
digraph Second {
    B -> A;
}
```
````
I have added TABs from left for it to render here. There were no TABs within the original document.

**Outcome**
<img width="842" alt="screen shot 2018-03-20 at 10 14 40" src="https://user-images.githubusercontent.com/6717361/37645566-8d8faba4-2c27-11e8-9d94-7700f5750852.png">

**Comment by franklinyu** [comment]
Please check if #943 fixes it.

**Comment by stemberamichal** [comment]
Not sure how should I have tested (new to open source).

Rather I explain what I did:
1. Cloned your forked repo.
1. Installed dependencies
1. Ran MacDown
1. Checked if it works with code

```
        ## First
	```dot
	digraph First {
		A -> B;
	}
	```
	## Second
	```dot
	digraph Second {
		B -> A;
	}
	```
	## Third
	```neato
	digraph Third {
	A -> B;
	}
	```
	## Fourth
	```fdp
	digraph Third {
	B -> A -> B;
	}
	```
	## Fifth
	```sfdp
	digraph Third {
	B -> A -> B;
	}
	```
	## Sixth
	```twopi
	digraph Third {
	B -> A -> B;
	}
	```
	## Seventh
	```circo
	digraph Third {
	B -> A -> B;
	}
	```
	
	## Eighth
	```twopi
	digraph Third {
	B -> A -> B;
	}
	```
```

Which results into:
<img width="642" alt="screen shot 2018-03-22 at 10 02 43" src="https://user-images.githubusercontent.com/6717361/37760846-3526253c-2db8-11e8-87fd-4f6e08e4ed5f.png">

**Comment by franklinyu** [comment]
Well done!

I added another commit. Please try again.

**Comment by stemberamichal** [comment]
Thanks.

Still seems some of them are not working. Not a Graphviz Pro so I am only using dot, neato, circo, fdp.

![943_test](https://user-images.githubusercontent.com/6717361/37787208-beef01a8-2dfe-11e8-90e1-0e739331b8ec.png)

![943_test-2](https://user-images.githubusercontent.com/6717361/37787209-bf0d2c28-2dfe-11e8-9ed9-7f356e75ae3c.png)

**Comment by franklinyu** [comment]
My bad. Currently our implementation uses [Viz.js](https://github.com/mdaines/viz.js), which does not yet support `sfdp`. Please subscribe to mdaines/viz.js#119 for updates. We are happy to support `sfdp` as soon as Viz.js do.

**Comment by stemberamichal** [comment]
No problem and thanks.
Can I close it now or does it need to be someone internal?

**Comment by franklinyu** [comment]
This will automatically be closed once the patch is merged to master branch. Just wait.
