### ISSUE TITLE
Headers rendered within the code on the left side, not on the right-side

### ISSUE THREAD

**Issue by kenorb** [MacDownApp/macdown#941]
The following formatting is confusing, as it's showing different results on the left side, but renders correctly on the right-side.

<img width="1057" alt="screen shot 2018-03-21 at 12 35 03" src="https://user-images.githubusercontent.com/266306/37710087-7a8f06de-2d04-11e8-9c79-3f5c2f4d7b03.png">

File: 
[MacDown-test.md.txt](https://github.com/MacDownApp/macdown/files/1833207/MacDown-test.md.txt), based on [`README.md` from `QISKit/qiskit-sdk-py`](https://github.com/QISKit/qiskit-sdk-py).

It works fine when I hit Enter after 3rd bullet point, before the code.

Similar: #107

**Comment by franklinyu** [comment]
```diff
 3. We are going to create a new file called `Qconfig.py` and insert the API token into it. This file must have these contents:
+
 ```python
 APItoken = 'MY_API_TOKEN'
```

Add a new line here. Code block need a new line before it.

**Comment by kenorb** [comment]
Yep, however, is there any way that it can be at least consistent between left and right sides?

**Comment by franklinyu** [comment]
It's difficult to be consistent to *invalid* Markdown.
