### ISSUE TITLE
MacDown freeze for 1 minute 

### ISSUE THREAD

**Issue by linediconsine** [MacDownApp/macdown#947]
HI All,
I really like MacDown, thanks to everybody involved!

On Version 0.7.1 (870)
if I enable e 
```rendering --> Tex-Like math syntax```

It randomly freeze spinning wheel for a minute and then start to work again (it happens in multiple times)

**Comment by uranusjr** [comment]
There is a duplicate issue somewhere I can’t find atm. This is probably fixed with the latest prerelease.
