### ISSUE TITLE
Standardise printing (and PDF) margins in the included themes

### ISSUE THREAD

**Issue by jckw** [MacDownApp/macdown#948]
Currently the PDF margins are very small on the sides and quite large at the top and bottom. This doesn't look particularly good, and is annoying to change for a non-technical user. 

Standard (A4) document margins are typically something like 2cm. All that would be required to implement this is to add either a margin or padding value (depending on the style) for `body` when the media type is `print`. 

I've tested this out, and have had a lot better results. Most first time users will probably want to keep PDF/printing margins to a normal printing standard so that their documents come out looking somewhat like a Word or Pages document.

**Comment by uranusjr** [comment]
Tracking this in #950.
