### ISSUE TITLE
Build failed in Xcode 9.3

### ISSUE THREAD

**Issue by franklinyu** [MacDownApp/macdown#954]
See Bertrand/handlebars-objc#20. The repository is pretty much dead; we may want to host our own.

**Comment by uranusjr** [comment]
Forked.

**Comment by uranusjr** [comment]
Probably can use some more work to fix those pesky warnings as well.

**Comment by franklinyu** [comment]
I thought that `inhibit_all_warnings!` is enough, but it turned out not to be. I’m wondering whether this is a bug of CocoaPods, and we should simply report this to CocoaPods.

If we were going to fix those warning ourselves, then we should probably enable issue in MacDownApp/handlebars-objc.
