### ISSUE TITLE
如何页面内跳转

### ISSUE THREAD

**Issue by lucky9322** [MacDownApp/macdown#962]
文章内容太长，想做到目录跳转 。怎么处理

**Comment by franklinyu** [comment]
Try if `[toc]` works for you. Enable it in preference panel.

**Comment by lucky9322** [comment]
sorry , I don't see what you mean.

**Comment by franklinyu** [comment]
https://macdown.uranusjr.com/blog/macdown-022-with-toc-support/

**Comment by lucky9322** [comment]
I have done follow your words ,  but it still doesn't work. 

![demo](https://user-images.githubusercontent.com/11935073/38974829-1b2acebc-43de-11e8-9d1c-68bbbfb279b9.gif)
![1524119332745](https://user-images.githubusercontent.com/11935073/38974837-24adfacc-43de-11e8-9f32-6ff76db75e89.jpg)

**Comment by uranusjr** [comment]
The toggle is moved to the Preferences as “detect table of contents token”.

**Comment by lucky9322** [comment]
thanks very much ,  but no effective like anchors

**Comment by uranusjr** [comment]
Upgrade OS to 10.13.4. #924.
