### ISSUE TITLE
升级新版本后文章长一些会闪退

### ISSUE THREAD

**Issue by chendongMarch** [MacDownApp/macdown#964]
不知道是不是升级新版本的原因，写了一篇文章，稍微有点长，每次编辑一会儿就会闪退。
感觉是文章太长内存不够用了，让我想起来之前用 Chrome 码云编辑 wiki 导致 Chrome 闪退。
麻烦优化一下，感谢。

**Comment by franklinyu** [comment]
1. Please provide an example.
2. Disable math.

**Comment by uranusjr** [comment]
3. Use English.
