### ISSUE TITLE
Erased file after choosing "Don't Save"

### ISSUE THREAD

**Issue by GrumpyOldTroll** [MacDownApp/macdown#965]
I newly downloaded macdown with "brew cask install macdown", clicked "New", created a README.md, then "Save...".

I couldn't get it to pick the directory I wanted, so I had it save in my home directory, then closed my window and moved the file to the directory I wanted, then opened with "macdown README.md" from that directory.

I got blank panes, so I exited the window and clicked "Don't Save", and afterward the file had been erased from disk. Next time I will cp instead of mv. :(

**Comment by uranusjr** [comment]
That’s how macOS works… Haven’t you used software like Pages, Keynote, and TextEdit?
