### ISSUE TITLE
fail to display online image

### ISSUE THREAD

**Issue by cygwins** [MacDownApp/macdown#967]
When adding image in Macdown, only local image can be rendered correctly:
`![alt text](path/to/img.png "It works")`

But putting an image with url here will result in rendering failure, the image shows up as a question mark:
`![alt text](http://domain.xyz/url/to/img.png "Doesn't work")`
<img width="70" alt="image" src="https://user-images.githubusercontent.com/38229206/39075207-786d0830-44a9-11e8-945e-3f325efc2c45.png">

**Comment by franklinyu** [comment]
Following markdown works on my machine:

```markdown
![CloudFlare](https://www.cloudflare.com/img/logo-cloudflare.svg)
```

**Comment by cygwins** [comment]
Hi Frank,

Thanks for the reply. I've tried the identifier *CloudFlare*, works for most website, but not on github (where I especially need it).
```
![CloudFlare](https://github.com/MacDownApp/macdown/blob/master/MacDown/Images.xcassets/Preferences%20Icons/PreferencesMarkdown.imageset/PreferencesMarkdown.png "this doesn't work")
```

Is it due to some redirecting on github url?
Why is this identifier named "CloudFlare", does it have anything to do with www.cloudflare.com?

Thank you.

**Comment by franklinyu** [comment]
@cygwins The URL you quoted is a *webpage*, not an *image*. To get the corresponding image URL (also known as “direct link”), append `?raw=true` to the one you mentioned.

**Comment by cygwins** [comment]
@franklinyu That works well, even with "alt text" within square brackets. Thank you very much! This issue could be closed. Cheers!
