### ISSUE TITLE
Incorrect comment for CSS

### ISSUE THREAD

**Issue by gkvallis** [MacDownApp/macdown#968]
It seems that you support CSS style statements at the top of a markdown file, and they are interpreted and rendered correctly. By this I mean lines like:
 p   {font-size: 12pt} 
give the expected result.

If you try to comment this out with the comment command in the menu, it produces:
<-- p   {font-size: 12pt} --> 

But this is wrong and the commenting out is ignored by the interpreter. It should produce:
/* p   {font-size: 12pt} */

**Comment by uranusjr** [comment]
We’re not implementing a code editor, and the hotkeys are built in a best-effort sense. You know what kind of comments to write. Just write it.

If you want this feature so badly, we do accept pull requests :)

**Comment by gkvallis** [comment]
Fair enough! It's certainly not a major issue - just thought I'd mention it.
