### ISSUE TITLE
Lists and block quotes require a blank line after for following text to render properly

### ISSUE THREAD

**Issue by mnemesh** [MacDownApp/macdown#984]
A couple of pictures is easier
![macdownscreensnapz001](https://user-images.githubusercontent.com/794940/40669734-a1707910-6335-11e8-8c2d-e068f0008b4e.png)
![macdownscreensnapz002](https://user-images.githubusercontent.com/794940/40669840-de677ae4-6335-11e8-9b78-d679e06afb55.png)

**Comment by Jmuccigr** [comment]
This is correct behavior. List items may contain line breaks.

**Comment by mnemesh** [comment]
Thanks. Seems odd, but it is what it is I suppose.

**Comment by Jmuccigr** [comment]
Line endings are allowed within elements in markdown, mostly so your text can look neat. Empty lines therefore carry meaning.

**Comment by franklinyu** [comment]
As @Jmuccigr said, this is expected. Minimal Working Example:

```markdown
1. foo
#h1
```

This rule is mentioned in [Section 5.2 List items](https://spec.commonmark.org/0.28/#list-items), subsection 5 Lasiness. See also [Example 253](https://spec.commonmark.org/0.28/#example-253) and [result from reference implementation](https://spec.commonmark.org/dingus/?text=1.%20foo%0A%23h1). GitHub rendering (note that GitHub shows line-break, which is not very CommonMark):

> 1. foo
> #h1
