### ISSUE TITLE
brew cask install is old

### ISSUE THREAD

**Issue by tedmiston** [MacDownApp/macdown#987]
The docs mention installing macdown via `$ brew cask install macdown`, however, looking at [macdown.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/macdown.rb), it points to the [0.7.1](https://github.com/MacDownApp/macdown/releases/tag/v0.7.1) release from May 2017.

It looks like this is the latest release, but there are currently 155 commits since then with a pretty huge diff.  Is it possible to either get a new release or perhaps we could add a note to the site that the Homebrew install is ~1 year old?

**Comment by uranusjr** [comment]
Well there really isn’t a stable release in between… There has been a few prereleases, but I’m not sure if Homebrew Cask accepts those. You can always install the old one and use the built-in upgrade mechanism anyway. I don’t think this is a problem.

**Comment by tedmiston** [comment]
In Homebrew, there are pre-installs flag for regular brew packages for this use case: `--devel` pulls latest develop and `--HEAD` pulls master branch.

From `$ brew install -h`:

> If --devel is passed, and formula defines it, install the development version.

> If --HEAD is passed, and formula defines it, install the HEAD version, aka master, trunk, unstable.

I tried on brew cask to get the same flags to work, but not sure if the issue is the config file for Macdown or that brew doesn't support these flags on cask installs.  Do these work for you?

The issue for me in the current 0.7.1 release is that Macdown doesn't reload the doc when it is edited in another app (I edit in my IDE, preview in Macdown).

**Comment by uranusjr** [comment]
I’m not sure if `--devel` and `--HEAD` apply for casks, however. They share the same `brew` command, but Casks are really quite different from Homebrew formulae.

**Comment by franklinyu** [comment]
Yes, it should be another Cask like `macdown-testing`.
