### ISSUE TITLE
How can I change the width of preview and output html ?

### ISSUE THREAD

**Issue by legoming** [MacDownApp/macdown#992]
I used **source code** and **table** very frequency, page is too narrow to show the table in well-formated style.

Is there any way to **enlarge** the **width** of html page?

**Comment by GiannisGG** [comment]
You mean a way different than dragging the sides or the middle separator?

**Comment by legoming** [comment]
no, I mean the exported html.

**Comment by franklinyu** [comment]
It should depend on your theme. There may be `max-width` somewhere in it.

**Comment by legoming** [comment]
@franklinyu yes, just look for something like max-width. And wondering if possible can set manually, such as I like git hub 2 theme, but wanna wider page ...

**Comment by franklinyu** [comment]
For theme `GitHub2` it’s

https://github.com/MacDownApp/macdown/blob/1af8db3d1345094e43bcc66741e1cdd667b4020d/MacDown/Resources/Styles/GitHub2.css#L299-L304

I don’t think there is good way to set it manually. It makes sense to be part of a style. If you want to customize, it’s easy to edit the style yourself, or create your own style.
